// Attack suite A, part 2: refusals before any change, and what a refused deploy leaves behind (A74, A77, A102, D115, D117, D155, D160, D161).
import { describe, expect, it } from 'vitest'
import {
  accountExists,
  count,
  createAccount,
  createRole,
  createTestDb,
  deploy,
  query,
  readerGrants,
  refusal,
  runScript,
  schemaExists,
  type TestDb,
  trackTestDbs,
  viewGrants,
} from './helpers/db.ts'

const { newDb } = trackTestDbs()

const markerless = (db: TestDb) =>
  query(
    `CREATE DATABASE \`${db.views}\`; CREATE TABLE \`${db.views}\`.keep (id INT); INSERT INTO \`${db.views}\`.keep VALUES (7);`,
  )

describe('MySQL deploy preconditions', () => {
  it('D117, D160, A102: no default database is refused before any change, with a fix', async () => {
    const db = await newDb()
    const result = query(db.files['redacted-views.sql'])
    const { message } = refusal(result, '1231')
    expect(message).toContain('no default database')
    expect(schemaExists(db.views)).toBe(false)
    expect(accountExists(db.reader)).toBe(false)
    // The fix works: select the source database and re-apply.
    expect(deploy(db).status).toBe(0)
  })

  it('D117: a default database equal to the views database is refused before any change', async () => {
    const db = await newDb()
    expect(markerless(db).status).toBe(0)
    const result = query(db.files['redacted-views.sql'], { database: db.views })
    const { message } = refusal(result)
    expect(message).toContain('default database is the views database')
    expect(count(`SELECT id FROM \`${db.views}\`.keep`)).toBe('7')
    expect(accountExists(db.reader)).toBe(false)
    // The remedy: select the source database. The views database is still foreign (no marker), so
    // the marker guard refuses next; once that database is dropped, the apply is green.
    expect(refusal(deploy(db)).message).toContain('has no hyde-db marker view')
    expect(query(`DROP DATABASE \`${db.views}\``).status).toBe(0)
    const again = deploy(db)
    expect(again.status, again.stderr).toBe(0)
    expect(readerGrants(db)).toEqual(viewGrants(db))
  })

  it('D115: a views database without the marker view is refused and nothing is dropped', async () => {
    const db = await newDb()
    expect(markerless(db).status).toBe(0)
    const result = deploy(db)
    const { message, fix } = refusal(result)
    expect(message).toContain('has no hyde-db marker view')
    expect(fix).toContain('"schema"')
    expect(count(`SELECT id FROM \`${db.views}\`.keep`)).toBe('7')
    expect(accountExists(db.reader)).toBe(false)
    // Pasting the fix (dropping the foreign database) as the administrator lets the re-apply pass.
    expect(query(`DROP DATABASE \`${db.views}\``).status).toBe(0)
    expect(deploy(db).status).toBe(0)
    expect(readerGrants(db)).toEqual(viewGrants(db))
  })

  it('D115: a views database whose marker view is a table of the same name is refused', async () => {
    const db = await newDb()
    expect(
      query(
        `CREATE DATABASE \`${db.views}\`; CREATE TABLE \`${db.views}\`.hyde_db_marker (marker VARCHAR(40)); INSERT INTO \`${db.views}\`.hyde_db_marker VALUES ('Generated by hyde-db');`,
      ).status,
    ).toBe(0)
    const { message } = refusal(deploy(db))
    expect(message).toContain('has no hyde-db marker view')
    expect(count(`SELECT COUNT(*) FROM \`${db.views}\`.hyde_db_marker`)).toBe('1')
  })

  it('A77, A102, D161: a deployer without read access to mysql.* is refused before any change; pasting the GRANT SELECT ON mysql.* fix makes a re-apply pass', async () => {
    const db = await newDb()
    const deployer = createAccount(db, {
      password: 'pw-deployer',
      grants: [
        `SELECT, CREATE TEMPORARY TABLES ON \`${db.name}\`.*`,
        `ALL PRIVILEGES ON \`${db.views}\`.*`,
        'CREATE USER ON *.*',
      ],
    })
    expect(
      query(`GRANT SELECT ON \`${db.views}\`.* TO '${deployer.user}'@'%' WITH GRANT OPTION`).status,
    ).toBe(0)
    const as = { user: deployer.user, password: deployer.password }
    const result = runScript(db, db.files['redacted-views.sql'], { as })
    const { message, fix } = refusal(result)
    expect(message).toContain('cannot read the MySQL grant tables')
    expect(fix).toBe(`GRANT SELECT ON mysql.* TO '${deployer.user}'@'%';`)
    expect(schemaExists(db.views)).toBe(false)
    expect(accountExists(db.reader)).toBe(false)
    expect(query(fix).status).toBe(0)
    const again = runScript(db, db.files['redacted-views.sql'], { as })
    expect(again.status, again.stderr).toBe(0)
    expect(readerGrants(db)).toEqual(viewGrants(db))
  })

  it('A102, D99: a deployer without CREATE TEMPORARY TABLES on the source database is refused at the temporary-table step; granting it makes a re-apply pass', async () => {
    const db = await newDb()
    const deployer = createAccount(db, {
      password: 'pw-deployer',
      grants: [
        `SELECT ON \`${db.name}\`.*`,
        `ALL PRIVILEGES ON \`${db.views}\`.*`,
        'SELECT ON mysql.*',
        'CREATE USER ON *.*',
      ],
    })
    expect(
      query(`GRANT SELECT ON \`${db.views}\`.* TO '${deployer.user}'@'%' WITH GRANT OPTION`).status,
    ).toBe(0)
    const as = { user: deployer.user, password: deployer.password }
    const script = db.files['redacted-views.sql']
    const result = runScript(db, script, { as })
    expect(result.status).not.toBe(0)
    const step =
      script.split('\n').findIndex((line) => line.startsWith('CREATE TEMPORARY TABLE')) + 1
    expect(step).toBeGreaterThan(0)
    expect(result.stderr).toMatch(
      new RegExp(`^ERROR 1044 \\(42000\\) at line ${step}: Access denied`),
    )
    expect(schemaExists(db.views)).toBe(false)
    expect(accountExists(db.reader)).toBe(false)
    expect(
      query(`GRANT CREATE TEMPORARY TABLES ON \`${db.name}\`.* TO '${deployer.user}'@'%'`).status,
    ).toBe(0)
    const again = runScript(db, script, { as })
    expect(again.status, again.stderr).toBe(0)
    expect(readerGrants(db)).toEqual(viewGrants(db))
  })

  it('D115: a model whose table is hyde_db_marker fails at generate time, not at deploy time', async () => {
    const source = `
generator redacted {
  provider = "hyde-db"
}
datasource db {
  provider = "mysql"
}
model Marker {
  /// @hyde.visible
  id Int @id

  @@map("hyde_db_marker")
}
`
    await expect(createTestDb({ schemaSource: source })).rejects.toThrow(/hyde_db_marker/)
  })

  describe('a refused deploy (A74, D101, D155, D161)', () => {
    /** The views database as a comparable text: its objects with their definitions, and the sentinel row. */
    const viewsContent = (db: TestDb) =>
      [
        query(
          `SELECT TABLE_NAME, TABLE_TYPE FROM information_schema.TABLES WHERE TABLE_SCHEMA = '${db.views}' ORDER BY TABLE_NAME`,
        ).stdout,
        query(
          `SELECT TABLE_NAME, VIEW_DEFINITION, DEFINER FROM information_schema.VIEWS WHERE TABLE_SCHEMA = '${db.views}' ORDER BY TABLE_NAME`,
        ).stdout,
        query(`SELECT id, note FROM \`${db.views}\`.sentinel`).stdout,
      ].join('\n')
    /** What the ungated reader-wide revoke (D155) leaves: only proxies, roles and default roles. */
    const afterRefusal = (before: string[]) =>
      before.filter((g) => /^(proxy|role|default role): /.test(g))

    /**
     * Deploys cleanly, adds a sentinel table to the views database, makes the next apply refuse and
     * returns the printed fix. The views database must be unchanged (sentinel included) and the
     * reader must hold nothing it did not hold before.
     */
    async function refusedDb(
      sabotage: (db: TestDb) => void,
    ): Promise<{ db: TestDb; fix: string; message: string; grants: string[]; content: string }> {
      const db = await newDb()
      expect(deploy(db).status).toBe(0)
      expect(
        query(
          `CREATE TABLE \`${db.views}\`.sentinel (id INT, note VARCHAR(20)); INSERT INTO \`${db.views}\`.sentinel VALUES (1, 'kept');`,
        ).status,
      ).toBe(0)
      sabotage(db)
      const grantsBefore = readerGrants(db)
      const content = viewsContent(db)
      expect(content).toContain('kept')
      const refused = refusal(deploy(db))
      expect(viewsContent(db)).toBe(content)
      const grants = readerGrants(db)
      expect(grants).toEqual(afterRefusal(grantsBefore))
      return { db, ...refused, grants, content }
    }
    const reader = (db: TestDb) => `'${db.reader}'@'${db.host}'`

    it('A74, D101, D155: a refusal drops nothing, also under --force; the reader is left with no view grant (the revoke is ungated)', async () => {
      const { db, grants, content } = await refusedDb((db) => {
        const other = createAccount(db)
        expect(query(`GRANT PROXY ON '${other.user}'@'%' TO ${reader(db)}`).status).toBe(0)
        expect(query(`GRANT SELECT ON \`${db.name}\`.* TO ${reader(db)}`).status).toBe(0)
      })
      expect(grants).toHaveLength(1)
      expect(grants[0]).toMatch(/^proxy: /)
      // Under --force the client runs on past the refusal: every statement from the drop on is gated (D155).
      const forced = runScript(db, db.files['redacted-views.sql'], { force: true })
      expect(forced.stderr).toContain('hyde-db:')
      expect(viewsContent(db)).toBe(content) // the sentinel survives: no DROP DATABASE ran
      expect(readerGrants(db)).toEqual(grants)
    })

    it('A74: no refused deploy grants the reader more than it held before', async () => {
      const { grants } = await refusedDb((db) => {
        const role = createRole(db)
        expect(query(`GRANT '${role.user}'@'%' TO ${reader(db)}`).status).toBe(0)
        expect(query(`GRANT SELECT ON \`${db.name}\`.* TO ${reader(db)}`).status).toBe(0)
      })
      expect(grants).toHaveLength(1)
      expect(grants[0]).toMatch(/^role: /)
    })

    /** Pastes the fix as the administrator and expects a green re-apply that leaves exactly the view grants. */
    function pasteAndReapply(db: TestDb, fix: string): void {
      expect(query(fix).status).toBe(0)
      const again = deploy(db)
      expect(again.status, again.stderr).toBe(0)
      expect(readerGrants(db)).toEqual(viewGrants(db))
    }

    it('D161: a proxy grant is refused with a per-object fix that works when pasted', async () => {
      const { db, fix } = await refusedDb((db) => {
        const other = createAccount(db)
        expect(query(`GRANT PROXY ON '${other.user}'@'%' TO ${reader(db)}`).status).toBe(0)
      })
      expect(fix).toMatch(/^REVOKE PROXY ON '.+'@'%' FROM '.+'@'%';$/)
      pasteAndReapply(db, fix)
    })

    it('D161: a role granted to the reader is refused with a per-object fix that works when pasted', async () => {
      const { db, fix } = await refusedDb((db) => {
        const role = createRole(db)
        expect(query(`GRANT '${role.user}'@'%' TO ${reader(db)}`).status).toBe(0)
      })
      expect(fix).toMatch(/^REVOKE '.+'@'%' FROM '.+'@'%';$/)
      pasteAndReapply(db, fix)
    })

    it('D161: a default role on the reader is refused with a fix that works when pasted', async () => {
      const { db, fix } = await refusedDb((db) => {
        const role = createRole(db)
        expect(query(`GRANT '${role.user}'@'%' TO ${reader(db)}`).status).toBe(0)
        expect(query(`SET DEFAULT ROLE '${role.user}'@'%' TO ${reader(db)}`).status).toBe(0)
      })
      // Roles are refused first (rank 7 before 8); revoking the role removes its default-role row too.
      pasteAndReapply(db, fix)
    })

    it('D161: another account that could match a reader login is refused with a DROP USER fix that works when pasted', async () => {
      const { db, fix } = await refusedDb((db) => {
        db.extras.push({ user: db.reader, host: 'localhost' })
        expect(query(`CREATE USER '${db.reader}'@'localhost'`).status).toBe(0)
      })
      expect(fix).toBe(`DROP USER '${db.reader}'@'localhost';`)
      pasteAndReapply(db, fix)
    })

    it('D161: an anonymous account is refused with a DROP USER fix that works when pasted', async () => {
      const { db, fix } = await refusedDb((db) => {
        // Unique host, so it neither collides with an anonymous account of the server nor leaks.
        db.extras.push({ user: '', host: `anon-${db.name}.example` })
        expect(query(`CREATE USER ''@'anon-${db.name}.example'`).status).toBe(0)
      })
      expect(fix).toBe(`DROP USER ''@'anon-${db.name}.example';`)
      pasteAndReapply(db, fix)
    })
  })
})
