// Attack suite A, part 2: refusals before any change, and what a refused deploy leaves behind (A74, A77, A102, D115, D117, D155, D160, D161).
import { afterEach, describe, expect, it } from 'vitest'
import {
  type ClientResult,
  createAccount,
  createRole,
  createTestDb,
  deploy,
  dropTestDb,
  query,
  readerGrants,
  runScript,
  type TestDb,
} from './helpers/db.ts'

const created: TestDb[] = []
async function newDb(options?: Parameters<typeof createTestDb>[0]): Promise<TestDb> {
  const db = await createTestDb(options)
  created.push(db)
  return db
}
afterEach(async () => {
  for (const db of created.splice(0)) await dropTestDb(db)
})

const viewGrants = (db: TestDb) => [
  `table: ${db.views}.orders Select|`,
  `table: ${db.views}.users Select|`,
]
const count = (sql: string) => query(sql).stdout.trim()
const schemaExists = (name: string) =>
  count(`SELECT COUNT(*) FROM information_schema.SCHEMATA WHERE SCHEMA_NAME = '${name}'`) === '1'
const accountExists = (user: string) =>
  count(`SELECT COUNT(*) FROM mysql.user WHERE User = '${user}'`) === '1'

/**
 * Asserts a refusal (non-zero status, a hyde-db message with a fix, at most 128 characters) and
 * returns the problem and the fix as printed. The message sits in a 1366 (temporary table) or, with
 * no default database, 1231 (sql_warnings) error (A102, D160).
 */
function refusal(
  result: ClientResult,
  code: '1366' | '1231' = '1366',
): { message: string; fix: string } {
  expect(result.status, result.stderr).not.toBe(0)
  expect(result.stderr).toContain(`ERROR ${code}`)
  expect(result.stderr).toContain('hyde-db:')
  expect(result.stderr).toContain('Fix:')
  const found = /(hyde-db: .*? Fix: .*?)'(?: for column|$)/m.exec(result.stderr)
  expect(found, result.stderr).not.toBeNull()
  const message = found?.[1] ?? ''
  expect(message.length).toBeLessThanOrEqual(128)
  return { message, fix: message.slice(message.indexOf(' Fix: ') + ' Fix: '.length) }
}

const markerless = (db: TestDb) =>
  query(
    `CREATE DATABASE \`${db.views}\`; CREATE TABLE \`${db.views}\`.keep (id INT); INSERT INTO \`${db.views}\`.keep VALUES (7);`,
  )

describe('MySQL deploy preconditions', () => {
  it('D117, D160, A102: no default database is refused before any change, with a fix', async () => {
    const db = await newDb()
    const result = query(db.files['redacted-views.sql'])
    const { message } = refusal(result, '1231')
    expect(message).toContain('no default database')
    expect(schemaExists(db.views)).toBe(false)
    expect(accountExists(db.reader)).toBe(false)
    // The fix works: select the source database and re-apply.
    expect(deploy(db).status).toBe(0)
  })

  it('D117: a default database equal to the views database is refused before any change', async () => {
    const db = await newDb()
    expect(markerless(db).status).toBe(0)
    const result = query(db.files['redacted-views.sql'], { database: db.views })
    const { message } = refusal(result)
    expect(message).toContain('default database is the views database')
    expect(count(`SELECT id FROM \`${db.views}\`.keep`)).toBe('7')
    expect(accountExists(db.reader)).toBe(false)
    expect(deploy(db).status).not.toBe(0) // still the marker guard
  })

  it('D115: a views database without the marker view is refused and nothing is dropped', async () => {
    const db = await newDb()
    expect(markerless(db).status).toBe(0)
    const result = deploy(db)
    const { message, fix } = refusal(result)
    expect(message).toContain('has no hyde-db marker view')
    expect(fix).toContain('"schema"')
    expect(count(`SELECT id FROM \`${db.views}\`.keep`)).toBe('7')
    expect(accountExists(db.reader)).toBe(false)
    // Pasting the fix (dropping the foreign database) as the administrator lets the re-apply pass.
    expect(query(`DROP DATABASE \`${db.views}\``).status).toBe(0)
    expect(deploy(db).status).toBe(0)
    expect(readerGrants(db)).toEqual(viewGrants(db))
  })

  it('D115: a views database whose marker view is a table of the same name is refused', async () => {
    const db = await newDb()
    expect(
      query(
        `CREATE DATABASE \`${db.views}\`; CREATE TABLE \`${db.views}\`.hyde_db_marker (marker VARCHAR(40)); INSERT INTO \`${db.views}\`.hyde_db_marker VALUES ('Generated by hyde-db');`,
      ).status,
    ).toBe(0)
    const { message } = refusal(deploy(db))
    expect(message).toContain('has no hyde-db marker view')
    expect(count(`SELECT COUNT(*) FROM \`${db.views}\`.hyde_db_marker`)).toBe('1')
  })

  it('A77, A102, D161: a deployer without read access to mysql.* is refused before any change; pasting the GRANT SELECT ON mysql.* fix makes a re-apply pass', async () => {
    const db = await newDb()
    const deployer = createAccount(db, {
      password: 'pw-deployer',
      grants: [
        `SELECT, CREATE TEMPORARY TABLES ON \`${db.name}\`.*`,
        `ALL PRIVILEGES ON \`${db.views}\`.*`,
        'CREATE USER ON *.*',
      ],
    })
    expect(
      query(`GRANT SELECT ON \`${db.views}\`.* TO '${deployer.user}'@'%' WITH GRANT OPTION`).status,
    ).toBe(0)
    const as = { user: deployer.user, password: deployer.password }
    const result = runScript(db, db.files['redacted-views.sql'], { as })
    const { message, fix } = refusal(result)
    expect(message).toContain('cannot read the MySQL grant tables')
    expect(fix).toBe(`GRANT SELECT ON mysql.* TO '${deployer.user}'@'%';`)
    expect(schemaExists(db.views)).toBe(false)
    expect(accountExists(db.reader)).toBe(false)
    expect(query(fix).status).toBe(0)
    const again = runScript(db, db.files['redacted-views.sql'], { as })
    expect(again.status, again.stderr).toBe(0)
    expect(readerGrants(db)).toEqual(viewGrants(db))
  })

  it('A102: a deployer without CREATE TEMPORARY TABLES on the source database cannot even start the abort table', async () => {
    const db = await newDb()
    const deployer = createAccount(db, {
      password: 'pw-deployer',
      grants: [`SELECT ON \`${db.name}\`.*`, 'SELECT ON mysql.*', 'CREATE USER ON *.*'],
    })
    const result = runScript(db, db.files['redacted-views.sql'], {
      as: { user: deployer.user, password: deployer.password },
    })
    expect(result.status).not.toBe(0)
    expect(result.stderr).toMatch(/ERROR 1044|ERROR 1142/)
    expect(schemaExists(db.views)).toBe(false)
    expect(accountExists(db.reader)).toBe(false)
  })

  it('D115: a model whose table is hyde_db_marker fails at generate time, not at deploy time', async () => {
    const source = `
generator redacted {
  provider = "hyde-db"
}
datasource db {
  provider = "mysql"
}
model Marker {
  /// @hyde.visible
  id Int @id

  @@map("hyde_db_marker")
}
`
    await expect(createTestDb({ schemaSource: source })).rejects.toThrow(/hyde_db_marker/)
  })

  describe('a refused deploy (A74, D101, D155, D161)', () => {
    /** Deploys cleanly, then makes the next apply refuse; returns the printed fix. */
    async function refusedDb(
      sabotage: (db: TestDb) => void,
    ): Promise<{ db: TestDb; fix: string; message: string }> {
      const db = await newDb()
      expect(deploy(db).status).toBe(0)
      sabotage(db)
      const result = deploy(db)
      return { db, ...refusal(result) }
    }
    const reader = (db: TestDb) => `'${db.reader}'@'${db.host}'`

    it('A74, D101: a refusal leaves the views built, drops nothing and leaves the reader with no grant (the revoke is ungated, D155)', async () => {
      const { db } = await refusedDb((db) => {
        const other = createAccount(db)
        expect(query(`GRANT PROXY ON '${other.user}'@'%' TO ${reader(db)}`).status).toBe(0)
        expect(query(`GRANT SELECT ON \`${db.name}\`.* TO ${reader(db)}`).status).toBe(0)
      })
      expect(readerGrants(db).filter((g) => g.startsWith('proxy:'))).toHaveLength(1)
      expect(readerGrants(db).some((g) => g.startsWith('db:'))).toBe(false)
      expect(readerGrants(db).some((g) => g.startsWith('table:'))).toBe(false)
      // The views database was not touched: gated statements after the refusal did not run.
      expect(count(`SELECT COUNT(*) FROM \`${db.views}\`.users`)).toBe('1')
      expect(count(`SELECT COUNT(*) FROM \`${db.views}\`.hyde_db_marker`)).toBe('1')
      // Under --force the client runs on past the refusal: every statement from the drop on is gated (D155).
      const forced = runScript(db, db.files['redacted-views.sql'], { force: true })
      expect(forced.status).toBe(0)
      expect(forced.stderr).toContain('hyde-db:')
      expect(count(`SELECT COUNT(*) FROM \`${db.views}\`.users`)).toBe('1')
      expect(count(`SELECT COUNT(*) FROM \`${db.views}\`.hyde_db_marker`)).toBe('1')
      expect(readerGrants(db).some((g) => g.startsWith('table:') || g.startsWith('db:'))).toBe(
        false,
      )
    })

    it('A74: no refused deploy grants the reader more than it held before', async () => {
      const { db } = await refusedDb((db) => {
        const role = createRole(db)
        expect(query(`GRANT '${role.user}'@'%' TO ${reader(db)}`).status).toBe(0)
        expect(query(`GRANT SELECT ON \`${db.name}\`.* TO ${reader(db)}`).status).toBe(0)
      })
      const grants = readerGrants(db)
      expect(grants.every((g) => g.startsWith('role:'))).toBe(true)
    })

    it('D161: a proxy grant is refused with a per-object fix that works when pasted', async () => {
      const { db, fix } = await refusedDb((db) => {
        const other = createAccount(db)
        expect(query(`GRANT PROXY ON '${other.user}'@'%' TO ${reader(db)}`).status).toBe(0)
      })
      expect(fix).toMatch(/^REVOKE PROXY ON '.+'@'%' FROM '.+'@'%';$/)
      expect(query(fix).status).toBe(0)
      const again = deploy(db)
      expect(again.status, again.stderr).toBe(0)
      expect(readerGrants(db)).toEqual(viewGrants(db))
    })

    it('D161: a role granted to the reader is refused with a per-object fix that works when pasted', async () => {
      const { db, fix } = await refusedDb((db) => {
        const role = createRole(db)
        expect(query(`GRANT '${role.user}'@'%' TO ${reader(db)}`).status).toBe(0)
      })
      expect(fix).toMatch(/^REVOKE '.+'@'%' FROM '.+'@'%';$/)
      expect(query(fix).status).toBe(0)
      const again = deploy(db)
      expect(again.status, again.stderr).toBe(0)
      expect(readerGrants(db)).toEqual(viewGrants(db))
    })

    it('D161: a default role on the reader is refused with a fix that works when pasted', async () => {
      const { db, fix } = await refusedDb((db) => {
        const role = createRole(db)
        expect(query(`GRANT '${role.user}'@'%' TO ${reader(db)}`).status).toBe(0)
        expect(query(`SET DEFAULT ROLE '${role.user}'@'%' TO ${reader(db)}`).status).toBe(0)
      })
      // Roles are refused first (rank 7 before 8); revoking the role removes its default-role row too.
      expect(query(fix).status).toBe(0)
      const again = deploy(db)
      expect(again.status, again.stderr).toBe(0)
      expect(readerGrants(db)).toEqual(viewGrants(db))
    })

    it('D161: another account that could match a reader login is refused with a DROP USER fix that works when pasted', async () => {
      const { db, fix } = await refusedDb((db) => {
        db.extras.push({ user: db.reader, host: 'localhost' })
        expect(query(`CREATE USER '${db.reader}'@'localhost'`).status).toBe(0)
      })
      expect(fix).toBe(`DROP USER '${db.reader}'@'localhost';`)
      expect(query(fix).status).toBe(0)
      const again = deploy(db)
      expect(again.status, again.stderr).toBe(0)
    })

    it('D161: the anonymous account is refused with a DROP USER fix that works when pasted', async () => {
      const db = await newDb()
      expect(deploy(db).status).toBe(0)
      const existing = count("SELECT COUNT(*) FROM mysql.user WHERE User = ''")
      if (existing !== '0') return // a server that already has an anonymous account is not ours to touch
      db.extras.push({ user: '', host: 'anon.example' })
      expect(query("CREATE USER ''@'anon.example'").status).toBe(0)
      const { fix } = refusal(deploy(db))
      expect(fix).toBe("DROP USER ''@'anon.example';")
      expect(query(fix).status).toBe(0)
      expect(deploy(db).status).toBe(0)
    })
  })
})
