// Attack suite: the whole-branch review's findings (A105, D165, D166, D168): a views database
// that belongs to another source database, a check whose query fails under `mysql --force`, and a
// leftover global privilege seen by a deployer with only table-level SELECT on the grant tables.
import { describe, expect, it } from 'vitest'
import {
  accountExists,
  count,
  createAccount,
  deploy,
  query,
  readerGrants,
  refusal,
  runScript,
  schemaExists,
  type TestDb,
  trackTestDbs,
  viewGrants,
} from './helpers/db.ts'

const { newDb } = trackTestDbs()

/** The first hyde-db abort message in the errors of a `--force` run (the client exits 0 when it runs past errors). */
function forcedRefusal(result: { stderr: string }): { message: string; fix: string } {
  expect(result.stderr).toContain('ERROR 1366')
  const found = /'(hyde-db: .*? Fix: .*?)'(?: for column|$)/m.exec(result.stderr)
  expect(found, result.stderr).not.toBeNull()
  const message = found?.[1] ?? ''
  expect(message.length).toBeLessThanOrEqual(128)
  return { message, fix: message.slice(message.indexOf(' Fix: ') + ' Fix: '.length) }
}

const GRANT_TABLES = [
  'user',
  'global_grants',
  'db',
  'tables_priv',
  'columns_priv',
  'procs_priv',
  'proxies_priv',
  'default_roles',
  'role_edges',
]

/** A deployer with exactly the README's privilege set (no SHOW VIEW, no ALL) except those named in `without` (mysql tables it may not read fully). */
function deployerFor(db: TestDb, options: { without?: string[]; createUser?: boolean } = {}) {
  const deployer = createAccount(db, {
    password: 'pw-deployer',
    grants: [
      `SELECT, CREATE TEMPORARY TABLES ON \`${db.name}\`.*`,
      `CREATE, DROP, CREATE VIEW, SELECT ON \`${db.views}\`.*`,
      ...GRANT_TABLES.filter((t) => !options.without?.includes(t)).map(
        (t) => `SELECT ON mysql.${t}`,
      ),
      ...(options.createUser === false ? [] : ['CREATE USER ON *.*']),
    ],
  })
  expect(
    query(`GRANT SELECT ON \`${db.views}\`.* TO '${deployer.user}'@'%' WITH GRANT OPTION`).status,
  ).toBe(0)
  return { user: deployer.user, password: deployer.password }
}

describe('A105, D165: a views database belongs to one source database', () => {
  async function twoSources() {
    const first = await newDb()
    const second = await newDb({ config: { schema: first.views } })
    return { first, second }
  }

  it('the second apply with the same schema is refused and changes nothing', async () => {
    const { first, second } = await twoSources()
    expect(deploy(first).status).toBe(0)
    expect(query(`CREATE TABLE \`${first.views}\`.sentinel (id INT)`).status).toBe(0)
    const before = readerGrants(first)
    expect(before).toEqual(viewGrants(first))
    const { message, fix } = refusal(deploy(second))
    expect(message).toBe(
      `hyde-db: database ${first.views} belongs to source database ${first.name}. Fix: set "schema" to an unused name`,
    )
    expect(fix).toBe('set "schema" to an unused name')
    expect(count(`SELECT COUNT(*) FROM \`${first.views}\`.sentinel`)).toBe('0')
    expect(readerGrants(first)).toEqual(before)
    expect(accountExists(second.reader)).toBe(false)
    expect(readerGrants(second)).toEqual([])
  })

  it('under --force the refused second apply still builds and grants nothing', async () => {
    const { first, second } = await twoSources()
    expect(deploy(first).status).toBe(0)
    expect(query(`CREATE TABLE \`${first.views}\`.sentinel (id INT)`).status).toBe(0)
    const before = readerGrants(first)
    const result = runScript(second, second.files['redacted-views.sql'], { force: true })
    expect(forcedRefusal(result).message).toContain('belongs to source database')
    expect(count(`SELECT COUNT(*) FROM \`${first.views}\`.sentinel`)).toBe('0')
    expect(readerGrants(first)).toEqual(before)
    expect(readerGrants(second)).toEqual([])
  })

  it('the same source re-applies, and distinct schemas both deploy', async () => {
    const first = await newDb()
    const second = await newDb()
    expect(deploy(first).status).toBe(0)
    expect(deploy(first).status).toBe(0)
    expect(deploy(second).status).toBe(0)
    expect(readerGrants(first)).toEqual(viewGrants(first))
    expect(readerGrants(second)).toEqual(viewGrants(second))
  })

  it('the marker records the source database in a second column', async () => {
    const db = await newDb()
    expect(deploy(db).status).toBe(0)
    expect(count(`SELECT marker, source FROM \`${db.views}\`.hyde_db_marker`)).toBe(
      `Generated by hyde-db\t${db.name}`,
    )
  })

  it('the drop script from the wrong source is refused and changes nothing', async () => {
    const { first, second } = await twoSources()
    expect(deploy(first).status).toBe(0)
    const before = readerGrants(first)
    const { message } = refusal(runScript(second, second.files['redacted-views-drop.sql']))
    expect(message).toContain(`belongs to source database ${first.name}`)
    expect(schemaExists(first.views)).toBe(true)
    expect(readerGrants(first)).toEqual(before)
    const own = runScript(first, first.files['redacted-views-drop.sql'])
    expect(own.status, own.stderr).toBe(0)
    expect(schemaExists(first.views)).toBe(false)
  })

  it('a marker without a source column is refused like a missing marker', async () => {
    const db = await newDb()
    expect(
      query(
        `CREATE DATABASE \`${db.views}\`; CREATE VIEW \`${db.views}\`.hyde_db_marker AS SELECT 'Generated by hyde-db' AS marker;`,
      ).status,
    ).toBe(0)
    expect(refusal(deploy(db)).message).toContain('has no hyde-db marker view')
    expect(schemaExists(db.views)).toBe(true)
    expect(accountExists(db.reader)).toBe(false)
  })

  it('A106: a deployer that is not the marker definer and lacks SHOW VIEW, with exactly the README privileges, can re-apply', async () => {
    const db = await newDb()
    expect(deploy(db).status).toBe(0)
    const as = deployerFor(db)
    // Premise: VIEW_DEFINITION is empty for this deployer, so only a read through the view works.
    expect(
      query(
        `SELECT LENGTH(VIEW_DEFINITION) FROM information_schema.VIEWS WHERE TABLE_SCHEMA = '${db.views}' AND TABLE_NAME = 'hyde_db_marker'`,
        { as },
      ).stdout.trim(),
    ).toBe('0')
    const again = runScript(db, db.files['redacted-views.sql'], { as })
    expect(again.status, again.stderr).toBe(0)
    expect(readerGrants(db)).toEqual(viewGrants(db))
  })

  it('D169: an INVOKER marker view is never selected from, and is refused as a missing marker', async () => {
    const db = await newDb()
    const bait = `bait_${db.views}`
    try {
      // The view would pass the guard if read (right marker, right source); the bait table is one
      // the deployer cannot read, so a read as the deployer would fail with ERROR 1356 or 1142.
      expect(
        query(
          `CREATE DATABASE \`${db.views}\`; CREATE DATABASE \`${bait}\`; CREATE TABLE \`${bait}\`.t (s VARCHAR(64)); INSERT INTO \`${bait}\`.t VALUES ('${db.name}');
           CREATE SQL SECURITY INVOKER VIEW \`${db.views}\`.hyde_db_marker AS SELECT 'Generated by hyde-db' AS marker, s AS source FROM \`${bait}\`.t;
           CREATE TABLE \`${db.views}\`.keep (id INT);`,
        ).status,
      ).toBe(0)
      const as = deployerFor(db)
      const result = runScript(db, db.files['redacted-views.sql'], { as })
      expect(result.stderr).not.toMatch(/ERROR (1356|1142|1143)/)
      expect(refusal(result).message).toContain('has no hyde-db marker view')
      // As root the read would succeed and the guard would pass; the refusal proves it never ran.
      expect(refusal(deploy(db)).message).toContain('has no hyde-db marker view')
      expect(count(`SELECT COUNT(*) FROM \`${db.views}\`.keep`)).toBe('0')
      expect(accountExists(db.reader)).toBe(false)
    } finally {
      query(`DROP DATABASE IF EXISTS \`${bait}\``)
    }
  })

  it('D169: a marker whose definer was dropped is refused as unreadable, naming the definer; re-creating it passes', async () => {
    const db = await newDb()
    const first = deployerFor(db)
    const first_ = runScript(db, db.files['redacted-views.sql'], { as: first })
    expect(first_.status, first_.stderr).toBe(0)
    expect(query(`DROP USER '${first.user}'@'%'`).status).toBe(0)
    const second = deployerFor(db)
    const before = readerGrants(db)
    // Without --force the failed read itself stops the script (ERROR 1045/1449); nothing changed.
    const plain = runScript(db, db.files['redacted-views.sql'], { as: second })
    expect(plain.status).not.toBe(0)
    expect(plain.stderr).toMatch(/ERROR (1045|1449)/)
    expect(readerGrants(db)).toEqual(before)
    // With --force the read leaves NULLs and the guard names the cause.
    const { message, fix } = forcedRefusal(
      runScript(db, db.files['redacted-views.sql'], { as: second, force: true }),
    )
    expect(message).toBe(
      `hyde-db: the marker view of ${db.views} cannot be read. Fix: re-create its definer ${first.user}@% or drop database ${db.views}`,
    )
    expect(fix).toBe(`re-create its definer ${first.user}@% or drop database ${db.views}`)
    // The reader reset is not gated (D119), so a --force run revokes the reader's grants; the views stay.
    expect(schemaExists(db.views)).toBe(true)
    expect(query(`CREATE USER '${first.user}'@'%'`).status).toBe(0)
    const again = runScript(db, db.files['redacted-views.sql'], { as: second })
    expect(again.status, again.stderr).toBe(0)
    expect(readerGrants(db)).toEqual(viewGrants(db))
  })
})

describe('D166: a check that cannot run refuses under --force', () => {
  it('a deployer that may read only one column of proxies_priv is refused and grants nothing', async () => {
    const db = await newDb()
    const as = deployerFor(db, { without: ['proxies_priv'] })
    expect(query(`GRANT SELECT (User) ON mysql.proxies_priv TO '${as.user}'@'%'`).status).toBe(0)
    const result = runScript(db, db.files['redacted-views.sql'], { as, force: true })
    expect(result.stderr).toContain('ERROR 1143')
    const { message, fix } = forcedRefusal(result)
    expect(message).toBe(
      'hyde-db: check proxies could not run. Fix: run without --force and read the first error',
    )
    expect(fix).toBe('run without --force and read the first error')
    expect(schemaExists(db.views)).toBe(false)
    expect(accountExists(db.reader)).toBe(false)
    expect(readerGrants(db)).toEqual([])
  })

  it('the same deployer without --force stops at the first error and grants nothing', async () => {
    const db = await newDb()
    const as = deployerFor(db, { without: ['proxies_priv'] })
    expect(query(`GRANT SELECT (User) ON mysql.proxies_priv TO '${as.user}'@'%'`).status).toBe(0)
    const result = runScript(db, db.files['redacted-views.sql'], { as })
    expect(result.status).not.toBe(0)
    expect(schemaExists(db.views)).toBe(false)
    expect(readerGrants(db)).toEqual([])
  })
})

describe('D168: the leftover-grant check reads mysql.user, not information_schema', () => {
  it('a reader global privilege that the reset cannot remove is refused for a deployer with table-level SELECT only', async () => {
    const db = await newDb()
    // The deployer lacks CREATE USER, so its reset REVOKE fails and `--force` runs past it (the
    // privilege then survives to the check, as a grant made between the reset and the check would).
    const as = deployerFor(db, { createUser: false })
    expect(
      query(
        `CREATE USER '${db.reader}'@'${db.host}' ACCOUNT LOCK; GRANT SELECT ON *.* TO '${db.reader}'@'${db.host}';`,
      ).status,
    ).toBe(0)
    // Premise: information_schema hides the reader's global privilege from this deployer.
    expect(
      query(
        `SELECT COUNT(*) FROM information_schema.USER_PRIVILEGES WHERE GRANTEE = '''${db.reader}''@''${db.host}'''`,
        { as },
      ).stdout.trim(),
    ).toBe('0')
    const before = readerGrants(db)
    expect(before).toEqual(['global: select_priv'])
    const result = runScript(db, db.files['redacted-views.sql'], { as, force: true })
    const { message, fix } = forcedRefusal(result)
    expect(message).toContain('the reader has a global privilege')
    expect(fix).toBe(`REVOKE SELECT ON *.* FROM '${db.reader}'@'${db.host}';`)
    expect(schemaExists(db.views)).toBe(false)
    expect(readerGrants(db)).toEqual(before)
    // The printed fix works when pasted.
    expect(query(fix).status).toBe(0)
    expect(readerGrants(db)).toEqual([])
  })
})
