-- GENERATED by prisma-ai-views. Run BEFORE `prisma migrate deploy` so that
-- migrations can drop/alter columns that the AI views depend on.
SET client_min_messages = warning;
DROP SCHEMA IF EXISTS "ai" CASCADE;
