-- GENERATED by prisma-ai-views from schema.prisma. Do not edit by hand.
-- Recreates schema ai with column-filtered views and grants role ai_reader
-- read access to exactly those views. Run AFTER `prisma migrate deploy`.
-- The whole script is one transaction; the final check aborts it if the role
-- could read anything outside the views.

SET client_min_messages = warning;
BEGIN;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ai_reader') THEN
    CREATE ROLE "ai_reader" NOLOGIN;
  END IF;
END $$;

DROP SCHEMA IF EXISTS "ai" CASCADE;
CREATE SCHEMA "ai";
COMMENT ON SCHEMA "ai" IS 'Generated by prisma-ai-views. Read-only, PII-filtered views for AI/LLM access. Recreated on every deploy.';

CREATE VIEW "ai"."users" AS SELECT
  "id",
  "created_at",
  "country",
  "plan"
FROM "public"."users";
COMMENT ON VIEW "ai"."users" IS 'A customer account.';
COMMENT ON COLUMN "ai"."users"."country" IS 'ISO 3166 country code';

CREATE VIEW "ai"."orders" AS SELECT
  "id",
  "user_id",
  "total_cents",
  "placed_at"
FROM "public"."orders";
COMMENT ON COLUMN "ai"."orders"."total_cents" IS 'Total in cents';

-- Privileges: nothing but SELECT on the views in ai.
REVOKE ALL ON SCHEMA "public" FROM "ai_reader";
REVOKE ALL ON ALL TABLES IN SCHEMA "public" FROM "ai_reader";
GRANT USAGE ON SCHEMA "ai" TO "ai_reader";
GRANT SELECT ON ALL TABLES IN SCHEMA "ai" TO "ai_reader";

-- Defence in depth for the session itself.
ALTER ROLE "ai_reader" SET default_transaction_read_only = on;
ALTER ROLE "ai_reader" SET statement_timeout = '15s';
ALTER ROLE "ai_reader" SET search_path = "ai";
ALTER ROLE "ai_reader" NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;

-- Safety check: abort if the role can read any relation outside the AI schema
-- (e.g. via PUBLIC grants or membership in another role).
DO $$
DECLARE leaks text;
BEGIN
  SELECT string_agg(format('%I.%I', n.nspname, c.relname), ', ' ORDER BY 1) INTO leaks
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE c.relkind IN ('r', 'p', 'v', 'm', 'f')
    AND n.nspname NOT IN ('ai', 'pg_catalog', 'information_schema')
    AND n.nspname NOT LIKE 'pg\_%'
    AND (has_table_privilege('ai_reader', c.oid, 'SELECT')
         OR has_any_column_privilege('ai_reader', c.oid, 'SELECT'));
  IF leaks IS NOT NULL THEN
    RAISE EXCEPTION 'prisma-ai-views: role ai_reader can read relations outside schema ai: %', leaks;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_auth_members m JOIN pg_roles r ON r.oid = m.member
             WHERE r.rolname = 'ai_reader') THEN
    RAISE EXCEPTION 'prisma-ai-views: role ai_reader must not be a member of other roles';
  END IF;
END $$;

COMMIT;
