-- GENERATED by hyde-db from schema.prisma. Do not edit by hand.
-- Recreates database redacted with column-filtered views and grants account redacted_reader@%
-- SELECT on exactly those views. Run AFTER `prisma migrate deploy`, connected to the source database.
-- MySQL commits DDL and grants as it runs, so this script cannot be rolled back: it checks first, grants last,
-- and revokes the reader and aborts if its final check fails.
SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_BACKSLASH_ESCAPES';
SET SESSION lock_wait_timeout = 60;
SET @hyde_refused = NULL;
SET @hyde_refused = IF(DATABASE() IS NULL, 'hyde-db: no default database; the connection must select the source database. Fix: add the database name to the connection URL', @hyde_refused);
SET SESSION sql_warnings = IF(@hyde_refused IS NULL, IF(@@SESSION.sql_warnings, 'ON', 'OFF'), @hyde_refused);
DROP TEMPORARY TABLE IF EXISTS `hyde_db_abort`;
CREATE TEMPORARY TABLE `hyde_db_abort` (`problem` INT NOT NULL);
SET @hyde_message = 'hyde-db: check default-database could not run. Fix: run without --force and read the first error';
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the default database is the views database.' AS problem, 'connect to the source database, not redacted' AS fix FROM DUAL WHERE LOWER(DATABASE()) = LOWER('redacted')) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_marker = NULL;
SET @hyde_source = NULL;
SET @hyde_sql = IF(EXISTS (SELECT 1 FROM information_schema.VIEWS WHERE TABLE_SCHEMA = 'redacted' AND TABLE_NAME = 'hyde_db_marker' AND SECURITY_TYPE = 'DEFINER') AND EXISTS (SELECT 1 FROM information_schema.COLUMNS c WHERE c.TABLE_SCHEMA = 'redacted' AND c.TABLE_NAME = 'hyde_db_marker' AND c.COLUMN_NAME = 'marker') AND EXISTS (SELECT 1 FROM information_schema.COLUMNS c WHERE c.TABLE_SCHEMA = 'redacted' AND c.TABLE_NAME = 'hyde_db_marker' AND c.COLUMN_NAME = 'source'), 'SELECT `marker`, `source` INTO @hyde_marker, @hyde_source FROM `redacted`.`hyde_db_marker`', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_message = 'hyde-db: check marker-guard could not run. Fix: run without --force and read the first error';
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT CONCAT('database ', 'redacted', ' has no hyde-db marker view.') AS problem,
       'drop or rename it, or set "schema" to an unused name' AS fix
FROM DUAL
WHERE EXISTS (SELECT 1 FROM information_schema.SCHEMATA WHERE SCHEMA_NAME = 'redacted')
  AND (@hyde_marker IS NULL OR @hyde_marker <> 'Generated by hyde-db' OR @hyde_source IS NULL) AND NOT (EXISTS (SELECT 1 FROM information_schema.VIEWS WHERE TABLE_SCHEMA = 'redacted' AND TABLE_NAME = 'hyde_db_marker' AND SECURITY_TYPE = 'DEFINER') AND EXISTS (SELECT 1 FROM information_schema.COLUMNS c WHERE c.TABLE_SCHEMA = 'redacted' AND c.TABLE_NAME = 'hyde_db_marker' AND c.COLUMN_NAME = 'marker') AND EXISTS (SELECT 1 FROM information_schema.COLUMNS c WHERE c.TABLE_SCHEMA = 'redacted' AND c.TABLE_NAME = 'hyde_db_marker' AND c.COLUMN_NAME = 'source') AND @hyde_marker IS NULL AND @hyde_source IS NULL)
UNION ALL
SELECT CONCAT('the marker view of ', 'redacted', ' cannot be read.'),
       IF(CHAR_LENGTH(CONCAT('re-create its definer ', (SELECT DEFINER FROM information_schema.VIEWS WHERE TABLE_SCHEMA = 'redacted' AND TABLE_NAME = 'hyde_db_marker' AND SECURITY_TYPE = 'DEFINER'), ' or drop database ', 'redacted')) > 113, 're-create the marker definer or drop the database', CONCAT('re-create its definer ', (SELECT DEFINER FROM information_schema.VIEWS WHERE TABLE_SCHEMA = 'redacted' AND TABLE_NAME = 'hyde_db_marker' AND SECURITY_TYPE = 'DEFINER'), ' or drop database ', 'redacted'))
FROM DUAL
WHERE (EXISTS (SELECT 1 FROM information_schema.VIEWS WHERE TABLE_SCHEMA = 'redacted' AND TABLE_NAME = 'hyde_db_marker' AND SECURITY_TYPE = 'DEFINER') AND EXISTS (SELECT 1 FROM information_schema.COLUMNS c WHERE c.TABLE_SCHEMA = 'redacted' AND c.TABLE_NAME = 'hyde_db_marker' AND c.COLUMN_NAME = 'marker') AND EXISTS (SELECT 1 FROM information_schema.COLUMNS c WHERE c.TABLE_SCHEMA = 'redacted' AND c.TABLE_NAME = 'hyde_db_marker' AND c.COLUMN_NAME = 'source') AND @hyde_marker IS NULL AND @hyde_source IS NULL)
UNION ALL
SELECT CONCAT('database ', 'redacted', ' belongs to source database ', @hyde_source, '.'),
       'set "schema" to an unused name'
FROM DUAL
WHERE NOT (@hyde_marker IS NULL OR @hyde_marker <> 'Generated by hyde-db' OR @hyde_source IS NULL) AND CONVERT(@hyde_source USING utf8mb4) COLLATE utf8mb4_bin <> CONVERT(DATABASE() USING utf8mb4) COLLATE utf8mb4_bin) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_message = 'hyde-db: check grant-table-access could not run. Fix: run without --force and read the first error';
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the deploying user cannot read the MySQL grant tables.' AS problem, IF(CHAR_LENGTH(CONCAT('GRANT SELECT ON mysql.* TO ', CONCAT(QUOTE(SUBSTRING_INDEX(CURRENT_USER(),'@',1)), '@', QUOTE(SUBSTRING_INDEX(CURRENT_USER(),'@',-1))), ';')) > 113, 'grant SELECT on mysql.* to the deploying user', CONCAT('GRANT SELECT ON mysql.* TO ', CONCAT(QUOTE(SUBSTRING_INDEX(CURRENT_USER(),'@',1)), '@', QUOTE(SUBSTRING_INDEX(CURRENT_USER(),'@',-1))), ';')) AS fix
FROM DUAL
WHERE (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'mysql' AND TABLE_NAME IN ('user', 'global_grants', 'db', 'tables_priv', 'columns_priv', 'procs_priv', 'proxies_priv', 'default_roles', 'role_edges')) < 9) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'redacted_reader'@'%' IGNORE UNKNOWN USER;
SET @hyde_message = 'hyde-db: check reset-reader could not run. Fix: run without --force and read the first error';
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the reader has a global privilege.' AS problem, IF(CHAR_LENGTH(CONCAT('REVOKE ', privs, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s global privileges', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ', privs, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) AS fix, 1 AS `rank`
  FROM (SELECT CONCAT_WS(', ', IF(Select_priv = 'Y', 'SELECT', NULL), IF(Insert_priv = 'Y', 'INSERT', NULL), IF(Update_priv = 'Y', 'UPDATE', NULL), IF(Delete_priv = 'Y', 'DELETE', NULL), IF(Create_priv = 'Y', 'CREATE', NULL), IF(Drop_priv = 'Y', 'DROP', NULL), IF(Reload_priv = 'Y', 'RELOAD', NULL), IF(Shutdown_priv = 'Y', 'SHUTDOWN', NULL), IF(Process_priv = 'Y', 'PROCESS', NULL), IF(File_priv = 'Y', 'FILE', NULL), IF(Grant_priv = 'Y', 'GRANT OPTION', NULL), IF(References_priv = 'Y', 'REFERENCES', NULL), IF(Index_priv = 'Y', 'INDEX', NULL), IF(Alter_priv = 'Y', 'ALTER', NULL), IF(Show_db_priv = 'Y', 'SHOW DATABASES', NULL), IF(Super_priv = 'Y', 'SUPER', NULL), IF(Create_tmp_table_priv = 'Y', 'CREATE TEMPORARY TABLES', NULL), IF(Lock_tables_priv = 'Y', 'LOCK TABLES', NULL), IF(Execute_priv = 'Y', 'EXECUTE', NULL), IF(Repl_slave_priv = 'Y', 'REPLICATION SLAVE', NULL), IF(Repl_client_priv = 'Y', 'REPLICATION CLIENT', NULL), IF(Create_view_priv = 'Y', 'CREATE VIEW', NULL), IF(Show_view_priv = 'Y', 'SHOW VIEW', NULL), IF(Create_routine_priv = 'Y', 'CREATE ROUTINE', NULL), IF(Alter_routine_priv = 'Y', 'ALTER ROUTINE', NULL), IF(Create_user_priv = 'Y', 'CREATE USER', NULL), IF(Event_priv = 'Y', 'EVENT', NULL), IF(Trigger_priv = 'Y', 'TRIGGER', NULL), IF(Create_tablespace_priv = 'Y', 'CREATE TABLESPACE', NULL), IF(Create_role_priv = 'Y', 'CREATE ROLE', NULL), IF(Drop_role_priv = 'Y', 'DROP ROLE', NULL)) AS privs
          FROM mysql.user WHERE User = 'redacted_reader' AND Host = '%') g WHERE privs <> ''
UNION ALL
SELECT 'the reader has a dynamic global privilege.', IF(CHAR_LENGTH(CONCAT('REVOKE ', PRIV, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s dynamic privileges', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ', PRIV, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 2
  FROM mysql.global_grants WHERE USER = 'redacted_reader' AND HOST = '%'
UNION ALL
SELECT 'the reader has a grant on a database.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s database grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 3
  FROM mysql.db WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has an unexpected table grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s table grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 4
  FROM mysql.tables_priv WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has a column grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ', REPLACE(Column_priv, ',', CONCAT(' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), '), ')), ' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), ') ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s column grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ', REPLACE(Column_priv, ',', CONCAT(' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), '), ')), ' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), ') ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 5
  FROM mysql.columns_priv WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has a routine grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', Routine_type, ' ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Routine_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s routine grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', Routine_type, ' ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Routine_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 6
  FROM mysql.procs_priv WHERE User = 'redacted_reader' AND Host = '%'
ORDER BY `rank` LIMIT 1) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_message = 'hyde-db: check roles could not run. Fix: run without --force and read the first error';
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the reader has a role.' AS problem, IF(CHAR_LENGTH(CONCAT('REVOKE ', CONCAT(QUOTE(FROM_USER), '@', QUOTE(FROM_HOST)), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the roles granted to the reader', CONCAT('REVOKE ', CONCAT(QUOTE(FROM_USER), '@', QUOTE(FROM_HOST)), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) AS fix, 7 AS `rank`
  FROM mysql.role_edges WHERE TO_USER = 'redacted_reader' AND TO_HOST = '%'
UNION ALL
SELECT 'the reader has a default role.', IF(CHAR_LENGTH(CONCAT('ALTER USER ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ' DEFAULT ROLE NONE;')) > 113, 'set the reader''s default role to NONE', CONCAT('ALTER USER ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ' DEFAULT ROLE NONE;')), 8
  FROM mysql.default_roles WHERE USER = 'redacted_reader' AND HOST = '%'
ORDER BY `rank` LIMIT 1) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_message = 'hyde-db: check mandatory-roles could not run. Fix: run without --force and read the first error';
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'mandatory_roles is set; that is unsupported.' AS problem, 'SET PERSIST mandatory_roles = '''';' AS fix, 9 AS `rank`
  FROM DUAL WHERE @@GLOBAL.mandatory_roles <> ''
ORDER BY `rank` LIMIT 1) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_message = 'hyde-db: check proxies could not run. Fix: run without --force and read the first error';
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the reader takes part in a proxy grant.' AS problem, IF(CHAR_LENGTH(CONCAT('REVOKE PROXY ON ', CONCAT(QUOTE(Proxied_user), '@', QUOTE(Proxied_host)), ' FROM ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) > 113, 'revoke the proxy grants of the reader', CONCAT('REVOKE PROXY ON ', CONCAT(QUOTE(Proxied_user), '@', QUOTE(Proxied_host)), ' FROM ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) AS fix, 10 AS `rank`
  FROM mysql.proxies_priv WHERE (User = 'redacted_reader' AND Host = '%') OR (Proxied_user = 'redacted_reader' AND Proxied_host = '%')
ORDER BY `rank` LIMIT 1) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_message = 'hyde-db: check other-accounts could not run. Fix: run without --force and read the first error';
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'another account could match a reader login.' AS problem, IF(CHAR_LENGTH(CONCAT('DROP USER ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) > 113, 'drop the other accounts of that user name', CONCAT('DROP USER ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) AS fix, 11 AS `rank`
  FROM mysql.user WHERE (User = 'redacted_reader' OR User = '') AND NOT (User = 'redacted_reader' AND Host = '%')
ORDER BY `rank` LIMIT 1) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'DROP DATABASE IF EXISTS `redacted`;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'CREATE DATABASE `redacted`;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, CONCAT('CREATE DEFINER = CURRENT_USER SQL SECURITY DEFINER VIEW `redacted`.`hyde_db_marker` AS SELECT ''Generated by hyde-db'' AS `marker`, ', CONCAT('''', REPLACE(DATABASE(), '''', ''''''), ''''), ' AS `source`;'), 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'CREATE DEFINER = CURRENT_USER SQL SECURITY DEFINER VIEW `redacted`.`users` (`id`, `created_at`, `country`, `plan`) AS SELECT `id`, `created_at`, `country`, `plan` FROM `users`;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'CREATE DEFINER = CURRENT_USER SQL SECURITY DEFINER VIEW `redacted`.`orders` (`id`, `user_id`, `total_cents`, `placed_at`) AS SELECT `id`, `user_id`, `total_cents`, `placed_at` FROM `orders`;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'CREATE USER IF NOT EXISTS ''redacted_reader''@''%'' ACCOUNT LOCK;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'GRANT SELECT ON `redacted`.`users` TO ''redacted_reader''@''%'';', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'GRANT SELECT ON `redacted`.`orders` TO ''redacted_reader''@''%'';', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_message = 'hyde-db: check recheck could not run. Fix: run without --force and read the first error';
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the reader has a global privilege.' AS problem, IF(CHAR_LENGTH(CONCAT('REVOKE ', privs, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s global privileges', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ', privs, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) AS fix, 1 AS `rank`
  FROM (SELECT CONCAT_WS(', ', IF(Select_priv = 'Y', 'SELECT', NULL), IF(Insert_priv = 'Y', 'INSERT', NULL), IF(Update_priv = 'Y', 'UPDATE', NULL), IF(Delete_priv = 'Y', 'DELETE', NULL), IF(Create_priv = 'Y', 'CREATE', NULL), IF(Drop_priv = 'Y', 'DROP', NULL), IF(Reload_priv = 'Y', 'RELOAD', NULL), IF(Shutdown_priv = 'Y', 'SHUTDOWN', NULL), IF(Process_priv = 'Y', 'PROCESS', NULL), IF(File_priv = 'Y', 'FILE', NULL), IF(Grant_priv = 'Y', 'GRANT OPTION', NULL), IF(References_priv = 'Y', 'REFERENCES', NULL), IF(Index_priv = 'Y', 'INDEX', NULL), IF(Alter_priv = 'Y', 'ALTER', NULL), IF(Show_db_priv = 'Y', 'SHOW DATABASES', NULL), IF(Super_priv = 'Y', 'SUPER', NULL), IF(Create_tmp_table_priv = 'Y', 'CREATE TEMPORARY TABLES', NULL), IF(Lock_tables_priv = 'Y', 'LOCK TABLES', NULL), IF(Execute_priv = 'Y', 'EXECUTE', NULL), IF(Repl_slave_priv = 'Y', 'REPLICATION SLAVE', NULL), IF(Repl_client_priv = 'Y', 'REPLICATION CLIENT', NULL), IF(Create_view_priv = 'Y', 'CREATE VIEW', NULL), IF(Show_view_priv = 'Y', 'SHOW VIEW', NULL), IF(Create_routine_priv = 'Y', 'CREATE ROUTINE', NULL), IF(Alter_routine_priv = 'Y', 'ALTER ROUTINE', NULL), IF(Create_user_priv = 'Y', 'CREATE USER', NULL), IF(Event_priv = 'Y', 'EVENT', NULL), IF(Trigger_priv = 'Y', 'TRIGGER', NULL), IF(Create_tablespace_priv = 'Y', 'CREATE TABLESPACE', NULL), IF(Create_role_priv = 'Y', 'CREATE ROLE', NULL), IF(Drop_role_priv = 'Y', 'DROP ROLE', NULL)) AS privs
          FROM mysql.user WHERE User = 'redacted_reader' AND Host = '%') g WHERE privs <> ''
UNION ALL
SELECT 'the reader has a dynamic global privilege.', IF(CHAR_LENGTH(CONCAT('REVOKE ', PRIV, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s dynamic privileges', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ', PRIV, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 2
  FROM mysql.global_grants WHERE USER = 'redacted_reader' AND HOST = '%'
UNION ALL
SELECT 'the reader has a grant on a database.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s database grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 3
  FROM mysql.db WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has an unexpected table grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s table grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 4
  FROM mysql.tables_priv WHERE User = 'redacted_reader' AND Host = '%'
    AND NOT (Db = 'redacted' AND Table_priv = 'Select' AND (Table_name IN ('users', 'orders') OR (@@lower_case_table_names <> 0 AND LOWER(Table_name) IN ('users', 'orders'))))
UNION ALL
SELECT 'the reader has a column grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ', REPLACE(Column_priv, ',', CONCAT(' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), '), ')), ' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), ') ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s column grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ', REPLACE(Column_priv, ',', CONCAT(' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), '), ')), ' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), ') ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 5
  FROM mysql.columns_priv WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has a routine grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', Routine_type, ' ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Routine_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s routine grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', Routine_type, ' ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Routine_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 6
  FROM mysql.procs_priv WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has a role.' AS problem, IF(CHAR_LENGTH(CONCAT('REVOKE ', CONCAT(QUOTE(FROM_USER), '@', QUOTE(FROM_HOST)), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the roles granted to the reader', CONCAT('REVOKE ', CONCAT(QUOTE(FROM_USER), '@', QUOTE(FROM_HOST)), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) AS fix, 7 AS `rank`
  FROM mysql.role_edges WHERE TO_USER = 'redacted_reader' AND TO_HOST = '%'
UNION ALL
SELECT 'the reader has a default role.', IF(CHAR_LENGTH(CONCAT('ALTER USER ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ' DEFAULT ROLE NONE;')) > 113, 'set the reader''s default role to NONE', CONCAT('ALTER USER ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ' DEFAULT ROLE NONE;')), 8
  FROM mysql.default_roles WHERE USER = 'redacted_reader' AND HOST = '%'
UNION ALL
SELECT 'mandatory_roles is set; that is unsupported.' AS problem, 'SET PERSIST mandatory_roles = '''';' AS fix, 9 AS `rank`
  FROM DUAL WHERE @@GLOBAL.mandatory_roles <> ''
UNION ALL
SELECT 'the reader takes part in a proxy grant.' AS problem, IF(CHAR_LENGTH(CONCAT('REVOKE PROXY ON ', CONCAT(QUOTE(Proxied_user), '@', QUOTE(Proxied_host)), ' FROM ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) > 113, 'revoke the proxy grants of the reader', CONCAT('REVOKE PROXY ON ', CONCAT(QUOTE(Proxied_user), '@', QUOTE(Proxied_host)), ' FROM ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) AS fix, 10 AS `rank`
  FROM mysql.proxies_priv WHERE (User = 'redacted_reader' AND Host = '%') OR (Proxied_user = 'redacted_reader' AND Proxied_host = '%')
UNION ALL
SELECT 'another account could match a reader login.' AS problem, IF(CHAR_LENGTH(CONCAT('DROP USER ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) > 113, 'drop the other accounts of that user name', CONCAT('DROP USER ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) AS fix, 11 AS `rank`
  FROM mysql.user WHERE (User = 'redacted_reader' OR User = '') AND NOT (User = 'redacted_reader' AND Host = '%')
ORDER BY `rank` LIMIT 1) f LIMIT 1);
SET @hyde_sql = IF(@hyde_message IS NULL, 'DO 0', 'REVOKE ALL PRIVILEGES, GRANT OPTION FROM ''redacted_reader''@''%'' IGNORE UNKNOWN USER');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
DROP TEMPORARY TABLE IF EXISTS `hyde_db_abort`;
