-- GENERATED by hyde-db from schema.prisma. Do not edit by hand.
-- Recreates database redacted with column-filtered views and grants account redacted_reader@%
-- SELECT on exactly those views. Run AFTER `prisma migrate deploy`, connected to the source database.
-- MySQL commits DDL and grants as it runs, so this script cannot be rolled back: it checks first, grants last,
-- and revokes the reader and aborts if its final check fails.
SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_BACKSLASH_ESCAPES';
SET SESSION lock_wait_timeout = 60;
SET @hyde_refused = NULL;
SET @hyde_refused = IF(DATABASE() IS NULL, 'hyde-db: no default database; the connection must select the source database. Fix: add the database name to the connection URL', @hyde_refused);
SET SESSION sql_warnings = IF(@hyde_refused IS NULL, IF(@@SESSION.sql_warnings, 'ON', 'OFF'), @hyde_refused);
DROP TEMPORARY TABLE IF EXISTS `hyde_db_abort`;
CREATE TEMPORARY TABLE `hyde_db_abort` (`problem` INT NOT NULL);
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the default database is the views database.' AS problem, 'connect to the source database, not redacted' AS fix FROM DUAL WHERE LOWER(DATABASE()) = LOWER('redacted')) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT CONCAT('database ', 'redacted', ' has no hyde-db marker view.') AS problem,
       'drop or rename it, or set "schema" to an unused name' AS fix
FROM DUAL
WHERE EXISTS (SELECT 1 FROM information_schema.SCHEMATA WHERE SCHEMA_NAME = 'redacted')
  AND NOT EXISTS (SELECT 1 FROM information_schema.VIEWS v JOIN information_schema.COLUMNS c
        ON c.TABLE_SCHEMA = v.TABLE_SCHEMA AND c.TABLE_NAME = v.TABLE_NAME
        WHERE v.TABLE_SCHEMA = 'redacted' AND v.TABLE_NAME = 'hyde_db_marker' AND c.COLUMN_NAME = 'marker'
          AND v.VIEW_DEFINITION LIKE '%Generated by hyde-db%')) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the deploying user cannot read the MySQL grant tables.' AS problem, IF(CHAR_LENGTH(CONCAT('GRANT SELECT ON mysql.* TO ', CONCAT(QUOTE(SUBSTRING_INDEX(CURRENT_USER(),'@',1)), '@', QUOTE(SUBSTRING_INDEX(CURRENT_USER(),'@',-1))), ';')) > 113, 'grant SELECT on mysql.* to the deploying user', CONCAT('GRANT SELECT ON mysql.* TO ', CONCAT(QUOTE(SUBSTRING_INDEX(CURRENT_USER(),'@',1)), '@', QUOTE(SUBSTRING_INDEX(CURRENT_USER(),'@',-1))), ';')) AS fix
FROM DUAL
WHERE (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'mysql' AND TABLE_NAME IN ('user', 'global_grants', 'db', 'tables_priv', 'columns_priv', 'procs_priv', 'proxies_priv', 'default_roles', 'role_edges')) < 9) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'redacted_reader'@'%' IGNORE UNKNOWN USER;
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the reader has a global privilege.' AS problem, IF(CHAR_LENGTH(CONCAT(IF(PRIVILEGE_TYPE = 'USAGE', 'REVOKE GRANT OPTION', CONCAT('REVOKE ', PRIVILEGE_TYPE)), ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s global privileges', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT(IF(PRIVILEGE_TYPE = 'USAGE', 'REVOKE GRANT OPTION', CONCAT('REVOKE ', PRIVILEGE_TYPE)), ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) AS fix, 1 AS `rank`
  FROM information_schema.USER_PRIVILEGES WHERE GRANTEE = '''redacted_reader''@''%''' AND (PRIVILEGE_TYPE <> 'USAGE' OR IS_GRANTABLE = 'YES')
UNION ALL
SELECT 'the reader has a dynamic global privilege.', IF(CHAR_LENGTH(CONCAT('REVOKE ', PRIV, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s dynamic privileges', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ', PRIV, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 2
  FROM mysql.global_grants WHERE USER = 'redacted_reader' AND HOST = '%'
UNION ALL
SELECT 'the reader has a grant on a database.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s database grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 3
  FROM mysql.db WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has an unexpected table grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s table grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 4
  FROM mysql.tables_priv WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has a column grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ', REPLACE(Column_priv, ',', CONCAT(' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), '), ')), ' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), ') ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s column grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ', REPLACE(Column_priv, ',', CONCAT(' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), '), ')), ' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), ') ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 5
  FROM mysql.columns_priv WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has a routine grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', Routine_type, ' ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Routine_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s routine grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', Routine_type, ' ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Routine_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 6
  FROM mysql.procs_priv WHERE User = 'redacted_reader' AND Host = '%'
ORDER BY `rank` LIMIT 1) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the reader has a role.' AS problem, IF(CHAR_LENGTH(CONCAT('REVOKE ', CONCAT(QUOTE(FROM_USER), '@', QUOTE(FROM_HOST)), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the roles granted to the reader', CONCAT('REVOKE ', CONCAT(QUOTE(FROM_USER), '@', QUOTE(FROM_HOST)), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) AS fix, 7 AS `rank`
  FROM mysql.role_edges WHERE TO_USER = 'redacted_reader' AND TO_HOST = '%'
UNION ALL
SELECT 'the reader has a default role.', IF(CHAR_LENGTH(CONCAT('ALTER USER ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ' DEFAULT ROLE NONE;')) > 113, 'set the reader''s default role to NONE', CONCAT('ALTER USER ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ' DEFAULT ROLE NONE;')), 8
  FROM mysql.default_roles WHERE USER = 'redacted_reader' AND HOST = '%'
ORDER BY `rank` LIMIT 1) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'mandatory_roles is set; that is unsupported.' AS problem, 'SET PERSIST mandatory_roles = '''';' AS fix, 9 AS `rank`
  FROM DUAL WHERE @@GLOBAL.mandatory_roles <> ''
ORDER BY `rank` LIMIT 1) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the reader takes part in a proxy grant.' AS problem, IF(CHAR_LENGTH(CONCAT('REVOKE PROXY ON ', CONCAT(QUOTE(Proxied_user), '@', QUOTE(Proxied_host)), ' FROM ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) > 113, 'revoke the proxy grants of the reader', CONCAT('REVOKE PROXY ON ', CONCAT(QUOTE(Proxied_user), '@', QUOTE(Proxied_host)), ' FROM ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) AS fix, 10 AS `rank`
  FROM mysql.proxies_priv WHERE (User = 'redacted_reader' AND Host = '%') OR (Proxied_user = 'redacted_reader' AND Proxied_host = '%')
ORDER BY `rank` LIMIT 1) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'another account could match a reader login.' AS problem, IF(CHAR_LENGTH(CONCAT('DROP USER ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) > 113, 'drop the other accounts of that user name', CONCAT('DROP USER ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) AS fix, 11 AS `rank`
  FROM mysql.user WHERE (User = 'redacted_reader' OR User = '') AND NOT (User = 'redacted_reader' AND Host = '%')
ORDER BY `rank` LIMIT 1) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'DROP DATABASE IF EXISTS `redacted`;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'CREATE DATABASE `redacted`;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'CREATE DEFINER = CURRENT_USER SQL SECURITY DEFINER VIEW `redacted`.`hyde_db_marker` AS SELECT ''Generated by hyde-db'' AS `marker`;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'CREATE DEFINER = CURRENT_USER SQL SECURITY DEFINER VIEW `redacted`.`users` (`id`, `created_at`, `country`, `plan`) AS SELECT `id`, `created_at`, `country`, `plan` FROM `users`;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'CREATE DEFINER = CURRENT_USER SQL SECURITY DEFINER VIEW `redacted`.`orders` (`id`, `user_id`, `total_cents`, `placed_at`) AS SELECT `id`, `user_id`, `total_cents`, `placed_at` FROM `orders`;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'CREATE USER IF NOT EXISTS ''redacted_reader''@''%'' ACCOUNT LOCK;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'GRANT SELECT ON `redacted`.`users` TO ''redacted_reader''@''%'';', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'GRANT SELECT ON `redacted`.`orders` TO ''redacted_reader''@''%'';', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT 'the reader has a global privilege.' AS problem, IF(CHAR_LENGTH(CONCAT(IF(PRIVILEGE_TYPE = 'USAGE', 'REVOKE GRANT OPTION', CONCAT('REVOKE ', PRIVILEGE_TYPE)), ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s global privileges', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT(IF(PRIVILEGE_TYPE = 'USAGE', 'REVOKE GRANT OPTION', CONCAT('REVOKE ', PRIVILEGE_TYPE)), ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) AS fix, 1 AS `rank`
  FROM information_schema.USER_PRIVILEGES WHERE GRANTEE = '''redacted_reader''@''%''' AND (PRIVILEGE_TYPE <> 'USAGE' OR IS_GRANTABLE = 'YES')
UNION ALL
SELECT 'the reader has a dynamic global privilege.', IF(CHAR_LENGTH(CONCAT('REVOKE ', PRIV, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s dynamic privileges', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ', PRIV, ' ON *.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 2
  FROM mysql.global_grants WHERE USER = 'redacted_reader' AND HOST = '%'
UNION ALL
SELECT 'the reader has a grant on a database.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s database grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.* FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 3
  FROM mysql.db WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has an unexpected table grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s table grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 4
  FROM mysql.tables_priv WHERE User = 'redacted_reader' AND Host = '%'
    AND NOT (LOWER(Db) = LOWER('redacted') AND Table_priv = 'Select' AND LOWER(Table_name) IN ('users', 'orders'))
UNION ALL
SELECT 'the reader has a column grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ', REPLACE(Column_priv, ',', CONCAT(' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), '), ')), ' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), ') ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s column grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ', REPLACE(Column_priv, ',', CONCAT(' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), '), ')), ' (', CONCAT('`', REPLACE(Column_name, '`', '``'), '`'), ') ON ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Table_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 5
  FROM mysql.columns_priv WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has a routine grant.', IF(CHAR_LENGTH(CONCAT('REVOKE ALL ON ', Routine_type, ' ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Routine_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, IF(CHAR_LENGTH(CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the reader''s routine grants', CONCAT('REVOKE ALL PRIVILEGES, GRANT OPTION FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), CONCAT('REVOKE ALL ON ', Routine_type, ' ', CONCAT('`', REPLACE(Db, '`', '``'), '`'), '.', CONCAT('`', REPLACE(Routine_name, '`', '``'), '`'), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')), 6
  FROM mysql.procs_priv WHERE User = 'redacted_reader' AND Host = '%'
UNION ALL
SELECT 'the reader has a role.' AS problem, IF(CHAR_LENGTH(CONCAT('REVOKE ', CONCAT(QUOTE(FROM_USER), '@', QUOTE(FROM_HOST)), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) > 113, 'revoke the roles granted to the reader', CONCAT('REVOKE ', CONCAT(QUOTE(FROM_USER), '@', QUOTE(FROM_HOST)), ' FROM ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ';')) AS fix, 7 AS `rank`
  FROM mysql.role_edges WHERE TO_USER = 'redacted_reader' AND TO_HOST = '%'
UNION ALL
SELECT 'the reader has a default role.', IF(CHAR_LENGTH(CONCAT('ALTER USER ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ' DEFAULT ROLE NONE;')) > 113, 'set the reader''s default role to NONE', CONCAT('ALTER USER ', CONCAT(QUOTE('redacted_reader'), '@', QUOTE('%')), ' DEFAULT ROLE NONE;')), 8
  FROM mysql.default_roles WHERE USER = 'redacted_reader' AND HOST = '%'
UNION ALL
SELECT 'mandatory_roles is set; that is unsupported.' AS problem, 'SET PERSIST mandatory_roles = '''';' AS fix, 9 AS `rank`
  FROM DUAL WHERE @@GLOBAL.mandatory_roles <> ''
UNION ALL
SELECT 'the reader takes part in a proxy grant.' AS problem, IF(CHAR_LENGTH(CONCAT('REVOKE PROXY ON ', CONCAT(QUOTE(Proxied_user), '@', QUOTE(Proxied_host)), ' FROM ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) > 113, 'revoke the proxy grants of the reader', CONCAT('REVOKE PROXY ON ', CONCAT(QUOTE(Proxied_user), '@', QUOTE(Proxied_host)), ' FROM ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) AS fix, 10 AS `rank`
  FROM mysql.proxies_priv WHERE (User = 'redacted_reader' AND Host = '%') OR (Proxied_user = 'redacted_reader' AND Proxied_host = '%')
UNION ALL
SELECT 'another account could match a reader login.' AS problem, IF(CHAR_LENGTH(CONCAT('DROP USER ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) > 113, 'drop the other accounts of that user name', CONCAT('DROP USER ', CONCAT(QUOTE(User), '@', QUOTE(Host)), ';')) AS fix, 11 AS `rank`
  FROM mysql.user WHERE (User = 'redacted_reader' OR User = '') AND NOT (User = 'redacted_reader' AND Host = '%')
ORDER BY `rank` LIMIT 1) f);
SET @hyde_sql = IF(@hyde_message IS NULL, 'DO 0', 'REVOKE ALL PRIVILEGES, GRANT OPTION FROM ''redacted_reader''@''%'' IGNORE UNKNOWN USER');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
DROP TEMPORARY TABLE IF EXISTS `hyde_db_abort`;
