-- GENERATED by hyde-db. Run BEFORE `prisma migrate deploy` so that
-- migrations can drop/alter columns that the redacted views depend on.
SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_BACKSLASH_ESCAPES';
SET SESSION lock_wait_timeout = 60;
SET @hyde_refused = NULL;
SET @hyde_refused = IF(DATABASE() IS NULL, 'hyde-db: no default database; the connection must select the source database. Fix: add the database name to the connection URL', @hyde_refused);
SET SESSION sql_warnings = IF(@hyde_refused IS NULL, IF(@@SESSION.sql_warnings, 'ON', 'OFF'), @hyde_refused);
DROP TEMPORARY TABLE IF EXISTS `hyde_db_abort`;
CREATE TEMPORARY TABLE `hyde_db_abort` (`problem` INT NOT NULL);
SET @hyde_marker = NULL;
SET @hyde_source = NULL;
SET @hyde_sql = IF(EXISTS (SELECT 1 FROM information_schema.VIEWS WHERE TABLE_SCHEMA = 'redacted' AND TABLE_NAME = 'hyde_db_marker') AND EXISTS (SELECT 1 FROM information_schema.COLUMNS c WHERE c.TABLE_SCHEMA = 'redacted' AND c.TABLE_NAME = 'hyde_db_marker' AND c.COLUMN_NAME = 'marker') AND EXISTS (SELECT 1 FROM information_schema.COLUMNS c WHERE c.TABLE_SCHEMA = 'redacted' AND c.TABLE_NAME = 'hyde_db_marker' AND c.COLUMN_NAME = 'source'), 'SELECT `marker`, `source` INTO @hyde_marker, @hyde_source FROM `redacted`.`hyde_db_marker`', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
SET @hyde_message = 'hyde-db: check marker-guard could not run. Fix: run without --force and read the first error';
SET @hyde_message = (SELECT CONCAT('hyde-db: ', LEFT(f.problem, GREATEST(0, 113 - CHAR_LENGTH(f.fix))), ' Fix: ', f.fix) FROM (SELECT CONCAT('database ', 'redacted', ' has no hyde-db marker view.') AS problem,
       'drop or rename it, or set "schema" to an unused name' AS fix
FROM DUAL
WHERE EXISTS (SELECT 1 FROM information_schema.SCHEMATA WHERE SCHEMA_NAME = 'redacted')
  AND (@hyde_marker IS NULL OR @hyde_marker <> 'Generated by hyde-db' OR @hyde_source IS NULL)
UNION ALL
SELECT CONCAT('database ', 'redacted', ' belongs to source database ', @hyde_source, '.'),
       'set "schema" to an unused name'
FROM DUAL
WHERE NOT (@hyde_marker IS NULL OR @hyde_marker <> 'Generated by hyde-db' OR @hyde_source IS NULL) AND BINARY @hyde_source <> BINARY DATABASE()) f LIMIT 1);
SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);
INSERT INTO `hyde_db_abort` (`problem`) SELECT @hyde_message FROM DUAL WHERE @hyde_message IS NOT NULL;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'redacted_reader'@'%' IGNORE UNKNOWN USER;
SET @hyde_sql = IF(@hyde_refused IS NULL, 'DROP DATABASE IF EXISTS `redacted`;', 'DO 0');
PREPARE hyde_stmt FROM @hyde_sql;
EXECUTE hyde_stmt;
DEALLOCATE PREPARE hyde_stmt;
DROP TEMPORARY TABLE IF EXISTS `hyde_db_abort`;
