// Renders ai-views.sql: one transaction that recreates the AI schema with column-filtered
// views, grants the AI role SELECT on exactly those views, and aborts if the role could
// reach anything else (D11, D13, D24).
import { BRAND, SCHEMA_MARKER } from '../brand.ts'
import { quoteIdent as qi, quoteLiteral as ql } from '../sql.ts'
import type { ResolvedConfig, View } from '../types.ts'
import { renderSchemaGuard } from './schema-guard.ts'

export interface RenderInput {
  readonly config: ResolvedConfig
  readonly views: readonly View[]
}

/**
 * SQL listing who must lose a privilege: PUBLIC when it holds it, and the AI role when it owns
 * the object (an owner holds its privileges with no ACL entry) or holds it directly. The role may
 * not exist yet when the fix is run (a failed first apply rolls back its creation), so it is only
 * named when it owns the object or has a direct grant.
 */
function grantees(
  publicHolds: string,
  owner: string,
  acl: string,
  privileges: readonly string[],
): string {
  const list = privileges.map((p) => `'${p}'`).join(', ')
  return (
    `concat_ws(', ', CASE WHEN ${publicHolds} THEN 'PUBLIC' END, ` +
    `CASE WHEN r.oid = ${owner} OR EXISTS (SELECT 1 FROM aclexplode(${acl}) a WHERE a.grantee = r.oid AND a.privilege_type IN (${list})) ` +
    'THEN quote_ident(r.rolname) END)'
  )
}

/** The final safety check: every way the role could reach data outside the views aborts the script. */
function renderFinalCheck(config: ResolvedConfig): string[] {
  const role = ql(config.role)
  const routine =
    "format('%I.%I(%s)', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid))"
  const sequence = "format('%I.%I', n.nspname, c.relname)"
  return [
    '-- Safety check: abort if the role can read any relation outside the AI schema',
    '-- (e.g. via PUBLIC grants or membership in another role), execute a SECURITY DEFINER',
    '-- function, or read a sequence.',
    'DO $$',
    'DECLARE',
    '  leaks text;',
    '  fixes text;',
    'BEGIN',
    `  SELECT string_agg(format('%I.%I', n.nspname, c.relname), ', ' ORDER BY 1) INTO leaks`,
    '  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace',
    `  WHERE c.relkind IN ('r', 'p', 'v', 'm', 'f')`,
    `    AND n.nspname NOT IN (${ql(config.schema)}, 'pg_catalog', 'information_schema')`,
    `    AND n.nspname NOT LIKE 'pg\\_%'`,
    `    AND (has_table_privilege(${role}, c.oid, 'SELECT')`,
    `         OR has_any_column_privilege(${role}, c.oid, 'SELECT'));`,
    '  IF leaks IS NOT NULL THEN',
    `    RAISE EXCEPTION '${BRAND}: role ${config.role} can read relations outside schema ${config.schema}: %', leaks;`,
    '  END IF;',
    '  IF EXISTS (SELECT 1 FROM pg_auth_members m JOIN pg_roles r ON r.oid = m.member',
    `             WHERE r.rolname = ${role}) THEN`,
    `    RAISE EXCEPTION '${BRAND}: role ${config.role} must not be a member of other roles';`,
    '  END IF;',
    '  -- The joins on pg_roles below always find the role: this transaction created it above if missing.',
    `  SELECT string_agg(${routine}, ', ' ORDER BY n.nspname, p.proname),`,
    `         string_agg(format('REVOKE EXECUTE ON ROUTINE %s FROM %s;', ${routine}, ${grantees("has_function_privilege('public', p.oid, 'EXECUTE')", 'p.proowner', 'p.proacl', ['EXECUTE'])}), ' ' ORDER BY n.nspname, p.proname)`,
    '    INTO leaks, fixes',
    '  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace CROSS JOIN pg_roles r',
    `  WHERE r.rolname = ${role}`,
    '    AND p.prosecdef',
    `    AND n.nspname NOT IN ('pg_catalog', 'information_schema')`,
    `    AND n.nspname NOT LIKE 'pg\\_%'`,
    "    AND has_schema_privilege(r.oid, n.oid, 'USAGE')",
    "    AND has_function_privilege(r.oid, p.oid, 'EXECUTE');",
    '  IF leaks IS NOT NULL THEN',
    `    RAISE EXCEPTION '${BRAND}: role ${config.role} can execute SECURITY DEFINER functions: %. Fix: %', leaks, fixes;`,
    '  END IF;',
    `  SELECT string_agg(${sequence}, ', ' ORDER BY n.nspname, c.relname),`,
    `         string_agg(format('REVOKE ALL ON SEQUENCE %s FROM %s;', ${sequence}, ${grantees("has_sequence_privilege('public', c.oid, 'SELECT, USAGE, UPDATE')", 'c.relowner', 'c.relacl', ['SELECT', 'USAGE', 'UPDATE'])}), ' ' ORDER BY n.nspname, c.relname)`,
    '    INTO leaks, fixes',
    '  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace CROSS JOIN pg_roles r',
    `  WHERE r.rolname = ${role}`,
    `    AND c.relkind = 'S'`,
    "    AND CASE WHEN c.relkind = 'S' THEN has_sequence_privilege(r.oid, c.oid, 'SELECT, USAGE, UPDATE') ELSE false END;",
    '  IF leaks IS NOT NULL THEN',
    `    RAISE EXCEPTION '${BRAND}: role ${config.role} can read sequences: %. Fix: %', leaks, fixes;`,
    '  END IF;',
    'END $$;',
  ]
}

export function renderApplySql({ config, views }: RenderInput): string {
  const S = qi(config.schema)
  const R = qi(config.role)
  const out: string[] = []
  out.push(
    `-- GENERATED by ${BRAND} from schema.prisma. Do not edit by hand.`,
    `-- Recreates schema ${config.schema} with column-filtered views and grants role ${config.role}`,
    '-- read access to exactly those views. Run AFTER `prisma migrate deploy`.',
    '-- The whole script is one transaction; the final check aborts it if the role',
    '-- could read anything outside the views.',
    '',
    'SET client_min_messages = warning;',
    'BEGIN;',
    '',
    'DO $$ BEGIN',
    `  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = ${ql(config.role)}) THEN`,
    `    CREATE ROLE ${R} NOLOGIN;`,
    '  END IF;',
    'END $$;',
    '',
    renderSchemaGuard(config),
    '',
    `DROP SCHEMA IF EXISTS ${S} CASCADE;`,
    `CREATE SCHEMA ${S};`,
    `COMMENT ON SCHEMA ${S} IS ${ql(`${SCHEMA_MARKER}. Read-only, PII-filtered views for AI/LLM access. Recreated on every deploy.`)};`,
    '',
  )

  for (const view of views) {
    const cols = view.columns.map((c) => `  ${qi(c.column)}`).join(',\n')
    // Views run with the owner's privileges (no security_invoker), so the AI
    // role needs no rights on the underlying tables at all.
    out.push(
      `CREATE VIEW ${S}.${qi(view.name)} AS SELECT\n${cols}\nFROM ${qi(view.sourceSchema)}.${qi(view.source)};`,
    )
    if (view.doc) out.push(`COMMENT ON VIEW ${S}.${qi(view.name)} IS ${ql(view.doc)};`)
    for (const c of view.columns) {
      if (c.doc)
        out.push(`COMMENT ON COLUMN ${S}.${qi(view.name)}.${qi(c.column)} IS ${ql(c.doc)};`)
    }
    out.push('')
  }

  out.push(
    `-- Privileges: nothing but SELECT on the views in ${config.schema}.`,
    `REVOKE ALL ON SCHEMA ${qi(config.sourceSchema)} FROM ${R};`,
    `REVOKE ALL ON ALL TABLES IN SCHEMA ${qi(config.sourceSchema)} FROM ${R};`,
    `GRANT USAGE ON SCHEMA ${S} TO ${R};`,
    `GRANT SELECT ON ALL TABLES IN SCHEMA ${S} TO ${R};`,
    '',
    '-- Defence in depth for the session itself.',
    `ALTER ROLE ${R} SET default_transaction_read_only = on;`,
    `ALTER ROLE ${R} SET statement_timeout = ${ql(config.statementTimeout)};`,
    `ALTER ROLE ${R} SET search_path = ${S};`,
    `ALTER ROLE ${R} NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;`,
    '',
    ...renderFinalCheck(config),
    '',
    'COMMIT;',
    '',
  )
  return out.join('\n')
}
