// Renders ai-views-drop.sql: drops the AI schema before migrations, but only when it
// carries the marker comment (D11).
import { BRAND } from '../brand.ts'
import { quoteIdent } from '../sql.ts'
import type { ResolvedConfig } from '../types.ts'
import { renderSchemaGuard } from './schema-guard.ts'

export function renderDropSql({ config }: { readonly config: ResolvedConfig }): string {
  return [
    `-- GENERATED by ${BRAND}. Run BEFORE \`prisma migrate deploy\` so that`,
    '-- migrations can drop/alter columns that the AI views depend on.',
    'SET client_min_messages = warning;',
    renderSchemaGuard(config),
    `DROP SCHEMA IF EXISTS ${quoteIdent(config.schema)} CASCADE;`,
    '',
  ].join('\n')
}
