// Renders redacted-views-drop.sql: drops the views schema before migrations, but only when it
// carries the marker comment (D11) and nothing outside it depends on its views (D141). Guards and
// drop share one transaction, so a refused drop changes nothing even under a client that runs
// past errors (D58).
import { BRAND } from '../brand.ts'
import { quoteIdent } from '../sql.ts'
import type { PostgresqlConfig } from '../types.ts'
import { renderDependentsGuard, renderSchemaGuard } from './schema-guard.ts'

export function renderDropSql({ config }: { readonly config: PostgresqlConfig }): string {
  return [
    `-- GENERATED by ${BRAND}. Run BEFORE \`prisma migrate deploy\` so that`,
    '-- migrations can drop/alter columns that the redacted views depend on.',
    'BEGIN;',
    // Every setting ends with the transaction (A84, D131): the notices DROP … CASCADE prints are
    // noise, a session holding a lock on the views makes the drop fail instead of wait forever
    // (A72), and JIT would compile the dependents guard's catalog query (A93).
    'SET LOCAL client_min_messages = warning;',
    "SET LOCAL lock_timeout = '60s';",
    'SET LOCAL jit = off;',
    renderSchemaGuard(config),
    renderDependentsGuard(config),
    `DROP SCHEMA IF EXISTS ${quoteIdent(config.schema)} CASCADE;`,
    'COMMIT;',
    '',
  ].join('\n')
}
