// Renders redacted-schema.md: the columns a reader of the database can see.
import { BRAND } from '../brand.ts'
import type { ResolvedConfig, View } from '../types.ts'

export function renderMarkdown({
  config,
  views,
}: {
  readonly config: ResolvedConfig
  readonly views: readonly View[]
}): string {
  const out: string[] = []
  out.push(
    '# Redacted database schema',
    '',
    `<!-- GENERATED by ${BRAND}. Do not edit by hand. -->`,
    '',
    `PostgreSQL, read-only. Query the views in schema \`${config.schema}\` (it is the reader role's default search_path, so ` +
      'unqualified names work). Only the columns listed here exist; every other column was removed on purpose. ' +
      `Statements time out after ${config.statementTimeout}.`,
    '',
  )
  for (const view of views) {
    out.push(`## ${view.name}`, '')
    if (view.doc) out.push(view.doc, '')
    out.push('| column | type | notes |', '|---|---|---|')
    for (const c of view.columns) {
      const notes = [c.isId ? 'primary key' : '', c.nullable ? 'nullable' : '', c.doc]
        .filter(Boolean)
        .join('; ')
      out.push(`| \`${c.column}\` | ${c.type} | ${notes.replace(/\|/g, '\\|')} |`)
    }
    if (view.relations.length) {
      out.push('', 'Joins:')
      for (const r of view.relations) {
        const on = r.fromCols
          .map((c, i) => `${view.name}.${c} = ${r.target}.${r.toCols[i] ?? '?'}`)
          .join(' AND ')
        out.push(`- ${on}`)
      }
    }
    out.push('')
  }
  return out.join('\n')
}
