// Renders redacted-schema.md: the columns a reader of the database can see, each name written as
// the reader must write it in SQL (D146).
import { BRAND } from '../brand.ts'
import { sqlName } from '../sql.ts'
import type { ResolvedConfig, View } from '../types.ts'

export function renderMarkdown({
  config,
  views,
}: {
  readonly config: ResolvedConfig
  readonly views: readonly View[]
}): string {
  const out: string[] = []
  out.push(
    '# Redacted database schema',
    '',
    `<!-- GENERATED by ${BRAND}. Do not edit by hand. -->`,
    '',
    `PostgreSQL, read-only. Query the views in schema \`${sqlName(config.schema)}\` (it is the reader role's default search_path, so ` +
      'unqualified names work). Names are written as SQL needs them: a name in double quotes is ' +
      'case-sensitive and works only with its quotes. A view named like a `pg_catalog` relation, or ' +
      'like a temporary table you created, is shadowed in unqualified queries: qualify it with the ' +
      'schema. Only the columns listed here exist; every ' +
      `other column was removed on purpose. Statements time out after ${config.statementTimeout}.`,
    '',
  )
  for (const view of views) {
    const name = sqlName(view.name)
    out.push(`## ${name}`, '')
    if (view.doc) out.push(view.doc, '')
    out.push('| column | Prisma type | notes |', '|---|---|---|')
    for (const c of view.columns) {
      const notes = [c.isId ? 'primary key' : '', c.nullable ? 'nullable' : '', c.doc]
        .filter(Boolean)
        .join('; ')
      out.push(`| \`${sqlName(c.column)}\` | ${c.type} | ${notes.replace(/\|/g, '\\|')} |`)
    }
    // analyze() keeps only joins whose target columns its target view shows (D146); a target
    // column missing from the list, which it never passes, shows as `?`.
    if (view.relations.length) {
      out.push('', 'Joins:')
      for (const r of view.relations) {
        const target = sqlName(r.target)
        const on = r.fromCols
          .map((c, i) => {
            const to = r.toCols[i]
            return `${name}.${sqlName(c)} = ${target}.${to === undefined ? '?' : sqlName(to)}`
          })
          .join(' AND ')
        out.push(`- ${on}`)
      }
    }
    out.push('')
  }
  return out.join('\n')
}
