// Renders the MySQL apply script in the order of D117 (D95): checks first, the views database
// rebuilt behind the refusal flag (D155), the reader granted SELECT last, a final re-check that
// revokes and aborts (D119). MySQL commits DDL and grants as it runs (A74), so ordering is the safety.
import { BRAND, SCHEMA_MARKER } from '../brand.ts'
import { quoteMysqlIdent as qi, quoteLiteral as ql } from '../sql.ts'
import type { MysqlConfig, View } from '../types.ts'
import {
  defaultDatabaseCheck,
  grantTableAccessCheck,
  preChecks,
  renderRecheck,
  resetReader,
} from './mysql-apply-checks.ts'
import {
  account,
  gated,
  MARKER_VIEW,
  markerGuard,
  renderPrelude,
  renderTeardown,
} from './mysql-guards.ts'

interface Input {
  readonly config: MysqlConfig
  readonly views: readonly View[]
}

const DEFINER = 'CREATE DEFINER = CURRENT_USER SQL SECURITY DEFINER VIEW'

/** One view over the connection database's table, with an explicit column list (A75, D113). */
function viewSql(config: MysqlConfig, view: View): string {
  const cols = view.columns.map((c) => qi(c.column)).join(', ')
  return `${DEFINER} ${qi(config.schema)}.${qi(view.name)} (${cols}) AS SELECT ${cols} FROM ${qi(view.source)};`
}

export function renderMysqlApplySql({ config, views }: Input): string {
  const S = qi(config.schema)
  const A = account(config)
  const out = [
    `-- GENERATED by ${BRAND} from schema.prisma. Do not edit by hand.`,
    `-- Recreates database ${config.schema} with column-filtered views and grants account ${config.role}@${config.readerHost}`,
    '-- SELECT on exactly those views. Run AFTER `prisma migrate deploy`, connected to the source database.',
    '-- MySQL commits DDL and grants as it runs, so this script cannot be rolled back: it checks first, grants last,',
    '-- and revokes the reader and aborts if its final check fails.',
    ...renderPrelude(),
    ...defaultDatabaseCheck.render(config),
    ...markerGuard.render(config),
    ...grantTableAccessCheck.render(config),
    ...resetReader.render(config),
    ...preChecks.flatMap((c) => c.render(config)),
    ...gated(`DROP DATABASE IF EXISTS ${S};`),
    ...gated(`CREATE DATABASE ${S};`),
    ...gated(
      `${DEFINER} ${S}.${qi(MARKER_VIEW)} AS SELECT ${ql(SCHEMA_MARKER)} AS ${qi('marker')};`,
    ),
    ...views.flatMap((v) => gated(viewSql(config, v))),
    ...gated(`CREATE USER IF NOT EXISTS ${A} ACCOUNT LOCK;`),
    ...views.flatMap((v) => gated(`GRANT SELECT ON ${S}.${qi(v.name)} TO ${A};`)),
    ...renderRecheck(
      config,
      views.map((v) => v.name),
    ),
    ...renderTeardown(),
  ]
  return `${out.join('\n')}\n`
}
