// Renders redacted-schema.md for MySQL: the columns a reader of the views database can see, each
// name backtick-quoted as the reader must write it (D104, D113).
import { BRAND } from '../brand.ts'
import { mysqlName } from '../sql.ts'
import type { MysqlConfig, View } from '../types.ts'

/** A CommonMark code span: the delimiter is one backtick longer than any run in `text`. */
function codeSpan(text: string): string {
  const longest = Math.max(0, ...(text.match(/`+/g) ?? []).map((run) => run.length))
  const fence = '`'.repeat(longest + 1)
  const pad = text.startsWith('`') || text.endsWith('`') ? ' ' : ''
  return `${fence}${pad}${text}${pad}${fence}`
}

const cell = (text: string): string => text.replace(/\|/g, '\\|')

export function renderMysqlMarkdown({
  config,
  views,
}: {
  readonly config: MysqlConfig
  readonly views: readonly View[]
}): string {
  const out: string[] = []
  const db = codeSpan(mysqlName(config.schema))
  out.push(
    '# Redacted database schema',
    '',
    `<!-- GENERATED by ${BRAND}. Do not edit by hand. -->`,
    '',
    `MySQL, read-only. Query the views in database ${db}: connect as the reader account, then ` +
      `run ${codeSpan(`USE ${mysqlName(config.schema)}`)} or qualify each table with the database name. Names are written exactly ` +
      'as shown, with their backticks. Only the columns listed here exist; every other column ' +
      'was removed on purpose.',
    '',
  )
  for (const view of views) {
    const name = mysqlName(view.name)
    const nameSpan = codeSpan(name)
    out.push(`## ${name}`, '')
    if (view.doc) out.push(view.doc, '')
    out.push('| column | Prisma type | notes |', '|---|---|---|')
    for (const c of view.columns) {
      const notes = [c.isId ? 'primary key' : '', c.nullable ? 'nullable' : '', c.doc]
        .filter(Boolean)
        .join('; ')
      out.push(`| ${cell(codeSpan(mysqlName(c.column)))} | ${c.type} | ${cell(notes)} |`)
    }
    // A target column missing from the list, which analyze() never passes, shows as `?` (D146).
    if (view.relations.length) {
      out.push('', 'Joins:')
      for (const r of view.relations) {
        const target = codeSpan(mysqlName(r.target))
        const on = r.fromCols
          .map((c, i) => {
            const to = r.toCols[i]
            return `${nameSpan}.${codeSpan(mysqlName(c))} = ${target}.${to === undefined ? '?' : codeSpan(mysqlName(to))}`
          })
          .join(' AND ')
        out.push(`- ${on}`)
      }
    }
    out.push('')
  }
  return out.join('\n')
}
