/** Product name used in generated files, SQL errors and generator output (D54). */
export const BRAND = 'hyde-db'

/** Prefix of the comment on the views schema; the scripts only drop a schema that carries it (D11). */
export const SCHEMA_MARKER: string = `Generated by ${BRAND}`

/** Output directory Prisma uses when the generator block sets none; the manifest and the help name it (D54). */
export const DEFAULT_OUTPUT = './redacted'
