/** Product name used in generated files, SQL errors and generator output (D54). */
export const BRAND = 'hyde-db'

/** Prefix of the comment on the views schema; the scripts only drop a schema that carries it (D11). */
export const SCHEMA_MARKER: string = `Generated by ${BRAND}`
