/** Product name used in generated files, SQL errors and generator output (D17). */
export const BRAND = 'prisma-ai-views'

/** Prefix of the comment on the AI schema; the scripts only drop a schema that carries it (D11). */
export const SCHEMA_MARKER: string = `Generated by ${BRAND}`
