-- GENERATED by hyde-db from schema.prisma. Do not edit by hand.
-- Recreates schema ai with column-filtered views and grants role ai_reader
-- read access to exactly those views. Run AFTER `prisma migrate deploy`.
-- The whole script is one transaction; the final check aborts it if the role
-- could read anything outside the views.

SET client_min_messages = warning;
BEGIN;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ai_reader') THEN
    CREATE ROLE "ai_reader" NOLOGIN;
  END IF;
END $$;

-- Refuse to drop a schema that hyde-db did not create.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'ai'
             AND NOT (coalesce(obj_description(oid, 'pg_namespace'), '') = 'Generated by hyde-db'
                      OR starts_with(coalesce(obj_description(oid, 'pg_namespace'), ''), 'Generated by hyde-db.'))) THEN
    RAISE EXCEPTION 'hyde-db: schema ai exists but was not created by hyde-db (its comment lacks the "Generated by hyde-db" marker); refusing to drop it. Rename or drop that schema yourself, or set the generator config "schema" to an unused name.';
  END IF;
END $$;

DROP SCHEMA IF EXISTS "ai" CASCADE;
CREATE SCHEMA "ai";
COMMENT ON SCHEMA "ai" IS 'Generated by hyde-db. Read-only, PII-filtered views for AI/LLM access. Recreated on every deploy.';

CREATE VIEW "ai"."products" AS SELECT
  "id",
  "title",
  "price_cents",
  "tags",
  "status",
  "category_id"
FROM "public"."products";
COMMENT ON VIEW "ai"."products" IS 'Product catalogue entry.';
COMMENT ON COLUMN "ai"."products"."price_cents" IS 'Price in cents';

CREATE VIEW "ai"."Category" AS SELECT
  "id",
  "label",
  "support_email"
FROM "public"."Category";
COMMENT ON COLUMN "ai"."Category"."label" IS 'Display label';
COMMENT ON COLUMN "ai"."Category"."support_email" IS 'Public support inbox';

-- Privileges: nothing but SELECT on the views in ai.
REVOKE ALL ON SCHEMA "public" FROM "ai_reader";
REVOKE ALL ON ALL TABLES IN SCHEMA "public" FROM "ai_reader";
GRANT USAGE ON SCHEMA "ai" TO "ai_reader";
GRANT SELECT ON ALL TABLES IN SCHEMA "ai" TO "ai_reader";

-- Defence in depth for the session itself.
ALTER ROLE "ai_reader" SET default_transaction_read_only = on;
ALTER ROLE "ai_reader" SET statement_timeout = '15s';
ALTER ROLE "ai_reader" SET search_path = "ai";
ALTER ROLE "ai_reader" NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;

-- Safety check: abort if the role can read any relation outside the AI schema
-- (e.g. via PUBLIC grants or membership in another role), execute a SECURITY DEFINER
-- function, read a sequence, or create objects in any schema.
DO $$
DECLARE
  leaks text;
  fixes text;
BEGIN
  SELECT string_agg(format('%I.%I', n.nspname, c.relname), ', ' ORDER BY 1) INTO leaks
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE c.relkind IN ('r', 'p', 'v', 'm', 'f')
    AND n.nspname NOT IN ('ai', 'pg_catalog', 'information_schema')
    AND n.nspname NOT LIKE 'pg\_%'
    AND (has_table_privilege('ai_reader', c.oid, 'SELECT')
         OR has_any_column_privilege('ai_reader', c.oid, 'SELECT'));
  IF leaks IS NOT NULL THEN
    RAISE EXCEPTION 'hyde-db: role ai_reader can read relations outside schema ai: %', leaks;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_auth_members m JOIN pg_roles r ON r.oid = m.member
             WHERE r.rolname = 'ai_reader') THEN
    RAISE EXCEPTION 'hyde-db: role ai_reader must not be a member of other roles';
  END IF;
  -- The joins on pg_roles below always find the role: this transaction created it above if missing.
  SELECT string_agg(format('%I.%I(%s)', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)), ', ' ORDER BY n.nspname, p.proname),
         string_agg(format('REVOKE EXECUTE ON ROUTINE %s FROM %s;', format('%I.%I(%s)', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)), concat_ws(', ', CASE WHEN has_function_privilege('public', p.oid, 'EXECUTE') THEN 'PUBLIC' END, CASE WHEN r.oid = p.proowner OR EXISTS (SELECT 1 FROM aclexplode(p.proacl) a WHERE a.grantee = r.oid AND a.privilege_type IN ('EXECUTE')) THEN quote_ident(r.rolname) END)), ' ' ORDER BY n.nspname, p.proname)
    INTO leaks, fixes
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace CROSS JOIN pg_roles r
  WHERE r.rolname = 'ai_reader'
    AND p.prosecdef
    AND n.nspname NOT IN ('pg_catalog', 'information_schema')
    AND n.nspname NOT LIKE 'pg\_%'
    AND has_schema_privilege(r.oid, n.oid, 'USAGE')
    AND has_function_privilege(r.oid, p.oid, 'EXECUTE');
  IF leaks IS NOT NULL THEN
    RAISE EXCEPTION 'hyde-db: role ai_reader can execute SECURITY DEFINER functions: %. Fix: %', leaks, fixes;
  END IF;
  SELECT string_agg(format('%I.%I', n.nspname, c.relname), ', ' ORDER BY n.nspname, c.relname),
         string_agg(format('REVOKE ALL ON SEQUENCE %s FROM %s;', format('%I.%I', n.nspname, c.relname), concat_ws(', ', CASE WHEN has_sequence_privilege('public', c.oid, 'SELECT, USAGE, UPDATE') THEN 'PUBLIC' END, CASE WHEN r.oid = c.relowner OR EXISTS (SELECT 1 FROM aclexplode(c.relacl) a WHERE a.grantee = r.oid AND a.privilege_type IN ('SELECT', 'USAGE', 'UPDATE')) THEN quote_ident(r.rolname) END)), ' ' ORDER BY n.nspname, c.relname)
    INTO leaks, fixes
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace CROSS JOIN pg_roles r
  WHERE r.rolname = 'ai_reader'
    AND c.relkind = 'S'
    AND CASE WHEN c.relkind = 'S' THEN has_sequence_privilege(r.oid, c.oid, 'SELECT, USAGE, UPDATE') ELSE false END;
  IF leaks IS NOT NULL THEN
    RAISE EXCEPTION 'hyde-db: role ai_reader can read sequences: %. Fix: %', leaks, fixes;
  END IF;
  SELECT string_agg(format('%I', n.nspname), ', ' ORDER BY n.nspname),
         string_agg(format('REVOKE CREATE ON SCHEMA %I FROM %s;', n.nspname, concat_ws(', ', CASE WHEN has_schema_privilege('public', n.oid, 'CREATE') THEN 'PUBLIC' END, CASE WHEN r.oid = n.nspowner OR EXISTS (SELECT 1 FROM aclexplode(n.nspacl) a WHERE a.grantee = r.oid AND a.privilege_type IN ('CREATE')) THEN quote_ident(r.rolname) END)), ' ' ORDER BY n.nspname)
    INTO leaks, fixes
  FROM pg_namespace n CROSS JOIN pg_roles r
  WHERE r.rolname = 'ai_reader'
    AND has_schema_privilege(r.oid, n.oid, 'CREATE');
  IF leaks IS NOT NULL THEN
    RAISE EXCEPTION 'hyde-db: role ai_reader can create objects in schemas: %. Fix: %', leaks, fixes;
  END IF;
END $$;

COMMIT;
