import { describe, expect, it } from 'vitest'
import { BRAND, DEFAULT_OUTPUT, SCHEMA_MARKER } from '../../src/brand.ts'

describe('branding', () => {
  it('D54: the product name is hyde-db and the schema marker says so', () => {
    expect(BRAND).toBe('hyde-db')
    expect(SCHEMA_MARKER).toBe('Generated by hyde-db')
  })

  it('D54: the default output directory is ./redacted', () => {
    expect(DEFAULT_OUTPUT).toBe('./redacted')
  })
})
