import { describe, expect, it } from 'vitest'
import { BRAND } from '../../src/brand.ts'
import { renderDropSql } from '../../src/render/drop-sql.ts'
import { config } from '../helpers/views.ts'

/** The start of the guard that refuses to drop objects outside the views schema (D141). */
const DEPENDENTS_GUARD = '-- Refuse to drop objects outside schema'

describe('drop SQL', () => {
  const sql = renderDropSql({ config })

  it('drops the redacted schema and nothing else', () => {
    expect(sql).toContain('\nDROP SCHEMA IF EXISTS "redacted" CASCADE;\n')
    expect(sql.match(/DROP /g)).toHaveLength(1)
  })

  it('says when to run it', () => {
    expect(sql.split('\n')[0]).toBe(
      `-- GENERATED by ${BRAND}. Run BEFORE \`prisma migrate deploy\` so that`,
    )
  })

  it('D54: is branded hyde-db', () => {
    expect(sql).toContain('-- GENERATED by hyde-db.')
    expect(sql).not.toContain('prisma-ai-views')
  })

  it('D11: refuses to drop a schema without the hyde-db marker', () => {
    expect(sql.indexOf("'Generated by hyde-db'")).toBeLessThan(sql.indexOf('DROP SCHEMA'))
    expect(sql).toContain('refusing to drop it')
  })

  it('D58: runs the guard and the drop in one transaction, so a refused drop changes nothing', () => {
    expect(sql.startsWith('-- ')).toBe(true)
    expect(sql.indexOf('BEGIN;')).toBeLessThan(sql.indexOf('DO $$'))
    expect(sql.endsWith('DROP SCHEMA IF EXISTS "redacted" CASCADE;\nCOMMIT;\n')).toBe(true)
  })

  it('A72, A84, D110: sets lock_timeout once, inside the transaction and for it alone, so a lock held by a reader fails the drop', () => {
    expect(sql.match(/lock_timeout/g)).toHaveLength(1)
    expect(sql).toContain("\nSET LOCAL lock_timeout = '60s';\n")
  })

  it('A84, D131: every session setting is SET LOCAL, right after BEGIN, so none outlives the script', () => {
    const settings = sql.split('\n').filter((line) => /^SET /.test(line))
    expect(settings).toEqual([
      'SET LOCAL client_min_messages = warning;',
      "SET LOCAL lock_timeout = '60s';",
      // Like the apply script (A93): the guard's catalog query must not be JIT-compiled.
      'SET LOCAL jit = off;',
    ])
    expect(sql).toContain(`\nBEGIN;\n${settings.join('\n')}\n`)
  })

  it('A97, D141: refuses to drop the schema while objects outside it depend on its views, after the marker guard', () => {
    const guard = sql.indexOf(DEPENDENTS_GUARD)
    expect(guard).toBeGreaterThan(sql.indexOf('refusing to drop it'))
    expect(guard).toBeLessThan(sql.indexOf('DROP SCHEMA'))
  })

  it('D11: the marker guard checks the configured schema', () => {
    const custom = renderDropSql({ config: { ...config, schema: 'safe' } })
    expect(custom).toContain("WHERE nspname = 'safe'")
    expect(custom).toContain('hyde-db: schema safe exists but was not created by hyde-db')
    expect(custom).toContain('DROP SCHEMA IF EXISTS "safe" CASCADE;')
    expect(custom).not.toContain("'redacted'")
  })
})
