import { describe, expect, it } from 'vitest'
import { renderMysqlApplySql } from '../../src/render/mysql-apply-sql.ts'
import type { View } from '../../src/types.ts'

const config = {
  dialect: 'mysql',
  schema: 'redacted',
  role: 'redacted_reader',
  readerHost: '%',
  default: 'hidden',
  strict: true,
} as const

const users: View = {
  model: 'User',
  name: 'users',
  sourceSchema: null,
  source: 'users',
  columns: [
    { column: 'id', field: 'id', type: 'Int', nullable: false, isId: true, doc: '' },
    { column: 'email', field: 'email', type: 'String', nullable: false, isId: false, doc: '' },
  ],
  relations: [],
  doc: '',
}

const sql = renderMysqlApplySql({ config, views: [users] })
const at = (s: string, from = 0): number => {
  const i = sql.indexOf(s, from)
  expect(i, s).toBeGreaterThan(-1)
  return i
}

describe('renderMysqlApplySql', () => {
  it('D117, D160: statements appear in the ledger order', () => {
    const order = [
      "SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_BACKSLASH_ESCAPES'",
      'DATABASE() IS NULL',
      'LOWER(DATABASE()) = LOWER(',
      'information_schema.SCHEMATA',
      "'role_edges'",
      'REVOKE ALL PRIVILEGES, GRANT OPTION FROM',
      'mysql.role_edges',
      'DROP DATABASE IF EXISTS',
      'CREATE USER IF NOT EXISTS',
      'GRANT SELECT ON `redacted`.',
    ].map((s) => at(s))
    expect(order).toEqual([...order].sort((a, b) => a - b))
    expect(sql.lastIndexOf('REVOKE ALL PRIVILEGES, GRANT OPTION FROM')).toBeGreaterThan(
      at('GRANT SELECT ON `redacted`.'),
    )
  })

  it('A75, D115: every view is created DEFINER = CURRENT_USER SQL SECURITY DEFINER, including the marker view', () => {
    expect(sql.match(/CREATE DEFINER = CURRENT_USER SQL SECURITY DEFINER VIEW/g)?.length).toBe(2)
    expect(sql).toContain("SELECT ''Generated by hyde-db'' AS `marker`")
  })

  it('D113: views read unqualified names from the connection database', () => {
    expect(sql).toContain('FROM `users`')
    expect(sql).not.toMatch(/FROM `[^`]+`\.`users`/)
    expect(sql).toContain('(`id`, `email`) AS SELECT `id`, `email` FROM `users`')
  })

  it('D116, A85: the account is created only when missing, locked, without a password, never altered', () => {
    expect(sql).toContain("CREATE USER IF NOT EXISTS ''redacted_reader''@''%'' ACCOUNT LOCK")
    expect(sql).not.toContain('IDENTIFIED')
    // The pre-check fixes mention ALTER USER as advice text; no executed statement does.
    expect(sql).not.toMatch(/^(ALTER USER|SET @hyde_sql = IF\(@hyde_refused IS NULL, 'ALTER)/m)
  })

  it('D117: the reader is granted SELECT on each view, never on the marker view or the database', () => {
    expect(sql).toContain("GRANT SELECT ON `redacted`.`users` TO ''redacted_reader''@''%''")
    expect(sql).not.toContain('`hyde_db_marker` TO')
    expect(sql).not.toMatch(/GRANT SELECT ON `redacted`\.\*/)
  })

  it('D155, D119: the reset REVOKE is a plain line, every statement from the database drop on is gated', () => {
    expect(sql).toMatch(
      /^REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'redacted_reader'@'%' IGNORE UNKNOWN USER;$/m,
    )
    const tail = sql.slice(at('DROP DATABASE IF EXISTS') - 200)
    expect(tail).not.toMatch(/^(DROP DATABASE|CREATE DATABASE|CREATE DEFINER|CREATE USER|GRANT)/m)
    expect(tail.match(/^SET @hyde_sql = IF\(@hyde_refused IS NULL/gm)?.length).toBe(
      1 + 1 + 1 + 1 + 1 + 1,
    )
  })

  it('D104: names and text survive the doubled quoting under the pinned sql_mode', () => {
    const nasty = renderMysqlApplySql({
      config,
      views: [
        {
          ...users,
          name: "we`i'rd",
          source: 'we`ird',
          columns: [{ ...(users.columns[0] as (typeof users.columns)[number]), column: "a'b\\c" }],
        },
      ],
    })
    expect(nasty).toContain("`we``i''rd`")
    expect(nasty).toContain("`a''b\\c`")
    expect(nasty).toContain('FROM `we``ird`')
  })

  it('D115, A101: with no views the script still creates the marker view and grants nothing', () => {
    const none = renderMysqlApplySql({ config, views: [] })
    expect(none).toContain('hyde_db_marker')
    expect(none).not.toContain('GRANT SELECT ON `redacted`')
  })

  it('A76: contains no DELIMITER and no routine', () => {
    expect(sql).not.toMatch(/DELIMITER|CREATE (PROCEDURE|FUNCTION)/)
  })

  it('D117: ends by dropping the abort table, after the re-check', () => {
    expect(sql.trimEnd().endsWith('DROP TEMPORARY TABLE IF EXISTS `hyde_db_abort`;')).toBe(true)
    expect(sql.lastIndexOf('EXECUTE hyde_stmt;')).toBeLessThan(
      sql.lastIndexOf('DROP TEMPORARY TABLE'),
    )
  })
})
