import { describe, expect, it } from 'vitest'
import {
  ABORT_TABLE,
  abortIf,
  abortWhenFound,
  account,
  FIX_LIMIT,
  gated,
  MARKER_FIX,
  MARKER_VIEW,
  MESSAGE_LIMIT,
  markerGuard,
  NO_DATABASE_MESSAGE,
  renderPrelude,
  renderTeardown,
} from '../../src/render/mysql-guards.ts'

const config = {
  dialect: 'mysql',
  schema: 'redacted',
  role: 'redacted_reader',
  readerHost: '%',
  default: 'hidden',
  strict: true,
} as const

describe('mysql script guards', () => {
  it('D117, D160: the prelude pins the session, reports a missing default database before the abort table exists, then creates the table', () => {
    expect(renderPrelude()).toEqual([
      "SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_BACKSLASH_ESCAPES';",
      'SET SESSION lock_wait_timeout = 60;',
      'SET @hyde_refused = NULL;',
      `SET @hyde_refused = IF(DATABASE() IS NULL, '${NO_DATABASE_MESSAGE}', @hyde_refused);`,
      "SET SESSION sql_warnings = IF(@hyde_refused IS NULL, IF(@@SESSION.sql_warnings, 'ON', 'OFF'), @hyde_refused);",
      'DROP TEMPORARY TABLE IF EXISTS `hyde_db_abort`;',
      'CREATE TEMPORARY TABLE `hyde_db_abort` (`problem` INT NOT NULL);',
    ])
  })

  it('D160, D151: the missing-database message has the hyde-db shape and fits 128 characters', () => {
    expect(NO_DATABASE_MESSAGE).toMatch(
      /^hyde-db: .+ Fix: add the database name to the connection URL$/,
    )
    expect(NO_DATABASE_MESSAGE.length).toBeLessThanOrEqual(MESSAGE_LIMIT)
  })

  it('D99: an abort is a failing insert into the temporary table, with no routine and no DELIMITER', () => {
    const sql = abortIf('1 = 1', 'x.', 'y;').join('\n')
    expect(sql).toContain('INSERT INTO `hyde_db_abort`')
    expect(sql).not.toMatch(/DELIMITER|CREATE (PROCEDURE|FUNCTION)|SIGNAL/i)
    expect(ABORT_TABLE).toBe('hyde_db_abort')
    expect(MARKER_VIEW).toBe('hyde_db_marker')
  })

  it('D99, D151: the abort message starts with hyde-db: and the limit is rendered from MESSAGE_LIMIT, the fix kept whole', () => {
    expect(MESSAGE_LIMIT).toBe(128)
    const sql = abortIf('1 = 1', 'p', 'f').join('\n')
    expect(sql).toContain("CONCAT('hyde-db: '")
    expect(sql).toContain(
      `GREATEST(0, ${MESSAGE_LIMIT - 'hyde-db: '.length - ' Fix: '.length} - CHAR_LENGTH(f.fix))`,
    )
    expect(sql).toContain("' Fix: ', f.fix")
  })

  it('D99: abortWhenFound records the first message in the refusal flag and aborts only when a row exists', () => {
    const sql = abortWhenFound('SELECT 1 AS problem, 2 AS fix').join('\n')
    expect(sql).toContain('FROM (SELECT 1 AS problem, 2 AS fix) f LIMIT 1')
    expect(sql).toContain('SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);')
    expect(sql).toContain('WHERE @hyde_message IS NOT NULL')
  })

  it('D99: abortIf quotes the problem and the fix as literals and fires on the condition', () => {
    const sql = abortIf('a = 1', "it's", "do 'x'").join('\n')
    expect(sql).toContain("'it''s' AS problem")
    expect(sql).toContain("'do ''x''' AS fix")
    expect(sql).toContain('WHERE a = 1')
  })

  it('Review Focus 1, D155: a gated statement is prepared from a literal and only runs while @hyde_refused is NULL', () => {
    expect(gated("DROP DATABASE `o'x`;").join('\n')).toBe(
      [
        "SET @hyde_sql = IF(@hyde_refused IS NULL, 'DROP DATABASE `o''x`;', 'DO 0');",
        'PREPARE hyde_stmt FROM @hyde_sql;',
        'EXECUTE hyde_stmt;',
        'DEALLOCATE PREPARE hyde_stmt;',
      ].join('\n'),
    )
  })

  it('D115: the marker guard looks for the view hyde_db_marker with a marker column and the marker text, only when the database exists', () => {
    const sql = markerGuard.render(config).join('\n')
    expect(sql).toContain('information_schema.SCHEMATA')
    expect(sql).toContain("'hyde_db_marker'")
    expect(sql).toContain('Generated by hyde-db')
    expect(sql).toContain("'redacted'")
    expect(markerGuard.id).toBe('marker-guard')
  })

  it('D151: with the default schema the marker refusal prints its problem and fix uncut', () => {
    const problem = 'database redacted has no hyde-db marker view.'
    expect(markerGuard.render(config).join('\n')).toContain(
      "CONCAT('database ', 'redacted', ' has no hyde-db marker view.')",
    )
    expect(`hyde-db: ${problem} Fix: ${MARKER_FIX}`.length).toBeLessThanOrEqual(MESSAGE_LIMIT)
  })

  it('D99: the marker guard renders the longest schema name into the check', () => {
    const longer = { ...config, schema: 'a'.repeat(64) }
    expect(markerGuard.render(longer).join('\n')).toContain(`SCHEMA_NAME = '${'a'.repeat(64)}'`)
  })

  it('D155: abortWhenFound emits the message SET, then the flag SET, then the INSERT, in that order', () => {
    // Cut-to-fit and gating at runtime are proven by the MySQL attack suite (Task 13+).
    const lines = abortWhenFound('SELECT 1 AS problem, 2 AS fix')
    expect(lines).toHaveLength(3)
    expect(lines[0]).toMatch(/^SET @hyde_message = /)
    expect(lines[1]).toBe('SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);')
    expect(lines[2]).toMatch(/^INSERT INTO `hyde_db_abort`/)
    expect(lines[0]).toContain(`${FIX_LIMIT} - CHAR_LENGTH(f.fix)`)
    expect(FIX_LIMIT).toBe(113)
  })

  it('Review Focus 1: gated emits SET, PREPARE, EXECUTE, DEALLOCATE in that order', () => {
    expect(gated('DO 1;').map((l) => l.split(' ')[0])).toEqual([
      'SET',
      'PREPARE',
      'EXECUTE',
      'DEALLOCATE',
    ])
  })

  it('D104: account is the quoted user and host, doubling single quotes', () => {
    expect(account(config)).toBe("'redacted_reader'@'%'")
    expect(account({ role: "o'x", readerHost: "h'y" })).toBe("'o''x'@'h''y'")
  })

  it('D99: the teardown drops the abort table', () => {
    expect(renderTeardown().join('\n')).toBe('DROP TEMPORARY TABLE IF EXISTS `hyde_db_abort`;')
  })
})
