import { describe, expect, it } from 'vitest'
import { renderMysqlMarkdown } from '../../src/render/mysql-markdown.ts'
import type { MysqlConfig, View } from '../../src/types.ts'
import { orders, users } from '../helpers/views.ts'

const config: MysqlConfig = {
  dialect: 'mysql',
  schema: 'redacted',
  role: 'redacted_reader',
  readerHost: '%',
  default: 'hidden',
  strict: true,
}
const mysqlUsers: View = { ...users, sourceSchema: null }
const mysqlOrders: View = { ...orders, sourceSchema: null }

describe('MySQL Markdown', () => {
  it('D104: says MySQL, names the views database, and tells the reader to qualify names or run USE', () => {
    const md = renderMysqlMarkdown({ config, views: [mysqlUsers] })
    expect(md).toContain('MySQL, read-only')
    expect(md).toContain('`redacted`')
    expect(md).toContain('run `` USE `redacted` `` or')
  })

  it('A78: does not claim a statement timeout or a read-only session default', () => {
    const md = renderMysqlMarkdown({ config, views: [mysqlUsers] })
    expect(md).not.toMatch(/time out after/)
    expect(md).not.toMatch(/search_path/)
  })

  it('D104: every table and column name is backtick-quoted; a backtick in a name is doubled', () => {
    const md = renderMysqlMarkdown({
      config,
      views: [
        {
          ...mysqlUsers,
          name: 'we`ird',
          columns: [
            { column: 'a`b', field: 'id', type: 'Int', nullable: false, isId: true, doc: '' },
          ],
        },
      ],
    })
    expect(md).toContain('## `we``ird`')
    expect(md).toContain('`a``b`')
  })

  it('D146 parity: the type column is labelled as Prisma types; joins appear with quoted names', () => {
    const md = renderMysqlMarkdown({ config, views: [mysqlUsers, mysqlOrders] })
    expect(md).toContain('| column | Prisma type | notes |')
    expect(md).toContain('| `` `country` `` | String | nullable; ISO \\| code |')
    expect(md).toContain('| `` `id` `` | Int | primary key |')
    expect(md).toContain("A customer's account.")
    expect(md).toContain('Joins:\n- `` `orders` ``.`` `user_id` `` = `` `users` ``.`` `id` ``')
  })

  it('D146 parity: a join target column the view does not show renders as ?', () => {
    const odd: View = {
      ...mysqlOrders,
      relations: [{ fromCols: ['user_id'], target: 'users', targetModel: 'User', toCols: [] }],
    }
    expect(renderMysqlMarkdown({ config, views: [odd] })).toContain(
      '`` `orders` ``.`` `user_id` `` = `` `users` ``.?',
    )
  })

  it('D104: a name that starts and ends with a backtick renders as a valid code span, and | is escaped in cells', () => {
    const md = renderMysqlMarkdown({
      config,
      views: [
        {
          ...mysqlUsers,
          columns: [
            { column: '`x`', field: 'id', type: 'Int', nullable: false, isId: true, doc: '' },
            { column: 'a|b', field: 'a', type: 'Int', nullable: false, isId: false, doc: '' },
          ],
        },
      ],
    })
    expect(md).toContain('| ```` ```x``` ```` | Int | primary key |')
    expect(md).toContain('| `` `a\\|b` `` | Int |')
  })

  it('D3: the generated header names the product and says do not edit', () => {
    expect(renderMysqlMarkdown({ config, views: [] })).toContain(
      'GENERATED by hyde-db. Do not edit by hand.',
    )
  })
})
