import { describe, expect, it } from 'vitest'
import { BRAND } from '../../src/brand.ts'
import { renderMarkdown } from '../../src/render/markdown.ts'
import { config, orders, users } from '../helpers/views.ts'

describe('Markdown', () => {
  const md = renderMarkdown({ config, views: [users, orders] })

  it('describes the schema, search_path and timeout', () => {
    expect(md.split('\n')[0]).toBe('# Redacted database schema')
    expect(md).toContain('Query the views in schema `redacted`')
    expect(md).toContain('Statements time out after 15s.')
  })

  it("D54: the intro names the reader role's search_path and says other columns were removed", () => {
    expect(md).toContain(
      "Query the views in schema `redacted` (it is the reader role's default search_path, so " +
        'unqualified names work). Only the columns listed here exist; every other column was ' +
        'removed on purpose. Statements time out after 15s.',
    )
    expect(md).not.toContain('deliberately')
  })

  it('carries the generated-file notice', () => {
    expect(md).toContain(`<!-- GENERATED by ${BRAND}. Do not edit by hand. -->`)
  })

  it('D54: is branded hyde-db', () => {
    expect(md).toContain('<!-- GENERATED by hyde-db. Do not edit by hand. -->')
  })

  it('lists columns with type and notes, escaping pipes', () => {
    expect(md).toContain("## users\n\nA customer's account.\n\n| column | type | notes |")
    expect(md).toContain('| `id` | Int | primary key |')
    expect(md).toContain('| `country` | String | nullable; ISO \\| code |')
  })

  it('describes joins and marks missing target columns with ?', () => {
    expect(md).toContain('Joins:\n- orders.user_id = users.id')
    const partial = renderMarkdown({
      config,
      views: [
        {
          ...orders,
          relations: [{ fromCols: ['a', 'b'], target: 't', targetModel: 'T', toCols: ['x'] }],
        },
      ],
    })
    expect(partial).toContain('- orders.a = t.x AND orders.b = t.?')
  })
})
