import { describe, expect, it } from 'vitest'
import { BRAND } from '../../src/brand.ts'
import { renderApplySql } from '../../src/render/apply-sql.ts'
import { config, orders, users } from '../helpers/views.ts'

describe('apply SQL', () => {
  const sql = renderApplySql({ config, views: [users, orders] })

  it('is generated by the product and marks the schema it creates', () => {
    expect(sql.split('\n')[0]).toBe(
      `-- GENERATED by ${BRAND} from schema.prisma. Do not edit by hand.`,
    )
    expect(sql).toContain(
      `COMMENT ON SCHEMA "redacted" IS 'Generated by ${BRAND}. Read-only views with sensitive columns removed.`,
    )
  })

  it('runs as one transaction and creates the role only when missing', () => {
    expect(sql).toContain("SET client_min_messages = warning;\nSET lock_timeout = '60s';\nBEGIN;\n")
    expect(sql).toContain(
      "IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'redacted_reader') THEN",
    )
    expect(sql).toContain('CREATE ROLE "redacted_reader" NOLOGIN;')
    expect(sql.trimEnd().endsWith('COMMIT;')).toBe(true)
  })

  it('creates one view per input with exactly its columns, quoting identifiers', () => {
    expect(sql).toContain(
      'CREATE VIEW "redacted"."users" AS SELECT\n  "id",\n  "country"\nFROM "public"."users";',
    )
    expect(sql).toContain(
      'CREATE VIEW "redacted"."orders" AS SELECT\n  "id",\n  "user_id"\nFROM "sales"."Order Items";',
    )
  })

  it('escapes doc comments as string literals', () => {
    expect(sql).toContain(`COMMENT ON VIEW "redacted"."users" IS 'A customer''s account.';`)
    expect(sql).toContain(`COMMENT ON COLUMN "redacted"."users"."country" IS 'ISO | code';`)
    expect(sql).not.toContain('COMMENT ON VIEW "redacted"."orders"')
  })

  it('grants nothing but USAGE and SELECT in the redacted schema and sets session defaults', () => {
    expect(sql).toContain('GRANT USAGE ON SCHEMA "redacted" TO "redacted_reader";')
    expect(sql).toContain('GRANT SELECT ON ALL TABLES IN SCHEMA "redacted" TO "redacted_reader";')
    expect(sql).toContain('ALTER ROLE "redacted_reader" SET default_transaction_read_only = on;')
    expect(sql).toContain(`ALTER ROLE "redacted_reader" SET statement_timeout = '15s';`)
    expect(sql).toContain('ALTER ROLE "redacted_reader" SET search_path = "redacted";')
  })

  it('A72, D92: sets lock_timeout once, before the transaction, so a lock held by a reader fails the deploy', () => {
    expect(sql.match(/lock_timeout/g)).toHaveLength(1)
    expect(sql.indexOf("SET lock_timeout = '60s';")).toBeLessThan(sql.indexOf('BEGIN;'))
  })

  it('D69: does not revoke anything in the source schema itself', () => {
    expect(sql).not.toContain('REVOKE ALL ON SCHEMA')
    expect(sql).not.toContain('REVOKE ALL ON ALL TABLES IN SCHEMA')
    expect(sql).not.toMatch(/^REVOKE /m)
  })

  /** The final safety check's DO block, from its header comment to the end of the script. */
  const finalCheckBlock = sql.slice(sql.indexOf('-- Safety check'))

  /** The part of the final DO block from the last occurrence of `from` before the abort message `to`, up to it. */
  function check(from: string, to: string): string {
    const end = sql.indexOf(to)
    return sql.slice(sql.lastIndexOf(from, end), end)
  }

  const relationCheck = check(
    "string_agg(format('%I.%I', n.nspname, c.relname), ', '",
    'can read relations outside schema',
  )

  it('keeps the base relation check on tables, views, materialized views and foreign tables', () => {
    expect(relationCheck).toContain("AND c.relkind IN ('r', 'p', 'v', 'm', 'f')")
    expect(relationCheck).toContain(
      "AND n.nspname NOT IN ('redacted', 'pg_catalog', 'information_schema')",
    )
  })

  it('D89: the relation check refuses any table or column privilege, but not MAINTAIN', () => {
    expect(relationCheck).toContain(
      "AND (has_table_privilege(r.oid, c.oid, 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER')\n" +
        "         OR has_any_column_privilege(r.oid, c.oid, 'SELECT, INSERT, UPDATE, REFERENCES'));",
    )
    expect(sql).not.toContain('MAINTAIN')
  })

  it('D89: the relation abort revokes ALL per relation, in schema and relation order, columns included', () => {
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader can read relations outside schema redacted: %. Fix: %', leaks, fixes;`,
    )
    expect(relationCheck).toContain("format('ALL ON %s', format('%I.%I', n.nspname, c.relname))")
    expect(relationCheck).toContain(
      'aclexplode(c.relacl || ARRAY(SELECT unnest(att.attacl) FROM pg_attribute att WHERE att.attrelid = c.oid AND att.attnum > 0 AND NOT att.attisdropped))',
    )
    expect(relationCheck).toMatch(/\), ' ' ORDER BY n\.nspname, c\.relname\)\n/)
    expect(sql).not.toContain('REVOKE SELECT')
    expect(sql).not.toContain('ORDER BY 1)')
  })

  it('A69, D89: every REVOKE fix revokes as each grantor that is not the owner, the reader first, with CASCADE', () => {
    for (const owner of [
      'c.relowner',
      'p.proowner',
      'n.nspowner',
      'd.datdba',
      'l.lomowner',
      'fs.srvowner',
    ]) {
      expect(sql).toContain(`AND a.grantee IN (0, r.oid) AND a.grantor <> ${owner}) g`)
      expect(sql).toContain(`AND a.grantee = 0 AND a.grantor = ${owner})`)
      expect(sql).toContain(`r.oid = ${owner} OR EXISTS (`)
    }
    expect(sql).not.toContain('a.grantor <> r.oid')
    expect(sql).toContain(
      "format('SET ROLE %s; %s RESET ROLE;', t.grantor::regrole, format('REVOKE %s FROM %s CASCADE;', format('CREATE ON DATABASE %I', d.datname), t.grantees))",
    )
    // The reader's revokes come before anything that takes away the grant options they need.
    expect(sql).toContain("' ' ORDER BY t.grantor <> r.oid, t.grantor)")
    expect(sql).not.toContain("' ' ORDER BY t.grantor)")
    expect(sql).toContain("|| ' CASCADE;')")
    // Every REVOKE on an object ends in CASCADE; ALTER DEFAULT PRIVILEGES revokes no grants.
    expect(sql).not.toMatch(/'REVOKE [^']*FROM %s;'/)
  })

  /** The REVOKE of exactly the privileges a grantor granted on `object`. */
  const exactly = (object: string, privileges: string): string =>
    `(SELECT format('REVOKE %s ON %s FROM %s CASCADE;', string_agg(DISTINCT x.privilege_type, ', ' ORDER BY x.privilege_type), ${object}, t.grantees) ` +
    `FROM aclexplode(c.relacl) x WHERE x.grantor = t.grantor AND x.grantee IN (0, r.oid) AND x.privilege_type IN (${privileges}) HAVING count(*) > 0)`

  it('A69, D89: a grantor, the reader included, revokes exactly the table privileges it granted, then ALL on the columns it granted privileges on', () => {
    expect(relationCheck).toContain(
      `concat_ws(' ', ${exactly("format('%I.%I', n.nspname, c.relname)", "'SELECT', 'INSERT', 'UPDATE', 'DELETE', 'TRUNCATE', 'REFERENCES', 'TRIGGER'")}, ` +
        "(SELECT format('REVOKE ALL (%s) ON %s FROM %s CASCADE;', string_agg(quote_ident(att.attname), ', ' ORDER BY att.attnum), format('%I.%I', n.nspname, c.relname), t.grantees) " +
        'FROM pg_attribute att WHERE att.attrelid = c.oid AND att.attnum > 0 AND NOT att.attisdropped AND EXISTS (SELECT 1 FROM aclexplode(att.attacl) x WHERE x.grantor = t.grantor AND x.grantee IN (0, r.oid)) HAVING count(*) > 0))',
    )
  })

  it('D13, D89: a grantor revokes exactly the sequence privileges it granted', () => {
    expect(sql).toContain(
      exactly(
        "format('SEQUENCE %s', format('%I.%I', n.nspname, c.relname))",
        "'SELECT', 'USAGE', 'UPDATE'",
      ),
    )
  })

  it('A69, D89: a reader that lost the grant option behind a column grant it passed on is given it back to revoke it, then loses it', () => {
    const regrant =
      "(SELECT format('ALL (%s) ON %s', string_agg(quote_ident(att.attname), ', ' ORDER BY att.attnum), format('%I.%I', n.nspname, c.relname)) " +
      'FROM pg_attribute att WHERE att.attrelid = c.oid AND att.attnum > 0 AND NOT att.attisdropped ' +
      'AND EXISTS (SELECT 1 FROM aclexplode(att.attacl) x WHERE x.grantor = r.oid AND x.grantee IN (0, r.oid) ' +
      "AND NOT has_column_privilege(r.oid, c.oid, att.attnum, x.privilege_type || ' WITH GRANT OPTION')) HAVING count(*) > 0)"
    expect(relationCheck).toContain(
      `format('%sSET ROLE %s; %s RESET ROLE;', CASE WHEN t.grantor = r.oid THEN 'GRANT ' || ${regrant} || ' TO ' || quote_ident(r.rolname) || ' WITH GRANT OPTION; ' END, t.grantor::regrole, concat_ws(' ', `,
    )
    // The owner's statement then names the reader, which takes the grant option away again.
    expect(relationCheck).toContain(
      `CASE WHEN r.oid = c.relowner OR EXISTS (SELECT 1 FROM aclexplode(c.relacl || ARRAY(SELECT unnest(att.attacl) FROM pg_attribute att WHERE att.attrelid = c.oid AND att.attnum > 0 AND NOT att.attisdropped)) a WHERE a.privilege_type IN ('SELECT', 'INSERT', 'UPDATE', 'DELETE', 'TRUNCATE', 'REFERENCES', 'TRIGGER') AND a.grantee = r.oid AND a.grantor = c.relowner) OR ${regrant} IS NOT NULL THEN quote_ident(r.rolname) END`,
    )
    // Only relations and catalog relations regrant: other objects have no column grants that
    // could outlive the grant option behind them.
    expect(sql.match(/WITH GRANT OPTION; /g)).toHaveLength(2)
  })

  it('D13, D24, D76, D80, D90: definer functions, sequences, schemas, the database, large objects and foreign servers use the same fix', () => {
    expect(sql).toContain("format('EXECUTE ON ROUTINE %s', ")
    expect(sql).toContain('p.proacl IS NULL OR EXISTS (')
    expect(sql).toContain("format('ALL ON SEQUENCE %s', ")
    expect(sql).toContain("format('CREATE ON SCHEMA %I', n.nspname)")
    expect(sql).toContain("format('CREATE ON DATABASE %I', d.datname)")
    expect(sql).toContain("format('ALL ON LARGE OBJECT %s', l.oid)")
    expect(sql).toContain("format('USAGE ON FOREIGN SERVER %I', fs.srvname)")
  })

  it('D80: refuses USAGE on any foreign server', () => {
    expect(sql).toContain('FROM pg_foreign_server fs CROSS JOIN pg_roles r')
    expect(sql).toContain("AND has_server_privilege(r.oid, fs.oid, 'USAGE');")
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader can use foreign servers: %. Fix: %', leaks, fixes;`,
    )
  })

  const membershipCheck = check(
    "string_agg(format('%I', g.rolname)",
    'must not be a member of other roles',
  )

  it('D89: the membership abort prints a REVOKE … CASCADE per membership, GRANTED BY its grantor on PostgreSQL 16+', () => {
    expect(membershipCheck).toContain(
      "string_agg((SELECT string_agg(format('REVOKE %I FROM %I%s CASCADE;', g.rolname, r.rolname, CASE WHEN current_setting('server_version_num')::int >= 160000 THEN format(' GRANTED BY %s', m.grantor::regrole) END), ' ' ORDER BY m.grantor) FROM pg_auth_members m WHERE m.roleid = g.oid AND m.member = r.oid), ' ' ORDER BY g.rolname)",
    )
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader must not be a member of other roles: %. Fix: %', leaks, fixes;`,
    )
  })

  const ownershipCheck = check('FROM pg_roles r', 'owns objects it must not own')

  it('D82: the ownership abort lists every object the role owns, from pg_shdepend, by type and qualified name', () => {
    expect(ownershipCheck).toContain(
      "JOIN pg_shdepend s ON s.refclassid = 'pg_authid'::regclass AND s.refobjid = r.oid AND s.deptype = 'o'",
    )
    expect(ownershipCheck).toContain(
      'AND s.dbid IN (0, (SELECT d.oid FROM pg_database d WHERE d.datname = current_database()))',
    )
    expect(ownershipCheck).toContain(
      'CROSS JOIN LATERAL pg_identify_object(s.classid, s.objid, s.objsubid) i',
    )
    expect(sql).toContain(
      'SELECT string_agg(format(\'%s %s\', i.type, i.identity), \', \' ORDER BY i.type COLLATE "C", i.identity COLLATE "C") INTO leaks',
    )
  })

  it("D82: the ownership abort leaves out the role's own temporary objects and large objects, and what REASSIGN OWNED does not move", () => {
    expect(ownershipCheck).toContain("AND coalesce(i.schema, '') !~ '^pg_(toast_)?temp_'")
    expect(ownershipCheck).toContain(
      "AND s.classid NOT IN ('pg_largeobject'::regclass, 'pg_default_acl'::regclass, 'pg_user_mapping'::regclass)",
    )
  })

  it('D82: the ownership abort prints REASSIGN OWNED for an administrator', () => {
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader owns objects it must not own: %. Fix: REASSIGN OWNED BY % TO CURRENT_USER; -- run as an administrator', leaks, quote_ident('redacted_reader');`,
    )
  })

  const catalogCheck = check("SELECT string_agg(o.object, ', '", 'beyond their initial privileges')

  it('D81: refuses privileges of the role or PUBLIC beyond the initial ones in pg_catalog, information_schema and pg_toast, columns included', () => {
    expect(catalogCheck).toContain(
      "WHERE n.nspname IN ('pg_catalog', 'information_schema', 'pg_toast') AND x.grantee IN (0, r.oid)",
    )
    expect(catalogCheck).toContain(
      "(SELECT ip.initprivs FROM pg_init_privs ip WHERE ip.classoid = 'pg_class'::regclass AND ip.objoid = c.oid AND ip.objsubid = att.attnum)",
    )
    expect(catalogCheck).toContain(
      "(SELECT ip.initprivs FROM pg_init_privs ip WHERE ip.classoid = 'pg_proc'::regclass AND ip.objoid = p.oid AND ip.objsubid = 0), acldefault('f', p.proowner))",
    )
    expect(catalogCheck).toContain(
      'WHERE b.grantee IN (x.grantee, 0) AND b.privilege_type = x.privilege_type)',
    )
  })

  it('A63, D81: refuses privileges beyond the initial ones on the pg_catalog, information_schema and pg_toast schemas themselves', () => {
    expect(catalogCheck).toContain(
      "UNION ALL SELECT format('%I', n.nspname), format('SCHEMA %I', n.nspname), a.privilege_type, a.grantee, a.grantor, n.nspowner",
    )
    expect(catalogCheck).toContain(
      "CASE WHEN n.nspname = 'information_schema' THEN acldefault('n', n.nspowner) || makeaclitem(0, n.nspowner, 'USAGE', false) ELSE acldefault('n', n.nspowner) END",
    )
  })

  it("D81: information_schema's public views count PUBLIC SELECT as initial, its internal _pg_ views do not", () => {
    expect(catalogCheck).toContain(
      "CASE WHEN n.nspname = 'information_schema' AND c.relname NOT LIKE '\\_pg\\_%' THEN acldefault('r', c.relowner) || makeaclitem(0, c.relowner, 'SELECT', false) ELSE acldefault('r', c.relowner) END",
    )
  })

  it('A69, D81, D89: the catalog fix revokes exactly the extra privileges, as each grantor that is not the owner, the reader first', () => {
    expect(catalogCheck).not.toContain('FILTER')
    expect(catalogCheck).toContain(
      'string_agg(e.privilege, \', \' ORDER BY e.privilege COLLATE "C") AS privileges, bool_or(e.lost) AS lost',
    )
    expect(catalogCheck).toContain(
      "format('REVOKE %s ON %s FROM %s CASCADE;', p.privileges, p.target, CASE WHEN p.grantee = 0 THEN 'PUBLIC' ELSE quote_ident(p.rolname) END)",
    )
    expect(catalogCheck).toContain(
      "CASE WHEN p.grantor <> p.owner THEN format('SET ROLE %s; ', p.grantor::regrole) END",
    )
    expect(catalogCheck).toContain(
      "' ' ORDER BY f.grantor <> f.reader, f.grantee, f.grantor) AS fix",
    )
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader has privileges on system catalog objects beyond their initial privileges: %. Fix: %', leaks, fixes;`,
    )
  })

  it('A69, D89: a column grant the reader passed on in the catalog after losing its grant option is revoked after giving the option back', () => {
    expect(catalogCheck).toContain(
      "x.col IS NOT NULL AND x.grantor = r.oid AND NOT has_column_privilege(r.oid, c.oid, x.col, x.privilege_type || ' WITH GRANT OPTION') AS lost",
    )
    expect(catalogCheck).toContain(
      "CASE WHEN p.lost THEN format('GRANT %s ON %s TO %I WITH GRANT OPTION; ', p.privileges, p.target, p.rolname) END",
    )
    expect(catalogCheck).toContain(
      "CASE WHEN p.lost THEN format(' REVOKE %s ON %s FROM %I CASCADE;', p.privileges, p.target, p.rolname) END",
    )
  })

  it('D76: refuses CREATE on the current database', () => {
    expect(sql).toContain("AND has_database_privilege(r.oid, d.oid, 'CREATE');")
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader can create schemas in database %. Fix: %', leaks, fixes;`,
    )
  })

  it('A61, A70, D90: refuses lo_compat_privileges from the server configuration or command line and from every role or database setting that reaches the reader', () => {
    expect(sql).toContain(
      "FROM pg_settings s WHERE s.name = 'lo_compat_privileges' AND s.setting = 'on' AND s.source IN ('configuration file', 'command line')",
    )
    expect(sql).toContain(
      'WHERE s.setrole IN (0, r.oid) AND s.setdatabase IN (0, (SELECT d.oid FROM pg_database d WHERE d.datname = current_database()))',
    )
    expect(sql).toContain(
      "AND EXISTS (SELECT 1 FROM unnest(s.setconfig) cfg WHERE cfg ~* '^lo_compat_privileges=(on|t|tr|tru|true|y|ye|yes|1)$')",
    )
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: lo_compat_privileges is on, which turns off privilege checks on large objects for role redacted_reader: %. Fix: %', leaks, fixes;`,
    )
  })

  it('A70, D90: a server setting is refused only when no role or database setting that reaches the reader overrides it', () => {
    expect(sql).toContain(
      "AND NOT EXISTS (SELECT 1 FROM pg_db_role_setting o CROSS JOIN LATERAL unnest(o.setconfig) cfg WHERE o.setrole IN (0, r.oid) AND o.setdatabase IN (0, (SELECT d.oid FROM pg_database d WHERE d.datname = current_database())) AND cfg ~* '^lo_compat_privileges=')",
    )
  })

  it('A70, D90: the lo_compat_privileges fix resets it where it is set, and turns it off for the reader when the server command line sets it', () => {
    expect(sql).toContain(
      "CASE s.source WHEN 'command line' THEN 'the server command line' ELSE 'the server configuration' END",
    )
    expect(sql).toContain(
      "CASE s.source WHEN 'command line' THEN format('ALTER ROLE %I SET lo_compat_privileges = off;', r.rolname) ELSE 'ALTER SYSTEM SET lo_compat_privileges = off; SELECT pg_reload_conf();' END",
    )
    expect(sql).toContain(
      "format('ALTER %s RESET lo_compat_privileges;', CASE WHEN s.setdatabase = 0 AND s.setrole = 0 THEN 'ROLE ALL' WHEN s.setdatabase = 0 THEN format('ROLE %I', r.rolname) WHEN s.setrole = 0 THEN format('DATABASE %I', current_database()) ELSE format('ROLE %I IN DATABASE %I', r.rolname, current_database()) END)",
    )
    expect(sql).toContain("|| ' -- run as a superuser'")
  })

  it("D90: refuses ACL entries for the role or PUBLIC on other roles' large objects", () => {
    expect(sql).toContain('FROM pg_largeobject_metadata l CROSS JOIN pg_roles r')
    expect(sql).toContain('AND l.lomowner <> r.oid')
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader can read large objects it does not own: %. Fix: %', leaks, fixes;`,
    )
  })

  const defaultsCheck = check(
    "string_agg(format('%s created by %I%s'",
    'objects created later (default privileges)',
  )

  it('A65, D91: refuses default privileges for the role on anything, and for PUBLIC on tables, sequences, schemas and large objects', () => {
    expect(defaultsCheck).toContain('FROM pg_default_acl d')
    expect(defaultsCheck).toContain(
      "WHERE a.grantee = r.oid OR (a.grantee = 0 AND d.defaclobjtype IN ('r', 'S', 'n', 'L')))",
    )
    expect(defaultsCheck).toContain(
      "CASE WHEN d.defaclobjtype IN ('r', 'S', 'n', 'L') AND EXISTS (SELECT 1 FROM aclexplode(d.defaclacl) a WHERE a.grantee = 0) THEN 'PUBLIC' END",
    )
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader gets privileges on objects created later (default privileges): %. Fix: %', leaks, fixes;`,
    )
  })

  it("A71, D91: ignores the reader's own default privileges, which reach only objects it can create", () => {
    expect(defaultsCheck).toContain(
      "  WHERE r.rolname = 'redacted_reader' AND d.defaclrole <> r.oid\n",
    )
  })

  it('D91: the fix is ALTER DEFAULT PRIVILEGES … REVOKE ALL, IN SCHEMA only for per-schema defaults, for every object type', () => {
    expect(defaultsCheck).toContain(
      "format('ALTER DEFAULT PRIVILEGES FOR ROLE %I%s REVOKE ALL ON %s FROM %s;', o.rolname, CASE WHEN d.defaclnamespace <> 0 THEN format(' IN SCHEMA %I', dn.nspname) END, ",
    )
    expect(defaultsCheck).toContain(
      "CASE d.defaclobjtype WHEN 'r' THEN 'TABLES' WHEN 'S' THEN 'SEQUENCES' WHEN 'f' THEN 'FUNCTIONS' WHEN 'T' THEN 'TYPES' WHEN 'n' THEN 'SCHEMAS' WHEN 'L' THEN 'LARGE OBJECTS' END",
    )
  })

  it('D49, D82, D89, D76, D81, D80, D13, D91, D24, D90: the final check runs in a fixed order', () => {
    const order = [
      'has attributes it must not have',
      'owns objects it must not own',
      'must not be a member of other roles',
      'can create schemas in database',
      'beyond their initial privileges',
      'can read relations outside schema',
      'can use foreign servers',
      'can execute SECURITY DEFINER functions',
      'can read sequences',
      // Before the schema check: the script creates the views schema under these defaults.
      'objects created later (default privileges)',
      'can create objects in schemas',
      'lo_compat_privileges is on',
      'can read large objects it does not own',
    ].map((message) => sql.indexOf(message))
    expect(order.every((position) => position > 0)).toBe(true)
    expect(order).toEqual([...order].sort((a, b) => a - b))
  })

  it('D89: every abort of the final check prints a fix', () => {
    const aborts = finalCheckBlock.split('\n').filter((line) => line.includes('RAISE EXCEPTION'))
    expect(aborts).toHaveLength(13)
    for (const abort of aborts) expect(abort).toMatch(/\. Fix: \S/)
  })

  it('D54: is branded hyde-db', () => {
    expect(sql.split('\n')[0]).toBe(
      '-- GENERATED by hyde-db from schema.prisma. Do not edit by hand.',
    )
    expect(sql).toContain(
      `COMMENT ON SCHEMA "redacted" IS 'Generated by hyde-db. Read-only views with sensitive columns removed. Recreated on every deploy.';`,
    )
    expect(sql).not.toContain('prisma-ai-views')
  })

  it('D11: guards the DROP SCHEMA with the marker check', () => {
    const guard = sql.indexOf("IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'redacted'")
    expect(guard).toBeGreaterThan(0)
    expect(guard).toBeLessThan(sql.indexOf('DROP SCHEMA IF EXISTS "redacted" CASCADE;'))
  })

  it('D58: the marker check accepts only the exact marker or the marker followed by a period', () => {
    expect(sql).toContain(
      "AND NOT (coalesce(obj_description(oid, 'pg_namespace'), '') = 'Generated by hyde-db'\n" +
        "                      OR starts_with(coalesce(obj_description(oid, 'pg_namespace'), ''), 'Generated by hyde-db.'))) THEN",
    )
    expect(sql).not.toContain("''), 'Generated by hyde-db')")
  })

  it('D11: the marker guard checks the configured schema', () => {
    const custom = renderApplySql({ config: { ...config, schema: 'safe' }, views: [] })
    expect(custom).toContain("IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'safe'")
    expect(custom).toContain('hyde-db: schema safe exists but was not created by hyde-db')
    expect(custom).not.toContain("'redacted'")
  })

  it('D13: aborts on executable SECURITY DEFINER functions and readable sequences', () => {
    expect(sql).toContain('    AND p.prosecdef')
    expect(sql).toContain(
      "CASE WHEN c.relkind = 'S' THEN has_sequence_privilege(r.oid, c.oid, 'SELECT, USAGE, UPDATE') ELSE false END",
    )
  })

  it('D13: names the role in the fix when it owns the function or sequence', () => {
    expect(sql).toContain('r.oid = p.proowner')
    expect(sql).toContain('r.oid = c.relowner')
  })

  it('D24: aborts when the role can create objects in any schema', () => {
    expect(sql).toContain("AND has_schema_privilege(r.oid, n.oid, 'CREATE');")
  })

  it('D24: names the role in the fix when it owns the schema', () => {
    expect(sql).toContain('r.oid = n.nspowner')
  })

  /** The CREATE check of the final DO block, from its query to its abort. */
  const createCheck = check(
    "SELECT string_agg(format('%I', n.nspname)",
    'can create objects in schemas',
  )

  it('D24: names the role in the fix when it holds CREATE directly', () => {
    expect(createCheck).toContain(
      "EXISTS (SELECT 1 FROM aclexplode(n.nspacl) a WHERE a.privilege_type IN ('CREATE') AND a.grantee = r.oid AND a.grantor = n.nspowner)",
    )
  })

  it("D24: ignores only the applying session's own temporary schema", () => {
    expect(createCheck).toContain('    AND n.oid <> pg_my_temp_schema()\n')
    expect(createCheck).not.toContain('temp\\_')
  })

  /** The final safety check's DO block. */
  const finalCheck = sql.slice(sql.lastIndexOf('DO $$'))

  it('D49: refuses elevated role attributes instead of resetting them', () => {
    expect(sql).not.toContain('NOSUPERUSER NOCREATEDB')
    expect(sql).not.toMatch(/^ALTER ROLE "redacted_reader" NO/m)
    for (const column of [
      'rolsuper',
      'rolcreatedb',
      'rolcreaterole',
      'rolreplication',
      'rolbypassrls',
    ]) {
      expect(finalCheck).toContain(`CASE WHEN r.${column} THEN`)
    }
    expect(finalCheck).toContain("FROM pg_roles r\n  WHERE r.rolname = 'redacted_reader';")
    expect(finalCheck).toContain("format('ALTER ROLE %I %s;', r.rolname, concat_ws(' ', ")
    expect(finalCheck).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader has attributes it must not have: %. Fix: %', leaks, fixes;`,
    )
  })

  it('D49: checks the role attributes before anything a superuser would trip', () => {
    const attributes = finalCheck.indexOf('has attributes it must not have')
    expect(attributes).toBeGreaterThan(0)
    expect(attributes).toBeLessThan(finalCheck.indexOf('has_table_privilege'))
  })

  it('uses the configured schema, role and timeout everywhere', () => {
    const custom = renderApplySql({
      config: {
        ...config,
        schema: 'safe',
        role: 'safe_reader',
        sourceSchema: 'app',
        statementTimeout: '5s',
      },
      views: [],
    })
    expect(custom).toContain('CREATE SCHEMA "safe";')
    expect(custom).toContain(`ALTER ROLE "safe_reader" SET statement_timeout = '5s';`)
    expect(custom).toContain('role safe_reader can read relations outside schema safe: %. Fix: %')
    // Without views the source schema is not referenced at all (D69).
    expect(custom).not.toMatch(/["']app["']/)
    expect(custom).not.toMatch(/"redacted"|redacted_reader/)
  })
})
