import { describe, expect, it } from 'vitest'
import { BRAND } from '../../src/brand.ts'
import { renderApplySql } from '../../src/render/apply-sql.ts'
import { config, orders, users } from '../helpers/views.ts'

describe('apply SQL', () => {
  const sql = renderApplySql({ config, views: [users, orders] })

  it('is generated by the product and marks the schema it creates', () => {
    expect(sql.split('\n')[0]).toBe(
      `-- GENERATED by ${BRAND} from schema.prisma. Do not edit by hand.`,
    )
    expect(sql).toContain(
      `COMMENT ON SCHEMA "redacted" IS 'Generated by ${BRAND}. Read-only views with sensitive columns removed.`,
    )
  })

  it('runs as one transaction and creates the role only when missing', () => {
    expect(sql).toContain('SET client_min_messages = warning;\nBEGIN;\n')
    expect(sql).toContain(
      "IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'redacted_reader') THEN",
    )
    expect(sql).toContain('CREATE ROLE "redacted_reader" NOLOGIN;')
    expect(sql.trimEnd().endsWith('COMMIT;')).toBe(true)
  })

  it('creates one view per input with exactly its columns, quoting identifiers', () => {
    expect(sql).toContain(
      'CREATE VIEW "redacted"."users" AS SELECT\n  "id",\n  "country"\nFROM "public"."users";',
    )
    expect(sql).toContain(
      'CREATE VIEW "redacted"."orders" AS SELECT\n  "id",\n  "user_id"\nFROM "sales"."Order Items";',
    )
  })

  it('escapes doc comments as string literals', () => {
    expect(sql).toContain(`COMMENT ON VIEW "redacted"."users" IS 'A customer''s account.';`)
    expect(sql).toContain(`COMMENT ON COLUMN "redacted"."users"."country" IS 'ISO | code';`)
    expect(sql).not.toContain('COMMENT ON VIEW "redacted"."orders"')
  })

  it('grants nothing but USAGE and SELECT in the redacted schema and sets session defaults', () => {
    expect(sql).toContain('GRANT USAGE ON SCHEMA "redacted" TO "redacted_reader";')
    expect(sql).toContain('GRANT SELECT ON ALL TABLES IN SCHEMA "redacted" TO "redacted_reader";')
    expect(sql).toContain('ALTER ROLE "redacted_reader" SET default_transaction_read_only = on;')
    expect(sql).toContain(`ALTER ROLE "redacted_reader" SET statement_timeout = '15s';`)
    expect(sql).toContain('ALTER ROLE "redacted_reader" SET search_path = "redacted";')
  })

  it('D69: does not revoke anything in the source schema itself', () => {
    expect(sql).not.toContain('REVOKE ALL ON SCHEMA')
    expect(sql).not.toContain('REVOKE ALL ON ALL TABLES IN SCHEMA')
    expect(sql).not.toMatch(/^REVOKE /m)
  })

  /** The part of the final DO block from the first occurrence of `from` to the abort message `to`. */
  function check(from: string, to: string): string {
    const end = sql.indexOf(to)
    return sql.slice(sql.lastIndexOf(from, end), end)
  }

  const relationCheck = check(
    "string_agg(format('%I.%I', n.nspname, c.relname)",
    'can read relations outside schema',
  )

  it('keeps the base relation check on tables, views, materialized views and foreign tables', () => {
    expect(relationCheck).toContain("AND c.relkind IN ('r', 'p', 'v', 'm', 'f')")
    expect(relationCheck).toContain(
      "AND n.nspname NOT IN ('redacted', 'pg_catalog', 'information_schema')",
    )
  })

  it('D70: the relation check refuses any table or column privilege, but not MAINTAIN', () => {
    expect(relationCheck).toContain(
      "AND (has_table_privilege(r.oid, c.oid, 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER')\n" +
        "         OR has_any_column_privilege(r.oid, c.oid, 'SELECT, INSERT, UPDATE, REFERENCES'));",
    )
    expect(sql).not.toContain('MAINTAIN')
  })

  it('D70: the relation abort prints one REVOKE ALL … CASCADE per relation, in schema and relation order', () => {
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader can read relations outside schema redacted: %. Fix: %', leaks, fixes;`,
    )
    expect(relationCheck).toContain(
      "string_agg(format('%I.%I', n.nspname, c.relname), ', ' ORDER BY n.nspname, c.relname),\n" +
        "         string_agg(format('REVOKE ALL ON %s FROM %s CASCADE;', format('%I.%I', n.nspname, c.relname), ",
    )
    expect(relationCheck).toMatch(/\), ' ' ORDER BY n\.nspname, c\.relname\)\n/)
    expect(sql).not.toContain('REVOKE SELECT')
    expect(sql).not.toContain('ORDER BY 1)')
  })

  it('D70: the relation fix names PUBLIC and the owning or directly granted role for any privilege, columns included', () => {
    expect(relationCheck).toContain(
      "CASE WHEN (has_table_privilege('public', c.oid, 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER') OR has_any_column_privilege('public', c.oid, 'SELECT, INSERT, UPDATE, REFERENCES')) THEN 'PUBLIC' END",
    )
    expect(relationCheck).toContain(
      "CASE WHEN r.oid = c.relowner OR EXISTS (SELECT 1 FROM aclexplode(c.relacl || ARRAY(SELECT unnest(att.attacl) FROM pg_attribute att WHERE att.attrelid = c.oid AND att.attnum > 0 AND NOT att.attisdropped)) a WHERE a.grantee = r.oid AND a.privilege_type IN ('SELECT', 'INSERT', 'UPDATE', 'DELETE', 'TRUNCATE', 'REFERENCES', 'TRIGGER')) THEN quote_ident(r.rolname) END",
    )
  })

  const membershipCheck = check(
    "string_agg(format('%I', g.rolname)",
    'must not be a member of other roles',
  )

  it('D70: the membership abort names each group and prints a REVOKE per membership, GRANTED BY its grantor on PostgreSQL 16+', () => {
    expect(membershipCheck).toContain(
      "string_agg(format('%I', g.rolname), ', ' ORDER BY g.rolname),\n" +
        "         string_agg((SELECT string_agg(format('REVOKE %I FROM %I%s;', g.rolname, r.rolname, CASE WHEN current_setting('server_version_num')::int >= 160000 THEN format(' GRANTED BY %s', m.grantor::regrole) END), ' ' ORDER BY m.grantor) FROM pg_auth_members m WHERE m.roleid = g.oid AND m.member = r.oid), ' ' ORDER BY g.rolname)",
    )
    expect(membershipCheck).toContain(
      'AND EXISTS (SELECT 1 FROM pg_auth_members m WHERE m.roleid = g.oid AND m.member = r.oid);',
    )
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader must not be a member of other roles: %. Fix: %', leaks, fixes;`,
    )
  })

  const ownershipCheck = check("string_agg(owned.name, ', '", 'owns objects it must not own')

  it('D71: the ownership abort lists the database, schemas, relations and functions the role owns', () => {
    expect(ownershipCheck).toContain(
      "SELECT 1, format('database %I', d.datname) FROM pg_database d WHERE d.datname = current_database() AND d.datdba = r.oid",
    )
    expect(ownershipCheck).toContain(
      "SELECT 2, format('schema %I', n.nspname) FROM pg_namespace n WHERE n.nspowner = r.oid",
    )
    expect(ownershipCheck).toContain(
      "WHERE c.relowner = r.oid AND c.relkind IN ('r', 'p', 'v', 'm', 'f', 'S')",
    )
    expect(ownershipCheck).toContain('WHERE p.proowner = r.oid')
    expect(ownershipCheck).toContain('ORDER BY owned.kind, owned.name COLLATE "C"')
  })

  it("D71: the ownership abort leaves out system schemas, which hold the role's own temporary tables", () => {
    expect(ownershipCheck.match(/AND n\.nspname NOT LIKE 'pg\\_%'/g)).toHaveLength(3)
  })

  it('D71: the ownership abort prints REASSIGN OWNED', () => {
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader owns objects it must not own: %. Fix: REASSIGN OWNED BY % TO CURRENT_USER;', leaks, quote_ident('redacted_reader');`,
    )
  })

  const defaultsCheck = check(
    "string_agg(format('%s created by %I%s'",
    'objects created later (default privileges)',
  )

  it('D72: refuses default privileges for the role on anything, and for PUBLIC on tables and sequences', () => {
    expect(defaultsCheck).toContain('FROM pg_default_acl d')
    expect(defaultsCheck).toContain(
      "WHERE a.grantee = r.oid OR (a.grantee = 0 AND d.defaclobjtype IN ('r', 'S')))",
    )
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader gets privileges on objects created later (default privileges): %. Fix: %', leaks, fixes;`,
    )
  })

  it('D72: the fix is ALTER DEFAULT PRIVILEGES … REVOKE ALL, IN SCHEMA only for per-schema defaults, for every object type', () => {
    expect(defaultsCheck).toContain(
      "format('ALTER DEFAULT PRIVILEGES FOR ROLE %I%s REVOKE ALL ON %s FROM %s;', o.rolname, CASE WHEN d.defaclnamespace <> 0 THEN format(' IN SCHEMA %I', dn.nspname) END, ",
    )
    expect(defaultsCheck).toContain(
      "CASE d.defaclobjtype WHEN 'r' THEN 'TABLES' WHEN 'S' THEN 'SEQUENCES' WHEN 'f' THEN 'FUNCTIONS' WHEN 'T' THEN 'TYPES' WHEN 'n' THEN 'SCHEMAS' WHEN 'L' THEN 'LARGE OBJECTS' END",
    )
    expect(defaultsCheck).toContain(
      "CASE WHEN d.defaclobjtype IN ('r', 'S') AND EXISTS (SELECT 1 FROM aclexplode(d.defaclacl) a WHERE a.grantee = 0) THEN 'PUBLIC' END",
    )
  })

  it('D49, D71, D70, D13, D24, D72: the final check runs attributes, ownership, membership, relations, functions, sequences, CREATE, then default privileges', () => {
    const order = [
      'has attributes it must not have',
      'owns objects it must not own',
      'must not be a member of other roles',
      'can read relations outside schema',
      'can execute SECURITY DEFINER functions',
      'can read sequences',
      'can create objects in schemas',
      'objects created later (default privileges)',
    ].map((message) => sql.indexOf(message))
    expect(order.every((position) => position > 0)).toBe(true)
    expect(order).toEqual([...order].sort((a, b) => a - b))
  })

  it('D54: is branded hyde-db', () => {
    expect(sql.split('\n')[0]).toBe(
      '-- GENERATED by hyde-db from schema.prisma. Do not edit by hand.',
    )
    expect(sql).toContain(
      `COMMENT ON SCHEMA "redacted" IS 'Generated by hyde-db. Read-only views with sensitive columns removed. Recreated on every deploy.';`,
    )
    expect(sql).not.toContain('prisma-ai-views')
  })

  it('D11: guards the DROP SCHEMA with the marker check', () => {
    const guard = sql.indexOf("IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'redacted'")
    expect(guard).toBeGreaterThan(0)
    expect(guard).toBeLessThan(sql.indexOf('DROP SCHEMA IF EXISTS "redacted" CASCADE;'))
  })

  it('D58: the marker check accepts only the exact marker or the marker followed by a period', () => {
    expect(sql).toContain(
      "AND NOT (coalesce(obj_description(oid, 'pg_namespace'), '') = 'Generated by hyde-db'\n" +
        "                      OR starts_with(coalesce(obj_description(oid, 'pg_namespace'), ''), 'Generated by hyde-db.'))) THEN",
    )
    expect(sql).not.toContain("''), 'Generated by hyde-db')")
  })

  it('D11: the marker guard checks the configured schema', () => {
    const custom = renderApplySql({ config: { ...config, schema: 'safe' }, views: [] })
    expect(custom).toContain("IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'safe'")
    expect(custom).toContain('hyde-db: schema safe exists but was not created by hyde-db')
    expect(custom).not.toContain("'redacted'")
  })

  it('D13: aborts on executable SECURITY DEFINER functions and readable sequences', () => {
    expect(sql).toContain('    AND p.prosecdef')
    expect(sql).toContain('REVOKE EXECUTE ON ROUTINE %s FROM %s;')
    expect(sql).toContain(
      "CASE WHEN c.relkind = 'S' THEN has_sequence_privilege(r.oid, c.oid, 'SELECT, USAGE, UPDATE') ELSE false END",
    )
    expect(sql).toContain('REVOKE ALL ON SEQUENCE %s FROM %s;')
  })

  it('D13: names the role in the fix when it owns the function or sequence', () => {
    expect(sql).toContain('r.oid = p.proowner')
    expect(sql).toContain('r.oid = c.relowner')
  })

  it('D24: aborts when the role can create objects in any schema', () => {
    expect(sql).toContain("AND has_schema_privilege(r.oid, n.oid, 'CREATE');")
    expect(sql).toContain('REVOKE CREATE ON SCHEMA %I FROM %s;')
  })

  it('D24: names the role in the fix when it owns the schema', () => {
    expect(sql).toContain('r.oid = n.nspowner')
  })

  /** The CREATE check of the final DO block, from its fix to its abort. */
  const createCheck = sql.slice(
    sql.indexOf("string_agg(format('REVOKE CREATE ON SCHEMA"),
    sql.indexOf('can create objects in schemas'),
  )

  it('D24: names the role in the fix when it holds CREATE directly', () => {
    expect(createCheck).toContain(
      "EXISTS (SELECT 1 FROM aclexplode(n.nspacl) a WHERE a.grantee = r.oid AND a.privilege_type IN ('CREATE'))",
    )
  })

  it("D24: ignores only the applying session's own temporary schema", () => {
    expect(createCheck).toContain('    AND n.oid <> pg_my_temp_schema()\n')
    expect(createCheck).not.toContain('temp\\_')
  })

  /** The final safety check's DO block. */
  const finalCheck = sql.slice(sql.lastIndexOf('DO $$'))

  it('D49: refuses elevated role attributes instead of resetting them', () => {
    expect(sql).not.toContain('NOSUPERUSER NOCREATEDB')
    expect(sql).not.toMatch(/^ALTER ROLE "redacted_reader" NO/m)
    for (const column of [
      'rolsuper',
      'rolcreatedb',
      'rolcreaterole',
      'rolreplication',
      'rolbypassrls',
    ]) {
      expect(finalCheck).toContain(`CASE WHEN r.${column} THEN`)
    }
    expect(finalCheck).toContain("FROM pg_roles r\n  WHERE r.rolname = 'redacted_reader';")
    expect(finalCheck).toContain("format('ALTER ROLE %I %s;', r.rolname, concat_ws(' ', ")
    expect(finalCheck).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader has attributes it must not have: %. Fix: %', leaks, fixes;`,
    )
  })

  it('D49: checks the role attributes before anything a superuser would trip', () => {
    const attributes = finalCheck.indexOf('has attributes it must not have')
    expect(attributes).toBeGreaterThan(0)
    expect(attributes).toBeLessThan(finalCheck.indexOf('has_table_privilege'))
  })

  it('uses the configured schema, role and timeout everywhere', () => {
    const custom = renderApplySql({
      config: {
        ...config,
        schema: 'safe',
        role: 'safe_reader',
        sourceSchema: 'app',
        statementTimeout: '5s',
      },
      views: [],
    })
    expect(custom).toContain('CREATE SCHEMA "safe";')
    expect(custom).toContain(`ALTER ROLE "safe_reader" SET statement_timeout = '5s';`)
    expect(custom).toContain('role safe_reader can read relations outside schema safe: %. Fix: %')
    // Without views the source schema is not referenced at all (D69).
    expect(custom).not.toMatch(/["']app["']/)
    expect(custom).not.toMatch(/"redacted"|redacted_reader/)
  })
})
