import { describe, expect, it } from 'vitest'
import { BRAND } from '../../src/brand.ts'
import { renderDropSql } from '../../src/render/drop-sql.ts'
import { config } from '../helpers/views.ts'

describe('drop SQL', () => {
  const sql = renderDropSql({ config })

  it('drops the AI schema and nothing else', () => {
    expect(sql.endsWith('DROP SCHEMA IF EXISTS "ai" CASCADE;\n')).toBe(true)
    expect(sql.match(/DROP /g)).toHaveLength(1)
  })

  it('says when to run it', () => {
    expect(sql.split('\n')[0]).toBe(
      `-- GENERATED by ${BRAND}. Run BEFORE \`prisma migrate deploy\` so that`,
    )
  })

  it('D54: is branded hyde-db', () => {
    expect(sql).toContain('-- GENERATED by hyde-db.')
    expect(sql).not.toContain('prisma-ai-views')
  })
})
