import { describe, expect, it } from 'vitest'
import { BRAND } from '../../src/brand.ts'
import { renderApplySql } from '../../src/render/apply-sql.ts'
import { config, orders, users } from '../helpers/views.ts'

describe('apply SQL', () => {
  const sql = renderApplySql({ config, views: [users, orders] })

  it('is generated by the product and marks the schema it creates', () => {
    expect(sql.split('\n')[0]).toBe(
      `-- GENERATED by ${BRAND} from schema.prisma. Do not edit by hand.`,
    )
    expect(sql).toContain(
      `COMMENT ON SCHEMA "redacted" IS 'Generated by ${BRAND}. Read-only views with sensitive columns removed.`,
    )
  })

  it('runs as one transaction and creates the role only when missing', () => {
    expect(sql).toContain(
      "\nBEGIN;\nSET LOCAL client_min_messages = warning;\nSET LOCAL lock_timeout = '60s';\n",
    )
    expect(sql).toContain(
      "IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'redacted_reader') THEN",
    )
    expect(sql).toContain('CREATE ROLE "redacted_reader" NOLOGIN;')
    expect(sql.trimEnd().endsWith('COMMIT;')).toBe(true)
  })

  it('creates one view per input with exactly its columns, quoting identifiers', () => {
    expect(sql).toContain(
      'CREATE VIEW "redacted"."users" AS SELECT\n  "id",\n  "country"\nFROM "public"."users";',
    )
    expect(sql).toContain(
      'CREATE VIEW "redacted"."orders" AS SELECT\n  "id",\n  "user_id"\nFROM "sales"."Order Items";',
    )
  })

  it('escapes doc comments as string literals', () => {
    expect(sql).toContain(`COMMENT ON VIEW "redacted"."users" IS 'A customer''s account.';`)
    expect(sql).toContain(`COMMENT ON COLUMN "redacted"."users"."country" IS 'ISO | code';`)
    expect(sql).not.toContain('COMMENT ON VIEW "redacted"."orders"')
  })

  it('grants nothing but USAGE and SELECT in the redacted schema and sets session defaults', () => {
    expect(sql).toContain('GRANT USAGE ON SCHEMA "redacted" TO "redacted_reader";')
    expect(sql).toContain('GRANT SELECT ON ALL TABLES IN SCHEMA "redacted" TO "redacted_reader";')
    expect(sql).toContain('ALTER ROLE "redacted_reader" SET default_transaction_read_only = on;')
    expect(sql).toContain(`ALTER ROLE "redacted_reader" SET statement_timeout = '15s';`)
    expect(sql).toContain('ALTER ROLE "redacted_reader" SET search_path = "redacted";')
  })

  it('A72, A84, D110: sets lock_timeout once, inside the transaction and for it alone, so a lock held by a reader fails the deploy', () => {
    expect(sql.match(/lock_timeout/g)).toHaveLength(1)
    expect(sql).toContain("\nSET LOCAL lock_timeout = '60s';\n")
  })

  it('turns JIT off for its own transaction, which would compile the final check on every deploy', () => {
    expect(sql).toContain("\nSET LOCAL lock_timeout = '60s';\nSET LOCAL jit = off;\n")
    expect(sql.match(/jit/g)).toHaveLength(1)
  })

  it('A84, D131: every session setting is SET LOCAL, right after BEGIN, so none outlives the script', () => {
    const settings = sql.split('\n').filter((line) => /^SET /.test(line))
    expect(settings).toEqual([
      'SET LOCAL client_min_messages = warning;',
      "SET LOCAL lock_timeout = '60s';",
      'SET LOCAL jit = off;',
    ])
    expect(sql).toContain(`\nBEGIN;\n${settings.join('\n')}\n`)
    expect(sql.indexOf('BEGIN;')).toBeLessThan(sql.indexOf('SET '))
  })

  it('D69: does not revoke anything in the source schema itself', () => {
    expect(sql).not.toContain('REVOKE ALL ON SCHEMA')
    expect(sql).not.toContain('REVOKE ALL ON ALL TABLES IN SCHEMA')
    expect(sql).not.toMatch(/^REVOKE /m)
  })

  /** SQL for the fix an abort prints: one transaction when it has several statements (D108). */
  const printed = (superuser: string): string =>
    "concat(CASE WHEN fixes LIKE '%; %' AND fixes NOT LIKE 'ALTER SYSTEM %' THEN 'BEGIN; ' || fixes || ' COMMIT;' ELSE fixes END, " +
    `${superuser})`
  /** The fix of an abort, marked for a superuser when it switches roles (D108). */
  const PRINTED = printed("CASE WHEN fixes LIKE '%SET ROLE %' THEN ' -- run as a superuser' END")
  /** The fix of an abort that revokes as the objects' owners: otherwise marked with `runner` (D134). */
  const OWNERS = printed(
    "CASE WHEN fixes LIKE '%SET ROLE %' THEN ' -- run as a superuser' ELSE runner END",
  )
  /** Who must run a fix revoking as the owners `owner` of the objects found (D134). */
  const runAs = (owner: string): string =>
    `CASE WHEN bool_and(pg_has_role(${owner}, 'USAGE')) IS NOT FALSE THEN NULL WHEN count(DISTINCT ${owner}) = 1 ` +
    `THEN format(' -- run as %s or a superuser', min(${owner})::regrole) ELSE ' -- run as a superuser' END`

  /** The final safety check's DO block, from its header comment to the end of the script. */
  const finalCheckBlock = sql.slice(sql.indexOf('-- Safety check'))

  /** The part of the final DO block from the last occurrence of `from` before the abort message `to`, up to it. */
  function check(from: string, to: string): string {
    const end = sql.indexOf(to)
    return sql.slice(sql.lastIndexOf(from, end), end)
  }

  const relationCheck = check(
    "string_agg(format('%I.%I', n.nspname, c.relname), ', '",
    'can read relations outside schema',
  )

  it('keeps the base relation check on tables, views, materialized views and foreign tables', () => {
    expect(relationCheck).toContain("AND c.relkind IN ('r', 'p', 'v', 'm', 'f')")
    expect(relationCheck).toContain(
      "AND n.nspname NOT IN ('redacted', 'pg_catalog', 'information_schema')",
    )
  })

  it('D108: the relation check refuses any table or column privilege, but not MAINTAIN', () => {
    expect(relationCheck).toContain(
      "AND (has_table_privilege(r.oid, c.oid, 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER')\n" +
        "         OR has_any_column_privilege(r.oid, c.oid, 'SELECT, INSERT, UPDATE, REFERENCES'));",
    )
    expect(sql).not.toContain('MAINTAIN')
  })

  it('D108: the relation abort revokes ALL per relation, in schema and relation order, columns included', () => {
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader can read relations outside schema redacted: %. Fix: %', leaks, ${OWNERS};`,
    )
    expect(relationCheck).toContain("format('ALL ON %s', format('%I.%I', n.nspname, c.relname))")
    // A NULL ACL stands for the default one, so the merged ACL is never an empty array (A88).
    expect(relationCheck).toContain(
      "aclexplode(coalesce(c.relacl, acldefault('r', c.relowner)) || ARRAY(SELECT unnest(att.attacl) FROM pg_attribute att WHERE att.attrelid = c.oid AND att.attnum > 0 AND NOT att.attisdropped))",
    )
    expect(relationCheck).toMatch(/\), ' ' ORDER BY n\.nspname, c\.relname\),\n/)
    expect(relationCheck).not.toContain('REVOKE SELECT')
    expect(sql).not.toContain('ORDER BY 1)')
  })

  const ROUTINE =
    "format('%I.%I(%s)', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid))"
  /** Objects without columns: owner, ACL, and how fixes name them. */
  const OBJECTS: readonly (readonly [owner: string, acl: string, object: string])[] = [
    ['d.datdba', 'd.datacl', "format('DATABASE %I', d.datname)"],
    ['fs.srvowner', 'fs.srvacl', "format('FOREIGN SERVER %I', fs.srvname)"],
    ['p.proowner', 'p.proacl', `format('ROUTINE %s', ${ROUTINE})`],
    ['n.nspowner', 'n.nspacl', "format('SCHEMA %I', n.nspname)"],
    ['l.lomowner', 'l.lomacl', "format('LARGE OBJECT %s', l.oid)"],
  ]

  it('A91, D127: a fix of objects without columns revokes, as each grantor other than the owner and the reader, exactly the privileges it granted, with CASCADE', () => {
    for (const [owner, acl, object] of OBJECTS) {
      expect(sql).toContain(
        `AND a.grantee IN (0, r.oid) AND a.grantor <> ${owner} AND a.grantor <> r.oid) g`,
      )
      expect(sql).toContain(exactly(object, '', acl).split(' AND x.privilege_type IN (')[0])
    }
    for (const owner of [
      'c.relowner',
      'p.proowner',
      'n.nspowner',
      'd.datdba',
      'l.lomowner',
      'fs.srvowner',
    ]) {
      expect(sql).toContain(`AND a.grantee = 0 AND a.grantor = ${owner})`)
      expect(sql).toContain(`r.oid = ${owner} OR EXISTS (`)
    }
    expect(sql).not.toContain("format('SET ROLE %s; REVOKE %s FROM %s CASCADE; RESET ROLE;'")
    expect(sql).toContain("|| ' CASCADE;')")
    // Every REVOKE on an object ends in CASCADE; ALTER DEFAULT PRIVILEGES revokes no grants.
    expect(sql).not.toMatch(/'REVOKE [^']*FROM %s;'/)
  })

  /** The grantors of a relation or sequence, other than its owner, as relation and sequence fixes list them. */
  const columnGrantors = (privileges: string): string =>
    `FROM (SELECT a.grantor, a.grantee FROM aclexplode(c.relacl) a WHERE a.privilege_type IN (${privileges}) AND a.grantee IN (0, r.oid) AND a.grantor <> c.relowner AND a.grantor <> r.oid ` +
    'UNION SELECT a.grantor, a.grantee FROM pg_attribute att CROSS JOIN LATERAL aclexplode(att.attacl) a WHERE att.attrelid = c.oid AND att.attnum > 0 AND NOT att.attisdropped AND a.grantee IN (0, r.oid) AND a.grantor <> c.relowner) g'
  const TABLE = "'SELECT', 'INSERT', 'UPDATE', 'DELETE', 'TRUNCATE', 'REFERENCES', 'TRIGGER'"
  const SEQUENCE = "'SELECT', 'USAGE', 'UPDATE'"
  const RELATION = "format('%I.%I', n.nspname, c.relname)"

  it('A69, D108: in relation and sequence fixes the reader is a grantor only of column privileges, and its revokes come first', () => {
    expect(relationCheck).toContain(columnGrantors(TABLE))
    expect(sql).toContain(columnGrantors(SEQUENCE))
    expect(sql.match(/' ' ORDER BY t\.grantor <> r\.oid, t\.grantor\)/g)).toHaveLength(2)
  })

  /** The REVOKE of exactly the table privileges a grantor other than the reader granted on `object`. */
  function exactly(object: string, privileges: string, acl = 'c.relacl'): string {
    return (
      `CASE WHEN t.grantor <> r.oid THEN (SELECT format('REVOKE %s ON %s FROM %s CASCADE;', string_agg(DISTINCT x.privilege_type, ', ' ORDER BY x.privilege_type), ${object}, t.grantees) ` +
      `FROM aclexplode(${acl}) x WHERE x.grantor = t.grantor AND x.grantee IN (0, r.oid) AND x.privilege_type IN (${privileges}) HAVING count(*) > 0) END`
    )
  }
  /** The REVOKE, as a grantor, of exactly the column privileges it granted (A87). */
  const onColumns =
    `(SELECT format('REVOKE %s ON %s FROM %s CASCADE;', string_agg(o.item, ', ' ORDER BY o.attnum, o.privilege_type), ${RELATION}, t.grantees) ` +
    "FROM (SELECT DISTINCT att.attnum, x.privilege_type, format('%s (%I)', x.privilege_type, att.attname) AS item FROM pg_attribute att CROSS JOIN LATERAL aclexplode(att.attacl) x " +
    'WHERE att.attrelid = c.oid AND att.attnum > 0 AND NOT att.attisdropped AND x.grantor = t.grantor AND x.grantee IN (0, r.oid)) o HAVING count(*) > 0)'

  it('A87, D127: a grantor revokes exactly the table privileges it granted, then exactly the column privileges it granted', () => {
    expect(relationCheck).toContain(`concat_ws(' ', ${exactly(RELATION, TABLE)}, ${onColumns})`)
    expect(sql).not.toContain('REVOKE ALL (')
  })

  it('A83, A87, D111, D127: a grantor revokes exactly the sequence privileges it granted, then exactly the column privileges', () => {
    expect(sql).toContain(
      `concat_ws(' ', ${exactly(`format('SEQUENCE %s', ${RELATION})`, SEQUENCE)}, ${onColumns})`,
    )
  })

  /** Whether grantor `who` itself holds `privilege` with the grant option in `acl` (A87). */
  const ownOption = (acl: string, who: string, privilege: string): string =>
    `EXISTS (SELECT 1 FROM aclexplode(${acl}) h WHERE h.grantee = ${who} AND h.privilege_type = ${privilege} AND h.is_grantable)`
  /**
   * A role other than `who`, the owner and the reader that `who` has the privileges of, holding
   * `privilege` with the grant option in `acl` (A90), and not a superuser (A92, D130).
   */
  const masking = (acl: string, who: string, privilege: string, owner: string): string =>
    `(SELECT min(h.grantee) FROM aclexplode(${acl}) h WHERE h.privilege_type = ${privilege} AND h.is_grantable AND h.grantee NOT IN (0, ${who}, ${owner}, r.oid) AND pg_has_role(${who}, h.grantee, 'USAGE') ` +
    'AND NOT EXISTS (SELECT 1 FROM pg_roles s WHERE s.oid = h.grantee AND s.rolsuper))'
  /** Pass-ons by `t.grantor` whose grant option it no longer holds itself, each with the role that lends it (A87, A90). */
  function lost(acl: string, owner: string, privileges: string, columns: boolean): string {
    const objectLevel =
      `SELECT 0 AS attnum, x.privilege_type, x.privilege_type AS item, b.lender, EXISTS (SELECT 1 FROM aclexplode(${acl}) h WHERE h.grantee = t.grantor AND h.grantor = b.lender AND h.privilege_type = x.privilege_type) AS held ` +
      `FROM aclexplode(${acl}) x CROSS JOIN LATERAL (SELECT coalesce(${masking(acl, 't.grantor', 'x.privilege_type', owner)}, ${owner}) AS lender) b ` +
      `WHERE t.grantor <> r.oid AND x.grantor = t.grantor AND x.grantee IN (0, r.oid) AND x.privilege_type IN (${privileges}) AND NOT ${ownOption(acl, 't.grantor', 'x.privilege_type')}`
    if (!columns) return objectLevel
    return (
      `${objectLevel} UNION SELECT att.attnum, x.privilege_type, format('%s (%I)', x.privilege_type, att.attname), b.lender, ` +
      'EXISTS (SELECT 1 FROM aclexplode(att.attacl) h WHERE h.grantee = t.grantor AND h.grantor = b.lender AND h.privilege_type = x.privilege_type) ' +
      `FROM pg_attribute att CROSS JOIN LATERAL aclexplode(att.attacl) x CROSS JOIN LATERAL (SELECT coalesce(${masking('att.attacl', 't.grantor', 'x.privilege_type', owner)}, ${owner}) AS lender) b ` +
      `WHERE att.attrelid = c.oid AND att.attnum > 0 AND NOT att.attisdropped AND x.grantor = t.grantor AND x.grantee IN (0, r.oid) AND NOT ${ownOption('c.relacl || att.attacl', 't.grantor', 'x.privilege_type')}`
    )
  }
  /** `sql` run as the lender `k.lender`; the pasting superuser already acts as the owner. */
  const asLender = (owner: string, sql: string): string =>
    `concat(CASE WHEN k.lender <> ${owner} THEN format('SET ROLE %s; ', k.lender::regrole) END, ${sql}, CASE WHEN k.lender <> ${owner} THEN ' RESET ROLE;' END)`
  const items = (filter?: string): string =>
    `string_agg(o.item, ', ' ORDER BY o.attnum, o.privilege_type)${filter ? ` FILTER (WHERE ${filter})` : ''}`
  /** The loans before grantor `grantor` revokes: the exact options it lost, from their lenders. */
  const borrow = (lostSql: string, grantor: string, owner: string, target: string): string =>
    `(SELECT string_agg(${asLender(owner, `format('GRANT %s ON %s TO %s WITH GRANT OPTION;', k.items, ${target}, ${grantor}::regrole)`)}, ' ' ORDER BY k.lender) FROM (SELECT o.lender, ${items()} AS items FROM (${lostSql}) o GROUP BY o.lender) k)`
  /** The column grants from the lender that a table-level REVOKE strips (A90), given back. */
  const restore = (grantor: string, target: string, relation: string): string => {
    const columns = (filter: string): string =>
      `string_agg(format('%s (%I)', h.privilege_type, att.attname), ', ' ORDER BY att.attnum, h.privilege_type) FILTER (WHERE ${filter})`
    return (
      `nullif((SELECT concat_ws(' ', CASE WHEN bool_or(h.is_grantable) THEN format('GRANT %s ON %s TO %s WITH GRANT OPTION;', ${columns('h.is_grantable')}, ${target}, ${grantor}::regrole) END, ` +
      `CASE WHEN bool_or(NOT h.is_grantable) THEN format('GRANT %s ON %s TO %s;', ${columns('NOT h.is_grantable')}, ${target}, ${grantor}::regrole) END) ` +
      `FROM pg_attribute att CROSS JOIN LATERAL aclexplode(att.attacl) h WHERE att.attrelid = ${relation} AND att.attnum > 0 AND NOT att.attisdropped AND h.grantee = ${grantor} AND h.grantor = k.lender AND h.privilege_type = ANY (k.types)), '')`
    )
  }
  /** The loans taken back after grantor `grantor` revoked, keeping what it held from the lender before. */
  const giveBack = (
    lostSql: string,
    grantor: string,
    owner: string,
    target: string,
    relation?: string,
  ): string =>
    `(SELECT string_agg(${asLender(owner, `concat_ws(' ', CASE WHEN k.held IS NOT NULL THEN format('REVOKE GRANT OPTION FOR %s ON %s FROM %s CASCADE;', k.held, ${target}, ${grantor}::regrole) END, CASE WHEN k.unheld IS NOT NULL THEN format('REVOKE %s ON %s FROM %s CASCADE;', k.unheld, ${target}, ${grantor}::regrole) END${relation ? `, ${restore(grantor, target, relation)}` : ''})`)}, ' ' ORDER BY k.lender) ` +
    `FROM (SELECT o.lender, ${items('o.held')} AS held, ${items('NOT o.held')} AS unheld${relation ? ', array_agg(o.privilege_type) FILTER (WHERE o.attnum = 0) AS types' : ''} FROM (${lostSql}) o GROUP BY o.lender) k)`

  it('A87, A90, D127: a relation grantor that lost the option behind a pass-on borrows exactly that option from the role that masks it, else from the owner, and gives it back right after', () => {
    const lostSql = lost('c.relacl', 'c.relowner', TABLE, true)
    expect(relationCheck).toContain(
      `format('%sSET ROLE %s; %s RESET ROLE;%s', ${borrow(lostSql, 't.grantor', 'c.relowner', RELATION)} || ' ', t.grantor::regrole, `,
    )
    expect(relationCheck).toContain(
      `' ' || ${giveBack(lostSql, 't.grantor', 'c.relowner', RELATION, 'c.oid')})`,
    )
    expect(sql).toContain(lost('c.relacl', 'c.relowner', SEQUENCE, true))
    // Options inherited through a role the grantor belongs to do not count (A87).
    expect(sql).not.toContain('has_column_privilege')
  })

  it('A91, D127: a grantor of an object without columns borrows the option it lost in the same way', () => {
    for (const [owner, acl, object] of OBJECTS) {
      const privileges =
        acl === 'l.lomacl'
          ? "'SELECT', 'UPDATE'"
          : acl === 'p.proacl'
            ? "'EXECUTE'"
            : acl === 'fs.srvacl'
              ? "'USAGE'"
              : "'CREATE'"
      const lostSql = lost(acl, owner, privileges, false)
      expect(sql).toContain(`${borrow(lostSql, 't.grantor', owner, object)} || ' '`)
      expect(sql).toContain(`' ' || ${giveBack(lostSql, 't.grantor', owner, object)}`)
    }
  })

  it('A92, D130: no superuser lends a grant option, so every lender choice leaves superusers out', () => {
    const choices =
      sql.match(/SELECT coalesce\(\(SELECT min\(h\.grantee\)[\s\S]*?AS lender\) b/g) ?? []
    expect(choices.length).toBeGreaterThan(2)
    for (const choice of choices) {
      expect(choice).toContain(
        'AND NOT EXISTS (SELECT 1 FROM pg_roles s WHERE s.oid = h.grantee AND s.rolsuper)), ',
      )
    }
  })

  /** Per check whose fix revokes as the owners of the objects found: its abort and the owner column. */
  const OWNER_CHECKS: readonly (readonly [abort: string, owner: string])[] = [
    ['can create schemas in database', 'd.datdba'],
    ['beyond their initial privileges', 'e.owner'],
    ['can read relations outside schema', 'c.relowner'],
    ['can use foreign servers', 'fs.srvowner'],
    ['can execute SECURITY DEFINER functions', 'p.proowner'],
    ['can read sequences', 'c.relowner'],
    ['can create objects in schemas', 'n.nspowner'],
    ['can read large objects it does not own', 'l.lomowner'],
  ]

  it('A95, D134: a fix that revokes as owners the deploying role does not act as names who must run it', () => {
    for (const [abort, owner] of OWNER_CHECKS) {
      const query = sql.slice(
        sql.lastIndexOf('\n  SELECT ', sql.indexOf(abort)),
        sql.indexOf(abort),
      )
      expect(query, abort).toContain(runAs(owner))
      expect(sql, abort).toMatch(
        new RegExp(
          `${abort.replace(/[()]/g, '\\$&')}[^\n]*Fix: %', leaks, ${OWNERS.replace(/[$()*+.?[\\\]^{|}]/g, '\\$&')};`,
        ),
      )
    }
    expect(sql.match(/INTO leaks, fixes, runner/g)).toHaveLength(OWNER_CHECKS.length - 1)
    expect(sql).toContain(`         (SELECT ${runAs('e.owner')} FROM e),\n`)
    expect(sql).toContain('    INTO leaks, runner, fixes;')
    // The other aborts' fixes do not revoke as an owner.
    expect(sql.match(/ELSE runner END/g)).toHaveLength(OWNER_CHECKS.length)
  })

  it('A82, D108, D127: no fix grants or revokes ALL as a grantor', () => {
    expect(sql).not.toContain('GRANT ALL')
    expect(sql).not.toContain("'GRANT ' || ")
    expect(sql).not.toContain('REVOKE ALL (')
  })

  it('D13, D24, D76, D80, D109: definer functions, sequences, schemas, the database, large objects and foreign servers use the same fix', () => {
    expect(sql).toContain("format('EXECUTE ON ROUTINE %s', ")
    expect(sql).toContain('p.proacl IS NULL OR EXISTS (')
    expect(sql).toContain("format('ALL ON SEQUENCE %s', ")
    expect(sql).toContain("format('CREATE ON SCHEMA %I', n.nspname)")
    expect(sql).toContain("format('CREATE ON DATABASE %I', d.datname)")
    expect(sql).toContain("format('ALL ON LARGE OBJECT %s', l.oid)")
    expect(sql).toContain("format('USAGE ON FOREIGN SERVER %I', fs.srvname)")
  })

  it('D80: refuses USAGE on any foreign server', () => {
    expect(sql).toContain('FROM pg_foreign_server fs CROSS JOIN pg_roles r')
    expect(sql).toContain("AND has_server_privilege(r.oid, fs.oid, 'USAGE');")
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader can use foreign servers: %. Fix: %', leaks, ${OWNERS};`,
    )
  })

  const membershipCheck = check(
    "string_agg(format('%I', g.rolname)",
    'must not be a member of other roles',
  )

  it('D108: the membership abort prints a REVOKE … CASCADE per membership, GRANTED BY its grantor on PostgreSQL 16+', () => {
    expect(membershipCheck).toContain(
      "string_agg((SELECT string_agg(format('REVOKE %I FROM %I%s CASCADE;', g.rolname, r.rolname, CASE WHEN current_setting('server_version_num')::int >= 160000 THEN format(' GRANTED BY %s', m.grantor::regrole) END), ' ' ORDER BY m.grantor) FROM pg_auth_members m WHERE m.roleid = g.oid AND m.member = r.oid), ' ' ORDER BY g.rolname)",
    )
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader must not be a member of other roles: %. Fix: %', leaks, ${PRINTED};`,
    )
  })

  const ownershipCheck = check('FROM pg_roles r', 'owns objects it must not own')

  it('D82: the ownership abort lists every object the role owns, from pg_shdepend, by type and qualified name', () => {
    expect(ownershipCheck).toContain(
      "JOIN pg_shdepend s ON s.refclassid = 'pg_authid'::regclass AND s.refobjid = r.oid AND s.deptype = 'o'",
    )
    expect(ownershipCheck).toContain(
      'AND s.dbid IN (0, (SELECT d.oid FROM pg_database d WHERE d.datname = current_database()))',
    )
    expect(ownershipCheck).toContain(
      'CROSS JOIN LATERAL pg_identify_object(s.classid, s.objid, s.objsubid) i',
    )
    expect(sql).toContain(
      'SELECT string_agg(format(\'%s %s\', i.type, i.identity), \', \' ORDER BY i.type COLLATE "C", i.identity COLLATE "C") INTO leaks',
    )
  })

  it("D82: the ownership abort leaves out the role's own temporary objects and large objects, and what REASSIGN OWNED does not move", () => {
    expect(ownershipCheck).toContain("AND coalesce(i.schema, '') !~ '^pg_(toast_)?temp_'")
    expect(ownershipCheck).toContain(
      "AND s.classid NOT IN ('pg_largeobject'::regclass, 'pg_default_acl'::regclass, 'pg_user_mapping'::regclass)",
    )
  })

  it('D82: the ownership abort prints REASSIGN OWNED for an administrator', () => {
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader owns objects it must not own: %. Fix: REASSIGN OWNED BY % TO CURRENT_USER; -- run as an administrator', leaks, quote_ident('redacted_reader');`,
    )
  })

  const catalogCheck = check('  WITH e AS (', 'beyond their initial privileges')

  it('D81: refuses privileges of the role or PUBLIC beyond the initial ones in pg_catalog, information_schema and pg_toast, columns included', () => {
    expect(catalogCheck).toContain(
      "WHERE n.nspname IN ('pg_catalog', 'information_schema', 'pg_toast') AND x.grantee IN (0, r.oid)",
    )
    expect(catalogCheck).toContain(
      "(SELECT ip.initprivs FROM pg_init_privs ip WHERE ip.classoid = 'pg_class'::regclass AND ip.objoid = c.oid AND ip.objsubid = att.attnum)",
    )
    expect(catalogCheck).toContain(
      "(SELECT ip.initprivs FROM pg_init_privs ip WHERE ip.classoid = 'pg_proc'::regclass AND ip.objoid = p.oid AND ip.objsubid = 0), acldefault('f', p.proowner))",
    )
    expect(catalogCheck).toContain(
      'WHERE b.grantee IN (x.grantee, 0) AND b.privilege_type = x.privilege_type)',
    )
  })

  it('A63, D81: refuses privileges beyond the initial ones on the pg_catalog, information_schema and pg_toast schemas themselves', () => {
    expect(catalogCheck).toContain(
      "UNION ALL SELECT format('%I', n.nspname), format('SCHEMA %I', n.nspname), NULL::oid, 0, a.privilege_type, a.privilege_type, a.grantee, a.grantor, n.nspowner, false,",
    )
    expect(catalogCheck).toContain(
      "CASE WHEN n.nspname = 'information_schema' THEN acldefault('n', n.nspowner) || makeaclitem(0, n.nspowner, 'USAGE', false) ELSE acldefault('n', n.nspowner) END",
    )
  })

  it("D81: information_schema's public views count PUBLIC SELECT as initial, its internal _pg_ views do not", () => {
    expect(catalogCheck).toContain(
      "CASE WHEN n.nspname = 'information_schema' AND c.relname NOT LIKE '\\_pg\\_%' THEN acldefault('r', c.relowner) || makeaclitem(0, c.relowner, 'SELECT', false) ELSE acldefault('r', c.relowner) END",
    )
  })

  it('A69, D81, D108: the catalog fix revokes exactly the extra privileges, as each grantor that is not the owner, the reader first and only for column privileges', () => {
    expect(catalogCheck).toContain(
      '  WITH e AS (SELECT ce.object, ce.target, ce.relid, ce.attnum, ce.privilege_type, ce.privilege, ce.grantee, ce.grantor, ce.owner, ce.on_column,',
    )
    expect(catalogCheck).toContain(
      'SELECT (SELECT string_agg(DISTINCT e.object COLLATE "C", \', \' ORDER BY e.object COLLATE "C") FROM e),',
    )
    expect(catalogCheck).toContain(
      "(SELECT string_agg(format('REVOKE %s ON %s FROM %s CASCADE;', q.privileges, g.target, CASE WHEN q.grantee = 0 THEN 'PUBLIC' ELSE quote_ident(g.rolname) END), ' ' ORDER BY q.grantee)",
    )
    expect(catalogCheck).toContain(
      'FROM e WHERE e.object = g.object AND e.grantor = g.grantor AND (e.grantor <> e.reader OR e.on_column) GROUP BY e.grantee) q)',
    )
    expect(catalogCheck).toContain(
      "CASE WHEN g.grantor <> g.owner THEN format('SET ROLE %s; ', g.grantor::regrole) END",
    )
    expect(catalogCheck).toContain(
      '\' \' ORDER BY f.object COLLATE "C", f.grantor <> f.reader, f.grantor) FROM (',
    )
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader has privileges on system catalog objects beyond their initial privileges: %. Fix: %', leaks, ${OWNERS};`,
    )
  })

  it('A69, A87, A90, A91, D127: a catalog grantor that lost the option behind a pass-on borrows exactly that option and gives it back right after its own statements', () => {
    expect(catalogCheck).toContain(
      `ce.grantor <> ce.owner AND NOT ${ownOption('ce.own_acl', 'ce.grantor', 'ce.privilege_type')} AS lost, b.lender,`,
    )
    expect(catalogCheck).toContain(
      `) ce CROSS JOIN LATERAL (SELECT coalesce(${masking('ce.lender_acl', 'ce.grantor', 'ce.privilege_type', 'ce.owner')}, ce.owner) AS lender) b`,
    )
    // A grantor's own option may be on the table or the column; a lender must hold it on the column.
    expect(catalogCheck).toContain('c.relacl || att.attacl, att.attacl FROM pg_attribute att')
    expect(catalogCheck).toContain(
      '        c.relacl AS own_acl, c.relacl AS lender_acl FROM aclexplode(c.relacl) a',
    )
    const lostSql =
      'SELECT e.attnum, e.privilege_type, e.privilege AS item, e.lender, e.held FROM e WHERE e.object = g.object AND e.grantor = g.grantor AND e.lost AND (e.grantor <> e.reader OR e.on_column)'
    expect(catalogCheck).toContain(`${borrow(lostSql, 'g.grantor', 'g.owner', 'g.target')} || ' '`)
    expect(catalogCheck).toContain(
      `' ' || ${giveBack(lostSql, 'g.grantor', 'g.owner', 'g.target', 'g.relid')}`,
    )
  })

  it('D76: refuses CREATE on the current database', () => {
    expect(sql).toContain("AND has_database_privilege(r.oid, d.oid, 'CREATE');")
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader can create schemas in database %. Fix: %', leaks, ${OWNERS};`,
    )
  })

  it('A61, A70, D109: refuses lo_compat_privileges from the server configuration or command line and from every role or database setting that reaches the reader', () => {
    expect(sql).toContain(
      "FROM pg_settings s WHERE s.name = 'lo_compat_privileges' AND s.setting = 'on' AND s.source IN ('configuration file', 'command line')",
    )
    expect(sql).toContain(
      'WHERE s.setrole IN (0, r.oid) AND s.setdatabase IN (0, (SELECT d.oid FROM pg_database d WHERE d.datname = current_database()))',
    )
    expect(sql).toContain(
      "AND EXISTS (SELECT 1 FROM unnest(s.setconfig) cfg WHERE cfg ~* '^lo_compat_privileges=(on|t|tr|tru|true|y|ye|yes|1)$')",
    )
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: lo_compat_privileges is on, which turns off privilege checks on large objects for role redacted_reader: %. Fix: %', leaks, ${printed("' -- run as a superuser'")};`,
    )
  })

  it('A70, D109: a server setting is refused only when no role or database setting that reaches the reader overrides it', () => {
    expect(sql).toContain(
      "AND NOT EXISTS (SELECT 1 FROM pg_db_role_setting o CROSS JOIN LATERAL unnest(o.setconfig) cfg WHERE o.setrole IN (0, r.oid) AND o.setdatabase IN (0, (SELECT d.oid FROM pg_database d WHERE d.datname = current_database())) AND cfg ~* '^lo_compat_privileges=')",
    )
  })

  it('A70, A89, D109, D123: the lo_compat_privileges fix resets it where it is set, and turns it off for the reader when the server command line sets it, giving a non-superuser deployer ADMIN on a reader it re-creates', () => {
    expect(sql).toContain(
      "CASE s.source WHEN 'command line' THEN 'the server command line' ELSE 'the server configuration' END",
    )
    expect(sql).toContain(
      "CASE s.source WHEN 'command line' THEN format('%sALTER ROLE %I SET lo_compat_privileges = off;', CASE WHEN current_setting('hyde_db.created_reader', true) = 'on' THEN format('CREATE ROLE %I NOLOGIN; %s', r.rolname, " +
        "CASE WHEN NOT (SELECT u.rolsuper FROM pg_roles u WHERE u.rolname = current_user) THEN format('GRANT %I TO %I WITH ADMIN OPTION%s; ', r.rolname, current_user, " +
        "CASE WHEN current_setting('server_version_num')::int >= 160000 THEN ', INHERIT FALSE, SET FALSE' END) END) END, r.rolname) " +
        "ELSE 'ALTER SYSTEM SET lo_compat_privileges = off; SELECT pg_reload_conf();' END",
    )
    expect(sql).toContain(
      "format('ALTER %s RESET lo_compat_privileges;', CASE WHEN s.setdatabase = 0 AND s.setrole = 0 THEN 'ROLE ALL' WHEN s.setdatabase = 0 THEN format('ROLE %I', r.rolname) WHEN s.setrole = 0 THEN format('DATABASE %I', current_database()) ELSE format('ROLE %I IN DATABASE %I', r.rolname, current_database()) END)",
    )
    expect(sql).not.toContain("|| ' -- run as a superuser'")
  })

  it('A81, D109: the role creation records that this transaction created the role, for fixes that must create it again', () => {
    expect(sql).toContain(
      `    CREATE ROLE "redacted_reader" NOLOGIN;\n    PERFORM set_config('hyde_db.created_reader', 'on', true);\n  END IF;`,
    )
  })

  /** The parameter check, from its version guard to the end of its IF block. */
  const parameterCheck = sql.slice(
    sql.indexOf("  IF current_setting('server_version_num')::int >= 150000 THEN"),
    sql.indexOf('END $$;', sql.indexOf('-- Safety check')),
  )

  it('A96, D138: refuses SET and ALTER SYSTEM on configuration parameters for the role or PUBLIC, on PostgreSQL 15+ only, through EXECUTE', () => {
    expect(parameterCheck).toMatch(
      /^ {2}IF current_setting\('server_version_num'\)::int >= 150000 THEN\n {4}EXECUTE \$p\$SELECT /,
    )
    expect(parameterCheck).toContain('      FROM pg_parameter_acl pa CROSS JOIN pg_roles r\n')
    expect(parameterCheck).toContain(
      '        AND EXISTS (SELECT 1 FROM aclexplode(pa.paracl) a WHERE a.grantee IN (0, r.oid))$p$\n      INTO leaks, fixes;\n',
    )
    expect(parameterCheck).toContain(
      `      RAISE EXCEPTION '${BRAND}: role redacted_reader has privileges on configuration parameters: %. Fix: %', leaks, ${printed("' -- run as a superuser'")};`,
    )
    expect(parameterCheck).toMatch(/ {4}END IF;\n {2}END IF;\n$/)
    // Nothing else in the script names the catalog PostgreSQL 14 lacks.
    expect(sql.split('pg_parameter_acl')).toHaveLength(2)
  })

  it('A56, D127, D138: the parameter fix revokes exactly the privileges each grantor granted, the bootstrap superuser acting as the owner', () => {
    const owner = '10::oid'
    expect(parameterCheck).toContain(
      `format('%s ON PARAMETER %I', (SELECT string_agg(DISTINCT a.privilege_type, ', ' ORDER BY a.privilege_type) FROM aclexplode(pa.paracl) a WHERE a.grantee IN (0, r.oid) AND a.grantor = ${owner}), pa.parname)`,
    )
    expect(parameterCheck).toContain(
      exactly("format('PARAMETER %I', pa.parname)", "'SET', 'ALTER SYSTEM'", 'pa.paracl'),
    )
    const lostSql = lost('pa.paracl', owner, "'SET', 'ALTER SYSTEM'", false)
    expect(parameterCheck).toContain(
      `${borrow(lostSql, 't.grantor', owner, "format('PARAMETER %I', pa.parname)")} || ' '`,
    )
  })

  it("D109: refuses ACL entries for the role or PUBLIC on other roles' large objects", () => {
    expect(sql).toContain('FROM pg_largeobject_metadata l CROSS JOIN pg_roles r')
    expect(sql).toContain('AND l.lomowner <> r.oid')
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader can read large objects it does not own: %. Fix: %', leaks, ${OWNERS};`,
    )
  })

  const defaultsCheck = check(
    "string_agg(format('%s created by %I%s'",
    'objects created later (default privileges)',
  )

  it('A65, D91: refuses default privileges for the role on anything, and for PUBLIC on tables, sequences, schemas and large objects', () => {
    expect(defaultsCheck).toContain('FROM pg_default_acl d')
    expect(defaultsCheck).toContain(
      "WHERE a.grantee = r.oid OR (a.grantee = 0 AND d.defaclobjtype IN ('r', 'S', 'n', 'L')))",
    )
    expect(defaultsCheck).toContain(
      "CASE WHEN d.defaclobjtype IN ('r', 'S', 'n', 'L') AND EXISTS (SELECT 1 FROM aclexplode(d.defaclacl) a WHERE a.grantee = 0) THEN 'PUBLIC' END",
    )
    expect(sql).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader gets privileges on objects created later (default privileges): %. Fix: %', leaks, ${PRINTED};`,
    )
  })

  it("A71, D91: ignores the reader's own default privileges, which reach only objects it can create", () => {
    expect(defaultsCheck).toContain(
      "  WHERE r.rolname = 'redacted_reader' AND d.defaclrole <> r.oid\n",
    )
  })

  it('D91: the fix is ALTER DEFAULT PRIVILEGES … REVOKE ALL, IN SCHEMA only for per-schema defaults, for every object type', () => {
    expect(defaultsCheck).toContain(
      "format('ALTER DEFAULT PRIVILEGES FOR ROLE %I%s REVOKE ALL ON %s FROM %s;', o.rolname, CASE WHEN d.defaclnamespace <> 0 THEN format(' IN SCHEMA %I', dn.nspname) END, ",
    )
    expect(defaultsCheck).toContain(
      "CASE d.defaclobjtype WHEN 'r' THEN 'TABLES' WHEN 'S' THEN 'SEQUENCES' WHEN 'f' THEN 'FUNCTIONS' WHEN 'T' THEN 'TYPES' WHEN 'n' THEN 'SCHEMAS' WHEN 'L' THEN 'LARGE OBJECTS' END",
    )
  })

  /**
   * The final check's aborts in the order they run, each with words of the line in the header
   * comment that announces it.
   */
  const CHECK_ORDER: readonly (readonly [abort: string, header: string])[] = [
    ['has attributes it must not have', 'has SUPERUSER, CREATEDB'],
    ['owns objects it must not own', 'owns any object in this database'],
    ['must not be a member of other roles', 'is a member of another role'],
    ['can create schemas in database', 'can create schemas in this database'],
    ['beyond their initial privileges', 'holds privileges on pg_catalog'],
    ['can read relations outside schema', 'holds any privilege on a relation outside'],
    ['can use foreign servers', 'or can use a foreign server'],
    ['can execute SECURITY DEFINER functions', 'can execute a SECURITY DEFINER function'],
    ['can read sequences', 'or use a sequence'],
    // Before the schema check: the script creates the views schema under these defaults.
    ['objects created later (default privileges)', 'gains privileges on objects created later'],
    ['can create objects in schemas', 'can create objects in any schema'],
    ['lo_compat_privileges is on', 'has lo_compat_privileges on'],
    ['can read large objects it does not own', 'can read large objects of other roles'],
    ['has privileges on configuration parameters', 'holds SET or ALTER SYSTEM on a configuration'],
  ]

  it('D49, D82, D108, D76, D81, D80, D13, D91, D24, D109, D138: the final check runs in a fixed order', () => {
    const order = CHECK_ORDER.map(([abort]) => sql.indexOf(abort))
    expect(order.every((position) => position > 0)).toBe(true)
    expect(order).toEqual([...order].sort((a, b) => a - b))
  })

  it('the header comment announces the checks in the order they run', () => {
    const header = sql.slice(
      sql.indexOf('-- Safety check'),
      sql.indexOf('DO $$', sql.indexOf('-- Safety check')),
    )
    const order = CHECK_ORDER.map(([, words]) => header.indexOf(words))
    expect(order.every((position) => position > 0)).toBe(true)
    expect(order).toEqual([...order].sort((a, b) => a - b))
  })

  it('D108: every abort of the final check prints a fix, as one transaction when it has several statements', () => {
    const aborts = finalCheckBlock.split('\n').filter((line) => line.includes('RAISE EXCEPTION'))
    expect(aborts).toHaveLength(14)
    for (const abort of aborts) expect(abort).toMatch(/\. Fix: \S/)
    // All but the ownership abort, whose fix is a single statement written into its message.
    expect(
      aborts.filter((abort) => abort.includes("'BEGIN; ' || fixes || ' COMMIT;'")),
    ).toHaveLength(13)
  })

  it('D54: is branded hyde-db', () => {
    expect(sql.split('\n')[0]).toBe(
      '-- GENERATED by hyde-db from schema.prisma. Do not edit by hand.',
    )
    expect(sql).toContain(
      `COMMENT ON SCHEMA "redacted" IS 'Generated by hyde-db. Read-only views with sensitive columns removed. Recreated on every deploy.';`,
    )
    expect(sql).not.toContain('prisma-ai-views')
  })

  it('D11: guards the DROP SCHEMA with the marker check', () => {
    const guard = sql.indexOf("IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'redacted'")
    expect(guard).toBeGreaterThan(0)
    expect(guard).toBeLessThan(sql.indexOf('DROP SCHEMA IF EXISTS "redacted" CASCADE;'))
  })

  /** The guard that refuses to drop objects outside the views schema (D141). */
  const dependentsGuard = sql.slice(
    sql.indexOf('-- Refuse to drop objects outside schema'),
    sql.indexOf('DROP SCHEMA IF EXISTS'),
  )

  it('A97, D141: refuses to drop the views schema while objects outside it depend on its views, naming them', () => {
    expect(dependentsGuard).toMatch(/^-- Refuse to drop objects outside schema redacted/)
    expect(sql.indexOf('refusing to drop it')).toBeLessThan(sql.indexOf(dependentsGuard))
    // Dependents on any relation or type of the schema, by a normal or automatic dependency.
    expect(dependentsGuard).toContain("\n    AND d.deptype IN ('n', 'a')\n")
    expect(dependentsGuard).toContain(
      "d.refclassid = 'pg_class'::regclass AND d.refobjid IN (SELECT c.oid FROM pg_class c WHERE c.relnamespace = s.oid)",
    )
    expect(dependentsGuard).toContain(
      "d.refclassid = 'pg_type'::regclass AND d.refobjid IN (SELECT t.oid FROM pg_type t WHERE t.typnamespace = s.oid)",
    )
    expect(dependentsGuard).toContain(
      `RAISE EXCEPTION '${BRAND}: objects outside schema redacted depend on its views: %; refusing to drop them with the schema. Drop them before the deploy, and create them again after it if you still need them.', dependents;`,
    )
  })

  it("A97, D141: rules, triggers, policies and defaults count in their relation's schema, and a view's rule is named as the view", () => {
    for (const [catalog, alias, relation] of [
      ['pg_rewrite', 'w', 'ev_class'],
      ['pg_trigger', 'tg', 'tgrelid'],
      ['pg_policy', 'po', 'polrelid'],
      ['pg_attrdef', 'ad', 'adrelid'],
    ]) {
      expect(dependentsGuard).toContain(
        `LEFT JOIN ${catalog} ${alias} ON d.classid = '${catalog}'::regclass AND ${alias}.oid = d.objid`,
      )
      expect(dependentsGuard).toContain(`${alias}.${relation}`)
    }
    expect(dependentsGuard).toContain(
      "pg_identify_object(CASE WHEN w.oid IS NULL THEN d.classid ELSE 'pg_class'::regclass END, coalesce(w.ev_class, d.objid), CASE WHEN w.oid IS NULL THEN d.objsubid ELSE 0 END) i",
    )
  })

  it("D141: temporary objects, and objects that depend on one, are left to the schema's drop, so a reader's own cannot block a deploy", () => {
    expect(dependentsGuard).toContain("AND h.schema IS DISTINCT FROM 'redacted'")
    expect(dependentsGuard).toContain("AND coalesce(h.schema, '') !~ '^pg_(toast_)?temp_'")
    expect(dependentsGuard).toContain(
      "AND NOT EXISTS (SELECT 1 FROM pg_depend o CROSS JOIN LATERAL pg_identify_object(o.refclassid, o.refobjid, 0) oi WHERE o.classid = d.classid AND o.objid = d.objid AND oi.schema ~ '^pg_(toast_)?temp_')",
    )
  })

  it('D58: the marker check accepts only the exact marker or the marker followed by a period', () => {
    expect(sql).toContain(
      "AND NOT (coalesce(obj_description(oid, 'pg_namespace'), '') = 'Generated by hyde-db'\n" +
        "                      OR starts_with(coalesce(obj_description(oid, 'pg_namespace'), ''), 'Generated by hyde-db.'))) THEN",
    )
    expect(sql).not.toContain("''), 'Generated by hyde-db')")
  })

  it('D11: the marker guard checks the configured schema', () => {
    const custom = renderApplySql({ config: { ...config, schema: 'safe' }, views: [] })
    expect(custom).toContain("IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'safe'")
    expect(custom).toContain('hyde-db: schema safe exists but was not created by hyde-db')
    expect(custom).not.toContain("'redacted'")
  })

  it('D13: aborts on executable SECURITY DEFINER functions and readable sequences', () => {
    expect(sql).toContain('    AND p.prosecdef')
    expect(sql).toContain(
      "CASE WHEN c.relkind = 'S' THEN has_sequence_privilege(r.oid, c.oid, 'SELECT, USAGE, UPDATE') ELSE false END",
    )
  })

  it('A88, D124: the sequence check ignores temporary schemas, like the relation and ownership checks', () => {
    expect(sql).toContain("    AND c.relkind = 'S'\n    AND n.nspname !~ '^pg_(toast_)?temp_'\n")
  })

  it('A83, D111: the sequence check also refuses column privileges, and the fix reads column grants too', () => {
    expect(sql).toContain(
      "    AND (CASE WHEN c.relkind = 'S' THEN has_sequence_privilege(r.oid, c.oid, 'SELECT, USAGE, UPDATE') ELSE false END\n" +
        "         OR has_any_column_privilege(r.oid, c.oid, 'SELECT'));",
    )
    expect(sql).toContain(
      "'REVOKE ' || format('ALL ON SEQUENCE %s', format('%I.%I', n.nspname, c.relname)) || ' FROM ' || nullif(concat_ws(', ', CASE WHEN EXISTS (SELECT 1 FROM aclexplode(coalesce(c.relacl, acldefault('s', c.relowner)) || ARRAY(SELECT unnest(att.attacl) FROM pg_attribute att WHERE att.attrelid = c.oid AND att.attnum > 0 AND NOT att.attisdropped)) a WHERE a.privilege_type IN ('SELECT', 'USAGE', 'UPDATE')",
    )
  })

  it('D13: names the role in the fix when it owns the function or sequence', () => {
    expect(sql).toContain('r.oid = p.proowner')
    expect(sql).toContain('r.oid = c.relowner')
  })

  it('D24: aborts when the role can create objects in any schema', () => {
    expect(sql).toContain("AND has_schema_privilege(r.oid, n.oid, 'CREATE');")
  })

  it('D24: names the role in the fix when it owns the schema', () => {
    expect(sql).toContain('r.oid = n.nspowner')
  })

  /** The CREATE check of the final DO block, from its query to its abort. */
  const createCheck = check(
    "SELECT string_agg(format('%I', n.nspname)",
    'can create objects in schemas',
  )

  it('D24: names the role in the fix when it holds CREATE directly', () => {
    expect(createCheck).toContain(
      "EXISTS (SELECT 1 FROM aclexplode(n.nspacl) a WHERE a.privilege_type IN ('CREATE') AND a.grantee = r.oid AND a.grantor = n.nspowner)",
    )
  })

  it("D24: ignores only the applying session's own temporary schema", () => {
    expect(createCheck).toContain('    AND n.oid <> pg_my_temp_schema()\n')
    expect(createCheck).not.toContain('temp\\_')
  })

  /** The final safety check's DO block. */
  const finalCheck = sql.slice(sql.lastIndexOf('DO $$'))

  it('D49: refuses elevated role attributes instead of resetting them', () => {
    expect(sql).not.toContain('NOSUPERUSER NOCREATEDB')
    expect(sql).not.toMatch(/^ALTER ROLE "redacted_reader" NO/m)
    for (const column of [
      'rolsuper',
      'rolcreatedb',
      'rolcreaterole',
      'rolreplication',
      'rolbypassrls',
    ]) {
      expect(finalCheck).toContain(`CASE WHEN r.${column} THEN`)
    }
    expect(finalCheck).toContain("FROM pg_roles r\n  WHERE r.rolname = 'redacted_reader';")
    expect(finalCheck).toContain("format('ALTER ROLE %I %s;', r.rolname, concat_ws(' ', ")
    expect(finalCheck).toContain(
      `RAISE EXCEPTION '${BRAND}: role redacted_reader has attributes it must not have: %. Fix: %', leaks, ${PRINTED};`,
    )
  })

  it('D49: checks the role attributes before anything a superuser would trip', () => {
    const attributes = finalCheck.indexOf('has attributes it must not have')
    expect(attributes).toBeGreaterThan(0)
    expect(attributes).toBeLessThan(finalCheck.indexOf('has_table_privilege'))
  })

  it('uses the configured schema, role and timeout everywhere', () => {
    const custom = renderApplySql({
      config: {
        ...config,
        schema: 'safe',
        role: 'safe_reader',
        sourceSchema: 'app',
        statementTimeout: '5s',
      },
      views: [],
    })
    expect(custom).toContain('CREATE SCHEMA "safe";')
    expect(custom).toContain(`ALTER ROLE "safe_reader" SET statement_timeout = '5s';`)
    expect(custom).toContain('role safe_reader can read relations outside schema safe: %. Fix: %')
    // Without views the source schema is not referenced at all (D69).
    expect(custom).not.toMatch(/["']app["']/)
    expect(custom).not.toMatch(/"redacted"|redacted_reader/)
  })
})
