import { describe, expect, it } from 'vitest'
import {
  ABORT_TABLE,
  abortIf,
  abortWhenFound,
  account,
  couldNotRunMessage,
  FIX_LIMIT,
  gated,
  MARKER_FIX,
  MARKER_VIEW,
  MESSAGE_LIMIT,
  markerGuard,
  markerViewSql,
  NO_DATABASE_MESSAGE,
  raiseRefusal,
  refusalMessage,
  renderPrelude,
  renderTeardown,
  SOURCE_FIX,
  UNREADABLE_FIX,
} from '../../src/render/mysql-guards.ts'

const config = {
  dialect: 'mysql',
  schema: 'redacted',
  role: 'redacted_reader',
  readerHost: '%',
  default: 'hidden',
  strict: true,
} as const

describe('mysql script guards', () => {
  it('D117, D160: the prelude pins the session, reports a missing default database before the abort table exists, then creates the table', () => {
    expect(renderPrelude()).toEqual([
      "SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_BACKSLASH_ESCAPES';",
      'SET SESSION lock_wait_timeout = 60;',
      'SET @hyde_refused = NULL;',
      `SET @hyde_refused = IF(DATABASE() IS NULL, '${NO_DATABASE_MESSAGE}', @hyde_refused);`,
      "SET SESSION sql_warnings = IF(@hyde_refused IS NULL, IF(@@SESSION.sql_warnings, 'ON', 'OFF'), @hyde_refused);",
      'DROP TEMPORARY TABLE IF EXISTS `hyde_db_abort`;',
      'CREATE TEMPORARY TABLE `hyde_db_abort` (`problem` INT NOT NULL);',
    ])
  })

  it('D160, D151: the missing-database message has the hyde-db shape and fits 128 characters', () => {
    expect(NO_DATABASE_MESSAGE).toMatch(
      /^hyde-db: .+ Fix: add the database name to the connection URL$/,
    )
    expect(NO_DATABASE_MESSAGE.length).toBeLessThanOrEqual(MESSAGE_LIMIT)
  })

  it('D99: an abort is a failing insert into the temporary table, with no routine and no DELIMITER', () => {
    const sql = abortIf('t', '1 = 1', 'x.', 'y;').join('\n')
    expect(sql).toContain('INSERT INTO `hyde_db_abort`')
    expect(sql).not.toMatch(/DELIMITER|CREATE (PROCEDURE|FUNCTION)|SIGNAL/i)
    expect(ABORT_TABLE).toBe('hyde_db_abort')
    expect(MARKER_VIEW).toBe('hyde_db_marker')
  })

  it('D99, D151: the abort message starts with hyde-db: and the limit is rendered from MESSAGE_LIMIT, the fix kept whole', () => {
    expect(MESSAGE_LIMIT).toBe(128)
    const sql = abortIf('t', '1 = 1', 'p', 'f').join('\n')
    expect(sql).toContain("CONCAT('hyde-db: '")
    expect(sql).toContain(
      `GREATEST(0, ${MESSAGE_LIMIT - 'hyde-db: '.length - ' Fix: '.length} - CHAR_LENGTH(f.fix))`,
    )
    expect(sql).toContain("' Fix: ', f.fix")
  })

  it('D99: abortWhenFound records the first message in the refusal flag and aborts only when a row exists', () => {
    const sql = abortWhenFound('t', 'SELECT 1 AS problem, 2 AS fix').join('\n')
    expect(sql).toContain('FROM (SELECT 1 AS problem, 2 AS fix) f LIMIT 1')
    expect(sql).toContain('SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);')
    expect(sql).toContain('WHERE @hyde_message IS NOT NULL')
  })

  it('D99: abortIf quotes the problem and the fix as literals and fires on the condition', () => {
    const sql = abortIf('t', 'a = 1', "it's", "do 'x'").join('\n')
    expect(sql).toContain("'it''s' AS problem")
    expect(sql).toContain("'do ''x''' AS fix")
    expect(sql).toContain('WHERE a = 1')
  })

  it('Review Focus 1, D155: a gated statement is prepared from a literal and only runs while @hyde_refused is NULL', () => {
    expect(gated("DROP DATABASE `o'x`;").join('\n')).toBe(
      [
        "SET @hyde_sql = IF(@hyde_refused IS NULL, 'DROP DATABASE `o''x`;', 'DO 0');",
        'PREPARE hyde_stmt FROM @hyde_sql;',
        'EXECUTE hyde_stmt;',
        'DEALLOCATE PREPARE hyde_stmt;',
      ].join('\n'),
    )
  })

  it('D115: the marker guard looks for the view hyde_db_marker with a marker column and the marker text, only when the database exists', () => {
    const sql = markerGuard.render(config).join('\n')
    expect(sql).toContain('information_schema.SCHEMATA')
    expect(sql).toContain("'hyde_db_marker'")
    expect(sql).toContain('Generated by hyde-db')
    expect(sql).toContain("'redacted'")
    expect(markerGuard.id).toBe('marker-guard')
  })

  it('D151: with the default schema the marker refusal prints its problem and fix uncut', () => {
    const problem = 'database redacted has no hyde-db marker view.'
    expect(markerGuard.render(config).join('\n')).toContain(
      "CONCAT('database ', 'redacted', ' has no hyde-db marker view.')",
    )
    expect(`hyde-db: ${problem} Fix: ${MARKER_FIX}`.length).toBeLessThanOrEqual(MESSAGE_LIMIT)
  })

  it('D99: the marker guard renders the longest schema name into the check', () => {
    const longer = { ...config, schema: 'a'.repeat(64) }
    expect(markerGuard.render(longer).join('\n')).toContain(`SCHEMA_NAME = '${'a'.repeat(64)}'`)
  })

  it('D155, D166: abortWhenFound emits the could-not-run message, the message query, the flag SET, then the INSERT, in that order', () => {
    // Cut-to-fit and gating at runtime are proven by the MySQL attack suite (Task 13+).
    const lines = abortWhenFound('some-check', 'SELECT 1 AS problem, 2 AS fix')
    expect(lines).toHaveLength(4)
    expect(lines[0]).toBe(`SET @hyde_message = '${couldNotRunMessage('some-check')}';`)
    expect(lines[1]).toMatch(/^SET @hyde_message = \(SELECT CONCAT\(/)
    expect(lines[2]).toBe('SET @hyde_refused = COALESCE(@hyde_refused, @hyde_message);')
    expect(lines[3]).toMatch(/^INSERT INTO `hyde_db_abort`/)
    expect(lines[1]).toContain(`${FIX_LIMIT} - CHAR_LENGTH(f.fix)`)
    expect(FIX_LIMIT).toBe(113)
  })

  it('D166: the could-not-run refusal is a hyde-db message that names the check and fits 128 characters for every check id', () => {
    expect(couldNotRunMessage('marker-guard')).toBe(
      'hyde-db: check marker-guard could not run. Fix: run without --force and read the first error',
    )
    for (const id of [
      'default-database',
      'marker-guard',
      'grant-table-access',
      'reset-reader',
      'roles',
      'mandatory-roles',
      'proxies',
      'other-accounts',
      'recheck',
    ])
      expect(couldNotRunMessage(id).length).toBeLessThanOrEqual(MESSAGE_LIMIT)
  })

  it('D166: refusalMessage is the SET of the first problem-and-fix row and raiseRefusal the flag and insert', () => {
    expect(refusalMessage('SELECT 1 AS problem, 2 AS fix')).toMatch(
      /^SET @hyde_message = \(SELECT CONCAT\(.*FROM \(SELECT 1 AS problem, 2 AS fix\) f LIMIT 1\);$/,
    )
    expect(raiseRefusal()).toHaveLength(2)
  })

  it('D165: the marker guard reads marker and source through the view itself, only after finding the view and both columns', () => {
    const sql = markerGuard.render(config).join('\n')
    expect(sql).toContain(
      'SELECT `marker`, `source` INTO @hyde_marker, @hyde_source FROM `redacted`.`hyde_db_marker`',
    )
    expect(sql).toContain("c.COLUMN_NAME = 'source'")
    expect(sql).not.toContain('VIEW_DEFINITION')
  })

  it('D165: the marker guard refuses a marker that names another source database, fix whole', () => {
    const sql = markerGuard.render(config).join('\n')
    expect(sql).toContain(
      'CONVERT(@hyde_source USING utf8mb4) COLLATE utf8mb4_bin <> CONVERT(DATABASE() USING utf8mb4) COLLATE utf8mb4_bin',
    )
    expect(sql).not.toMatch(/\bBINARY\b/)
    expect(sql).toContain(
      "CONCAT('database ', 'redacted', ' belongs to source database ', @hyde_source, '.')",
    )
    expect(sql).toContain(SOURCE_FIX)
    expect(SOURCE_FIX).toBe('set "schema" to an unused name')
    expect(SOURCE_FIX.length).toBeLessThanOrEqual(FIX_LIMIT)
  })

  it('D169: the marker is read only from a view that information_schema shows as SQL SECURITY DEFINER, so the deployer never runs a view body', () => {
    const sql = markerGuard.render(config).join('\n')
    const set = sql.split('\n').find((l) => l.startsWith('SET @hyde_sql')) ?? ''
    expect(set).toContain("AND SECURITY_TYPE = 'DEFINER'")
    expect(set.indexOf("SECURITY_TYPE = 'DEFINER'")).toBeLessThan(set.indexOf('INTO @hyde_marker'))
  })

  it('D169: a definer-view marker whose read left NULLs is reported as unreadable with a fix naming its definer, within the limits', () => {
    const sql = markerGuard.render(config).join('\n')
    expect(sql).toContain("' cannot be read.'")
    expect(sql).toContain('re-create its definer ')
    expect(sql).toContain(' or drop database ')
    expect(sql).toContain('SELECT DEFINER FROM information_schema.VIEWS')
    expect(sql).toContain(`> ${FIX_LIMIT}, '${UNREADABLE_FIX}'`)
    expect(UNREADABLE_FIX.length).toBeLessThanOrEqual(FIX_LIMIT)
  })

  it('D165: a marker without a source value is treated like a missing marker', () => {
    const sql = markerGuard.render(config).join('\n')
    expect(sql).toContain('@hyde_marker IS NULL OR @hyde_marker <> ')
    expect(sql).toContain('@hyde_source IS NULL')
  })

  it('D165, D155: the marker DDL is built inside the gate from DATABASE(), quoted without backslash escapes', () => {
    const lines = markerViewSql(config)
    expect(lines[0]).toMatch(
      /^SET @hyde_sql = IF\(@hyde_refused IS NULL, CONCAT\('CREATE DEFINER = CURRENT_USER SQL SECURITY DEFINER VIEW `redacted`\.`hyde_db_marker` AS SELECT ''Generated by hyde-db'' AS `marker`, ', /,
    )
    expect(lines[0]).toContain("REPLACE(DATABASE(), '''', '''''')")
    expect(lines[0]).toContain("' AS `source`;'), 'DO 0');")
    expect(lines.slice(1).map((l) => l.split(' ')[0])).toEqual(['PREPARE', 'EXECUTE', 'DEALLOCATE'])
  })

  it('Review Focus 1: gated emits SET, PREPARE, EXECUTE, DEALLOCATE in that order', () => {
    expect(gated('DO 1;').map((l) => l.split(' ')[0])).toEqual([
      'SET',
      'PREPARE',
      'EXECUTE',
      'DEALLOCATE',
    ])
  })

  it('D104: account is the quoted user and host, doubling single quotes', () => {
    expect(account(config)).toBe("'redacted_reader'@'%'")
    expect(account({ role: "o'x", readerHost: "h'y" })).toBe("'o''x'@'h''y'")
  })

  it('D99: the teardown drops the abort table', () => {
    expect(renderTeardown().join('\n')).toBe('DROP TEMPORARY TABLE IF EXISTS `hyde_db_abort`;')
  })
})
