// SECURITY.md is a view of LEDGER.md. It states the same guarantee and non-guarantees as the
// README (D93), word for word where the README states them, plus the private reporting path (D41),
// the supported release (D133) and a hardening checklist; these tests keep the two documents from
// drifting apart.
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import {
  citedRecords,
  headingAnchors,
  ledgerStatement,
  ledgerStates,
  section,
  withoutComments,
} from '../helpers/docs.ts'
import { readRepoFile, repoRoot } from '../helpers/files.ts'

const security = readRepoFile('SECURITY.md')
const prose = withoutComments(security)
const readmeProse = withoutComments(readRepoFile('README.md'))
const applySql = readRepoFile('example', 'redacted', 'redacted-views.sql')

/** The paragraphs of a section: blocks of text separated by blank lines, trimmed. */
function paragraphs(text: string): string[] {
  return text
    .split(/\n\s*\n/)
    .map((block) => block.trim())
    .filter((block) => block !== '')
}

/** A table's separator row, such as `|---|---|`. */
const SEPARATOR = /^\|[-| ]+\|$/

/** The first cell of every body row of the tables in `text`: header and separator rows skipped. */
function firstColumn(text: string): string[] {
  const lines = text.split('\n')
  const header = (index: number): boolean => SEPARATOR.test(lines[index + 1] ?? '')
  return lines
    .filter((line, index) => line.startsWith('|') && !SEPARATOR.test(line) && !header(index))
    .map((row) => row.split(/(?<!\\)\|/)[1]?.trim() ?? '')
}

const README_GUARANTEES = section(readmeProse, 'What it guarantees and what it does not')
const CHECKLIST = section(prose, 'Hardening checklist')

describe('SECURITY.md (a view of LEDGER.md)', () => {
  it('D41: routes reports through GitHub private vulnerability reporting', () => {
    expect(prose).toContain('GitHub private vulnerability reporting')
    expect(prose).toContain('https://github.com/bergbacher/hyde-db/security/advisories/new')
    expect(prose).toContain('Do not open a public issue')
  })

  it('D133: only the latest release is supported, in the ledger’s words', () => {
    expect(section(prose, 'Supported versions')).toContain(ledgerStatement('D133'))
    expect(citedRecords(security).has('D133')).toBe(true)
  })

  it('D93, D14, D132: states the README guarantee and its time scope word for word', () => {
    const [guarantee, sessionDefaults] = paragraphs(README_GUARANTEES).slice(1, 3)
    expect(guarantee).toMatch(/^The guarantee is the privilege setup/)
    expect(guarantee).toContain('can read no table data outside the generated views')
    expect(guarantee).toContain(
      'It holds as of each successful apply: a grant made later is not prevented, and the next apply refuses it.',
    )
    expect(sessionDefaults).toContain('are session defaults, not guarantees')
    expect(prose).toContain(guarantee)
    expect(prose).toContain(sessionDefaults)
  })

  it('D93, D34, D15, D50: lists exactly the README non-guarantees, in the same order', () => {
    const readmeRows = firstColumn(README_GUARANTEES)
    expect(readmeRows.length).toBeGreaterThanOrEqual(8)
    expect(firstColumn(section(prose, 'What hyde-db does not guarantee'))).toEqual(readmeRows)
  })

  it('D93: gives the optional large-object hardening and its cost, as the README does', () => {
    const statement =
      'REVOKE EXECUTE ON FUNCTION lo_create(oid), lo_creat(integer), lo_from_bytea(oid, bytea) FROM PUBLIC;'
    expect(readmeProse).toContain(statement)
    expect(CHECKLIST).toContain(statement)
  })

  it('D11, D13, D24, D49, D58, D141: says the final check refuses every kind of access the apply script checks, and that a refusal changes nothing', () => {
    // The aborts after the header of the final check; the guards before the drop come earlier.
    const finalCheck = applySql.slice(applySql.indexOf('-- Safety check'))
    const finalChecks = (finalCheck.match(/RAISE EXCEPTION/g) ?? []).length
    expect(finalChecks).toBeGreaterThanOrEqual(14)
    const enforced = section(prose, 'How the guarantee is enforced', '###')
    expect(enforced).toContain(`${finalChecks} kinds of access`)
    expect(enforced).toContain('nothing changes')
    expect(enforced).toContain('Generated by hyde-db')
    expect(enforced).toContain('objects outside it that depend on its views')
    expect(enforced).toContain('never changes the reader role')
    expect(enforced).toContain('README.md#what-the-apply-script-refuses')
  })

  it('D135: states only what the tests show about pasted fixes, as the README does', () => {
    const evidence =
      'The integration tests paste each printed fix and re-apply; the fix tests also compare ACL entries before and after the paste.'
    expect(readmeProse).toContain(evidence)
    expect(section(prose, 'How the guarantee is enforced', '###')).toContain(evidence)
    expect(prose).not.toContain('proves each refusal and each printed fix')
  })

  it('D15: gives the REVOKE CONNECT step', () => {
    expect(CHECKLIST).toContain('REVOKE CONNECT ON DATABASE other_database FROM PUBLIC;')
  })

  it('A99, D140: the cluster step says a role belongs to the whole cluster and gives each database its own role, as the README does', () => {
    const sentence = 'give each database, and each generator block, its own `role`'
    expect(CHECKLIST).toContain('A role belongs to the whole cluster')
    expect(CHECKLIST).toContain(sentence)
    expect(readmeProse).toContain(sentence)
  })

  it("A15, A95, D24: gives the REVOKE CREATE step for PostgreSQL 14 and older, run in the application's database by the owner of public or a superuser", () => {
    expect(CHECKLIST).toContain('REVOKE CREATE ON SCHEMA public FROM PUBLIC;')
    expect(CHECKLIST).toContain('PostgreSQL 14 and older')
    expect(CHECKLIST).toContain("in the application's database")
    expect(CHECKLIST).toContain('the owner of schema `public` or a superuser')
    expect(CHECKLIST).toContain('no privileges could be revoked')
  })

  it('D50: gives the optional REVOKE TEMPORARY step and says it affects every role', () => {
    expect(CHECKLIST).toContain('REVOKE TEMPORARY ON DATABASE app_database FROM PUBLIC;')
    expect(CHECKLIST).toContain('affects every role')
    expect(CHECKLIST).toContain('read replica')
  })

  it('every link into the repository points at a file and, with an anchor, at a heading of it', () => {
    const links = Array.from(prose.matchAll(/\]\(([^)]+)\)/g), (m) => m[1] ?? '').filter(
      (target) => !/^[a-z]+:/.test(target),
    )
    expect(links.length).toBeGreaterThan(0)
    for (const link of links) {
      // A bare `#anchor` points into SECURITY.md itself.
      const [path = '', fragment] = link.split('#')
      const file = path === '' ? 'SECURITY.md' : path
      expect(existsSync(join(repoRoot, file)), link).toBe(true)
      if (fragment !== undefined)
        expect(headingAnchors(readRepoFile(file)), link).toContain(fragment)
    }
  })

  it('D41: the README links here', () => {
    expect(readmeProse).toContain('[SECURITY.md](SECURITY.md)')
  })

  it('keeps record IDs in HTML comments, cites only live records, and ends with the view footer', () => {
    expect(prose).not.toMatch(/\b[ADCQ]\d+\b/)
    const states = ledgerStates()
    const cited = citedRecords(security)
    expect(cited.size).toBeGreaterThan(0)
    for (const id of cited) {
      expect(['active', 'verified', 'open', 'answered'], id).toContain(states.get(id))
    }
    expect(security.trimEnd()).toMatch(/\n---\n\nView on LEDGER\.md, \d{4}-\d{2}-\d{2}$/)
  })
})
