// SECURITY.md is a view of LEDGER.md. It states the same guarantee and non-guarantees as the
// README (D93), word for word where the README states them, plus the private reporting path (D41)
// and a hardening checklist; these tests keep the two documents from drifting apart.
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { readRepoFile, repoRoot } from '../helpers/files.ts'

const security = readRepoFile('SECURITY.md')
const prose = security.replace(/<!--[\s\S]*?-->/g, '')
const readme = readRepoFile('README.md')
const readmeProse = readme.replace(/<!--[\s\S]*?-->/g, '')
const applySql = readRepoFile('example', 'redacted', 'redacted-views.sql')

/** A section of a document, from its heading (`##` unless given) up to the next `## ` heading. */
function section(text: string, heading: string, level = '##'): string {
  const start = text.indexOf(`\n${level} ${heading}\n`)
  if (start === -1) throw new Error(`no "${level} ${heading}" section`)
  const end = text.indexOf('\n## ', start + 1)
  return text.slice(start, end === -1 ? undefined : end)
}

/** The paragraphs of a section: blocks of text separated by blank lines, trimmed. */
function paragraphs(text: string): string[] {
  return text
    .split(/\n\s*\n/)
    .map((block) => block.trim())
    .filter((block) => block !== '')
}

/** A table's separator row, such as `|---|---|`. */
const SEPARATOR = /^\|[-| ]+\|$/

/** The first cell of every body row of the tables in `text`: header and separator rows skipped. */
function firstColumn(text: string): string[] {
  const lines = text.split('\n')
  const header = (index: number): boolean => SEPARATOR.test(lines[index + 1] ?? '')
  return lines
    .filter((line, index) => line.startsWith('|') && !SEPARATOR.test(line) && !header(index))
    .map((row) => row.split(/(?<!\\)\|/)[1]?.trim() ?? '')
}

/** GitHub's anchor for a heading: lower case, punctuation other than `-` dropped, spaces as `-`. */
function anchor(heading: string): string {
  return heading
    .toLowerCase()
    .replace(/[^\w\- ]/g, '')
    .replaceAll(' ', '-')
}

const README_GUARANTEES = section(readmeProse, 'What it guarantees and what it does not')

/** Record ID → state, read from the end of each row: a statement may hold an unescaped pipe. */
function ledgerStates(): Map<string, string> {
  const states = new Map<string, string>()
  for (const line of readRepoFile('LEDGER.md').split('\n')) {
    const row = line.split(/(?<!\\)\|/).map((cell) => cell.trim())
    const id = row[1]
    if (id !== undefined && /^[ADCQ]\d+$/.test(id)) states.set(id, row.at(-4) ?? '')
  }
  return states
}

describe('SECURITY.md (a view of LEDGER.md)', () => {
  it('D41: routes reports through GitHub private vulnerability reporting', () => {
    expect(prose).toContain('GitHub private vulnerability reporting')
    expect(prose).toContain('https://github.com/bergbacher/hyde-db/security/advisories/new')
    expect(prose).toContain('Do not open a public issue')
  })

  it('D93, D14: states the README guarantee word for word', () => {
    const [guarantee, sessionDefaults] = paragraphs(README_GUARANTEES).slice(1, 3)
    expect(guarantee).toMatch(/^The guarantee is the privilege setup/)
    expect(guarantee).toContain('can read no table data outside the generated views')
    expect(sessionDefaults).toContain('are session defaults, not guarantees')
    expect(prose).toContain(guarantee)
    expect(prose).toContain(sessionDefaults)
  })

  it('D93, D34, D15, D50: lists exactly the README non-guarantees, in the same order', () => {
    const readmeRows = firstColumn(README_GUARANTEES)
    expect(readmeRows.length).toBeGreaterThanOrEqual(8)
    expect(firstColumn(section(prose, 'What hyde-db does not guarantee'))).toEqual(readmeRows)
  })

  it('D93: gives the optional large-object hardening and its cost, as the README does', () => {
    const statement =
      'REVOKE EXECUTE ON FUNCTION lo_create(oid), lo_creat(integer), lo_from_bytea(oid, bytea) FROM PUBLIC;'
    expect(readmeProse).toContain(statement)
    expect(prose).toContain(statement)
  })

  it('D11, D13, D24, D49, D58: says the final check refuses every kind of access the apply script checks, and that a refusal changes nothing', () => {
    // Every RAISE EXCEPTION but the first (the schema-marker guard) is a final-check abort.
    const finalChecks = (applySql.match(/RAISE EXCEPTION/g) ?? []).length - 1
    expect(finalChecks).toBeGreaterThanOrEqual(13)
    const enforced = section(prose, 'How the guarantee is enforced', '###')
    expect(enforced).toContain(`${finalChecks} kinds of access`)
    expect(enforced).toContain('nothing changes')
    expect(enforced).toContain('Generated by hyde-db')
    expect(enforced).toContain('never changes the reader role')
    expect(enforced).toContain('README.md#what-the-apply-script-refuses')
  })

  it('D15: gives the REVOKE CONNECT step', () => {
    expect(section(prose, 'Hardening checklist')).toContain(
      'REVOKE CONNECT ON DATABASE other_database FROM PUBLIC;',
    )
  })

  it('D24, A15: gives the REVOKE CREATE step for PostgreSQL 14 and older', () => {
    const checklist = section(prose, 'Hardening checklist')
    expect(checklist).toContain('REVOKE CREATE ON SCHEMA public FROM PUBLIC;')
    expect(checklist).toContain('PostgreSQL 14 and older')
  })

  it('D50: gives the optional REVOKE TEMPORARY step and says it affects every role', () => {
    const checklist = section(prose, 'Hardening checklist')
    expect(checklist).toContain('REVOKE TEMPORARY ON DATABASE app_database FROM PUBLIC;')
    expect(checklist).toContain('affects every role')
    expect(checklist).toContain('read replica')
  })

  it('every link into the repository points at a file and, with an anchor, at a heading', () => {
    const links = Array.from(prose.matchAll(/\]\(([^)]+)\)/g), (m) => m[1] ?? '').filter(
      (target) => !/^[a-z]+:/.test(target),
    )
    expect(links.length).toBeGreaterThan(0)
    for (const link of links) {
      // A bare `#anchor` points into SECURITY.md itself.
      const [path = '', fragment] = link.split('#')
      const file = path === '' ? 'SECURITY.md' : path
      expect(existsSync(join(repoRoot, file)), link).toBe(true)
      if (fragment !== undefined) {
        const headings = readRepoFile(file)
          .split('\n')
          .filter((line) => /^#{1,6} /.test(line))
          .map((line) => anchor(line.replace(/^#+ /, '')))
        expect(headings, link).toContain(fragment)
      }
    }
  })

  it('D41: the README links here', () => {
    expect(readmeProse).toContain('[SECURITY.md](SECURITY.md)')
  })

  it('keeps record IDs in HTML comments, cites only live records, and ends with the view footer', () => {
    expect(prose).not.toMatch(/\b[ADCQ]\d+\b/)
    const states = ledgerStates()
    const cited = new Set(
      Array.from(security.matchAll(/<!--[\s\S]*?-->/g), (match) =>
        Array.from(match[0].matchAll(/\b[ADCQ]\d+\b/g), (id) => id[0]),
      ).flat(),
    )
    expect(cited.size).toBeGreaterThan(0)
    for (const id of cited) {
      expect(['active', 'verified', 'open', 'answered'], id).toContain(states.get(id))
    }
    expect(security.trimEnd()).toMatch(/\n---\n\nView on LEDGER\.md, \d{4}-\d{2}-\d{2}$/)
  })
})
