-- GENERATED by hyde-db. Run BEFORE `prisma migrate deploy` so that
-- migrations can drop/alter columns that the redacted views depend on.
BEGIN;
SET LOCAL client_min_messages = warning;
SET LOCAL lock_timeout = '60s';
-- Refuse to drop a schema that hyde-db did not create.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'redacted'
             AND NOT (coalesce(obj_description(oid, 'pg_namespace'), '') = 'Generated by hyde-db'
                      OR starts_with(coalesce(obj_description(oid, 'pg_namespace'), ''), 'Generated by hyde-db.'))) THEN
    RAISE EXCEPTION 'hyde-db: schema redacted exists but was not created by hyde-db (its comment lacks the "Generated by hyde-db" marker); refusing to drop it. Rename or drop that schema yourself, or set the generator config "schema" to an unused name.';
  END IF;
END $$;
-- Refuse to drop objects outside schema redacted that depend on its views.
DO $$
DECLARE
  dependents text;
BEGIN
  SELECT string_agg(DISTINCT format('%s %s', i.type, i.identity) COLLATE "C", ', ' ORDER BY format('%s %s', i.type, i.identity) COLLATE "C") INTO dependents
  FROM pg_namespace s
    JOIN pg_depend d
      ON d.refclassid = 'pg_class'::regclass AND d.refobjid IN (SELECT c.oid FROM pg_class c WHERE c.relnamespace = s.oid)
      OR d.refclassid = 'pg_type'::regclass AND d.refobjid IN (SELECT t.oid FROM pg_type t WHERE t.typnamespace = s.oid)
    LEFT JOIN pg_rewrite w ON d.classid = 'pg_rewrite'::regclass AND w.oid = d.objid
    LEFT JOIN pg_trigger tg ON d.classid = 'pg_trigger'::regclass AND tg.oid = d.objid
    LEFT JOIN pg_policy po ON d.classid = 'pg_policy'::regclass AND po.oid = d.objid
    LEFT JOIN pg_attrdef ad ON d.classid = 'pg_attrdef'::regclass AND ad.oid = d.objid
    CROSS JOIN LATERAL pg_identify_object(CASE WHEN w.oid IS NULL THEN d.classid ELSE 'pg_class'::regclass END, coalesce(w.ev_class, d.objid), CASE WHEN w.oid IS NULL THEN d.objsubid ELSE 0 END) i
    CROSS JOIN LATERAL (SELECT coalesce((SELECT n.nspname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE c.oid = coalesce(w.ev_class, tg.tgrelid, po.polrelid, ad.adrelid)), i.schema) AS schema) h
  WHERE s.nspname = 'redacted'
    AND d.deptype IN ('n', 'a')
    AND h.schema IS DISTINCT FROM 'redacted'
    AND coalesce(h.schema, '') !~ '^pg_(toast_)?temp_'
    AND NOT EXISTS (SELECT 1 FROM pg_depend o CROSS JOIN LATERAL pg_identify_object(o.refclassid, o.refobjid, 0) oi WHERE o.classid = d.classid AND o.objid = d.objid AND oi.schema ~ '^pg_(toast_)?temp_');
  IF dependents IS NOT NULL THEN
    RAISE EXCEPTION 'hyde-db: objects outside schema redacted depend on its views: %; refusing to drop them with the schema. Drop them before the deploy, and create them again after it if you still need them.', dependents;
  END IF;
END $$;
DROP SCHEMA IF EXISTS "redacted" CASCADE;
COMMIT;
