-- GENERATED by hyde-db. Run BEFORE `prisma migrate deploy` so that
-- migrations can drop/alter columns that the redacted views depend on.
SET client_min_messages = warning;
BEGIN;
SET LOCAL lock_timeout = '60s';
-- Refuse to drop a schema that hyde-db did not create.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'redacted'
             AND NOT (coalesce(obj_description(oid, 'pg_namespace'), '') = 'Generated by hyde-db'
                      OR starts_with(coalesce(obj_description(oid, 'pg_namespace'), ''), 'Generated by hyde-db.'))) THEN
    RAISE EXCEPTION 'hyde-db: schema redacted exists but was not created by hyde-db (its comment lacks the "Generated by hyde-db" marker); refusing to drop it. Rename or drop that schema yourself, or set the generator config "schema" to an unused name.';
  END IF;
END $$;
DROP SCHEMA IF EXISTS "redacted" CASCADE;
COMMIT;
