// D11: the scripts only drop a redacted schema that carries the "Generated by hyde-db" marker.
// D141: they never drop objects outside it that depend on its views (A97).
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import {
  adminQuery,
  apply,
  buildFiles,
  connectAsReader,
  createTestDatabase,
  dropTestDatabase,
  psql,
  type TestDb,
} from './helpers/db.ts'

let db: TestDb
beforeEach(async () => {
  db = await createTestDatabase()
})
afterEach(async () => {
  await dropTestDatabase(db)
})

const plantForeignSchema = (comment?: string): void => {
  const script = [
    'CREATE SCHEMA redacted;',
    'CREATE TABLE redacted.keep (id int);',
    'INSERT INTO redacted.keep VALUES (1);',
    comment === undefined ? '' : `COMMENT ON SCHEMA redacted IS '${comment}';`,
  ].join('\n')
  expect(psql(db.name, script).status).toBe(0)
}

describe('schema marker', () => {
  it('D11: apply refuses to drop an existing schema without the hyde-db marker', async () => {
    plantForeignSchema()
    const result = apply(db)
    expect(result.status).toBe(3)
    expect(result.stderr).toContain('schema redacted exists but was not created by hyde-db')
    expect(await adminQuery(db.name, 'SELECT id FROM redacted.keep')).toEqual([{ id: 1 }])
  })

  it('D11: the drop script refuses an unmarked schema too', async () => {
    plantForeignSchema('Owned by the analytics team')
    const result = psql(db.name, db.files['redacted-views-drop.sql'])
    expect(result.status).toBe(3)
    expect(result.stderr).toContain('refusing to drop it')
    expect(await adminQuery(db.name, 'SELECT id FROM redacted.keep')).toEqual([{ id: 1 }])
  })

  it('D11: a comment that merely contains the marker is refused', async () => {
    plantForeignSchema('Not Generated by hyde-db')
    const result = apply(db)
    expect(result.status).toBe(3)
    expect(result.stderr).toContain('schema redacted exists but was not created by hyde-db')
    expect(await adminQuery(db.name, 'SELECT id FROM redacted.keep')).toEqual([{ id: 1 }])
  })

  it('D58: a look-alike marker such as "Generated by hyde-dbx" is refused', async () => {
    plantForeignSchema('Generated by hyde-dbx')
    const result = apply(db)
    expect(result.status).toBe(3)
    expect(result.stderr).toContain('schema redacted exists but was not created by hyde-db')
    expect(await adminQuery(db.name, 'SELECT id FROM redacted.keep')).toEqual([{ id: 1 }])
  })

  it('D58: the drop script drops nothing under a client without ON_ERROR_STOP', async () => {
    plantForeignSchema()
    const result = psql(db.name, db.files['redacted-views-drop.sql'], { onErrorStop: false })
    // Without ON_ERROR_STOP psql runs past the refused guard and exits 0; the DROP still must not happen.
    expect(result.status).toBe(0)
    expect(result.stderr).toContain('refusing to drop it')
    expect(await adminQuery(db.name, 'SELECT id FROM redacted.keep')).toEqual([{ id: 1 }])
  })

  it('D11: a schema created by hyde-db is replaced by apply and dropped by the drop script', async () => {
    expect(apply(db).status).toBe(0)
    expect(apply(db).status).toBe(0)
    expect(psql(db.name, db.files['redacted-views-drop.sql']).status).toBe(0)
    expect(
      await adminQuery(db.name, "SELECT 1 FROM pg_namespace WHERE nspname = 'redacted'"),
    ).toEqual([])
  })
})

describe('objects that depend on the views', () => {
  const DEPENDENTS = 'objects outside schema redacted depend on its views'
  const SCRIPTS = ['redacted-views.sql', 'redacted-views-drop.sql'] as const

  /** The OID of the view redacted.users, which changes whenever a script recreates the schema. */
  async function viewOid(): Promise<unknown> {
    const [row] = await adminQuery(db.name, "SELECT 'redacted.users'::regclass::oid AS oid")
    return row?.oid
  }

  it('A97, D141: a view in another schema on a redacted view refuses apply and drop, naming it, and nothing changes', async () => {
    expect(apply(db).status).toBe(0)
    await adminQuery(
      db.name,
      'CREATE SCHEMA analytics; CREATE VIEW analytics.report AS SELECT count(*) AS n FROM redacted.users',
    )
    const before = await viewOid()
    for (const file of SCRIPTS) {
      const result = psql(db.name, db.files[file])
      expect(result.status, file).toBe(3)
      expect(result.stderr, file).toContain(`${DEPENDENTS}: view analytics.report;`)
      expect(await viewOid(), file).toBe(before)
      expect(await adminQuery(db.name, 'SELECT n FROM analytics.report'), file).toEqual([
        { n: '1' },
      ])
    }
    // The way out the abort gives: drop it before the deploy, create it again after.
    await adminQuery(db.name, 'DROP VIEW analytics.report')
    expect(psql(db.name, db.files['redacted-views-drop.sql']).status).toBe(0)
    expect(apply(db).status).toBe(0)
    await adminQuery(
      db.name,
      'CREATE VIEW analytics.report AS SELECT count(*) AS n FROM redacted.users',
    )
  })

  it('A97, D141: functions, columns and policies outside the schema that depend on its views are named too', async () => {
    expect(apply(db).status).toBe(0)
    await adminQuery(
      db.name,
      `CREATE SCHEMA analytics;
       CREATE FUNCTION analytics.users() RETURNS bigint LANGUAGE sql BEGIN ATOMIC SELECT count(*) FROM redacted.users; END;
       CREATE TABLE analytics.snapshot (id int, taken redacted.users);
       CREATE TABLE analytics.audit (id int); ALTER TABLE analytics.audit ENABLE ROW LEVEL SECURITY;
       CREATE POLICY visible ON analytics.audit USING (id IN (SELECT id FROM redacted.users))`,
    )
    for (const file of SCRIPTS) {
      const result = psql(db.name, db.files[file])
      expect(result.status, file).toBe(3)
      expect(result.stderr, file).toContain(
        `${DEPENDENTS}: function analytics.users(), policy visible on analytics.audit, table column analytics.snapshot.taken;`,
      )
    }
  })

  it("D141: a reader's temporary objects that depend on the views do not block a deploy", async () => {
    expect(apply(db).status).toBe(0)
    const reader = await connectAsReader(db)
    try {
      // A schema's drop takes a dependent column, not its table; what is left goes first.
      const plant = async (): Promise<void> => {
        await reader.query('DROP TABLE IF EXISTS kept; DROP TYPE IF EXISTS pg_temp.shape CASCADE')
        await reader.query('CREATE TEMP VIEW mine AS SELECT * FROM redacted.users')
        await reader.query('CREATE TEMP TABLE kept (taken redacted.users)')
        await reader.query('CREATE TYPE pg_temp.shape AS (id int)')
        await reader.query('CREATE CAST (pg_temp.shape AS redacted.users) WITH INOUT')
      }
      await reader.query('SET default_transaction_read_only = off')
      await plant()
      const applied = apply(db)
      expect(applied.status, applied.stderr).toBe(0)
      // The apply dropped them with the old views; the reader plants them again.
      await plant()
      const dropped = psql(db.name, db.files['redacted-views-drop.sql'])
      expect(dropped.status, dropped.stderr).toBe(0)
    } finally {
      await reader.end()
    }
  })

  it('A97, D141: the check does not grow with the rest of the database: with 3000 more tables, apply and drop each finish within 3 seconds', async () => {
    // Batches of 500 tables, each in a transaction of its own, so PostgreSQL 14 does not run out
    // of lock slots.
    await adminQuery(db.name, 'CREATE SCHEMA bulk')
    for (let first = 1; first <= 3000; first += 500) {
      await adminQuery(
        db.name,
        `DO $$ BEGIN FOR i IN ${first}..${first + 499} LOOP
           EXECUTE format('CREATE TABLE bulk.t%s (id serial PRIMARY KEY, note text)', i);
         END LOOP; END $$`,
      )
    }
    expect(apply(db).status).toBe(0)
    for (const file of SCRIPTS) {
      const started = Date.now()
      const result = psql(db.name, db.files[file])
      const seconds = (Date.now() - started) / 1000
      expect(result.status, result.stderr).toBe(0)
      // A bound, not a benchmark: the quadratic guard took 5 to 8 seconds here on PostgreSQL 18.
      expect(seconds, file).toBeLessThan(3)
    }
  })

  it('D141: a views schema named with a reserved word counts as itself, so only objects outside it are refused', async () => {
    // pg_identify_object writes such a schema quoted: "user".
    const files = buildFiles(db.role, undefined, { schema: 'user' })
    expect(psql(db.name, files['redacted-views.sql']).status).toBe(0)
    const inside =
      'CREATE FUNCTION "user".count_users(u "user".users) RETURNS int LANGUAGE sql AS \'SELECT 1\''
    await adminQuery(db.name, inside)
    const reapplied = psql(db.name, files['redacted-views.sql'])
    expect(reapplied.status, reapplied.stderr).toBe(0)
    await adminQuery(db.name, inside)
    const dropped = psql(db.name, files['redacted-views-drop.sql'])
    expect(dropped.status, dropped.stderr).toBe(0)
    expect(psql(db.name, files['redacted-views.sql']).status).toBe(0)
    await adminQuery(
      db.name,
      'CREATE SCHEMA analytics; CREATE VIEW analytics.report AS SELECT * FROM "user".users',
    )
    for (const sql of [files['redacted-views.sql'], files['redacted-views-drop.sql']]) {
      const refused = psql(db.name, sql)
      expect(refused.status).toBe(3)
      expect(refused.stderr).toContain(
        'objects outside schema user depend on its views: view analytics.report;',
      )
    }
  })
})
