// D11: the scripts only drop a redacted schema that carries the "Generated by hyde-db" marker.
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import {
  adminQuery,
  apply,
  createTestDatabase,
  dropTestDatabase,
  psql,
  type TestDb,
} from './helpers/db.ts'

let db: TestDb
beforeEach(async () => {
  db = await createTestDatabase()
})
afterEach(async () => {
  await dropTestDatabase(db)
})

const plantForeignSchema = (comment?: string): void => {
  const script = [
    'CREATE SCHEMA redacted;',
    'CREATE TABLE redacted.keep (id int);',
    'INSERT INTO redacted.keep VALUES (1);',
    comment === undefined ? '' : `COMMENT ON SCHEMA redacted IS '${comment}';`,
  ].join('\n')
  expect(psql(db.name, script).status).toBe(0)
}

describe('schema marker', () => {
  it('D11: apply refuses to drop an existing schema without the hyde-db marker', async () => {
    plantForeignSchema()
    const result = apply(db)
    expect(result.status).toBe(3)
    expect(result.stderr).toContain('schema redacted exists but was not created by hyde-db')
    expect(await adminQuery(db.name, 'SELECT id FROM redacted.keep')).toEqual([{ id: 1 }])
  })

  it('D11: the drop script refuses an unmarked schema too', async () => {
    plantForeignSchema('Owned by the analytics team')
    const result = psql(db.name, db.files['redacted-views-drop.sql'])
    expect(result.status).toBe(3)
    expect(result.stderr).toContain('refusing to drop it')
    expect(await adminQuery(db.name, 'SELECT id FROM redacted.keep')).toEqual([{ id: 1 }])
  })

  it('D11: a comment that merely contains the marker is refused', async () => {
    plantForeignSchema('Not Generated by hyde-db')
    const result = apply(db)
    expect(result.status).toBe(3)
    expect(result.stderr).toContain('schema redacted exists but was not created by hyde-db')
    expect(await adminQuery(db.name, 'SELECT id FROM redacted.keep')).toEqual([{ id: 1 }])
  })

  it('D58: a look-alike marker such as "Generated by hyde-dbx" is refused', async () => {
    plantForeignSchema('Generated by hyde-dbx')
    const result = apply(db)
    expect(result.status).toBe(3)
    expect(result.stderr).toContain('schema redacted exists but was not created by hyde-db')
    expect(await adminQuery(db.name, 'SELECT id FROM redacted.keep')).toEqual([{ id: 1 }])
  })

  it('D58: the drop script drops nothing under a client without ON_ERROR_STOP', async () => {
    plantForeignSchema()
    const result = psql(db.name, db.files['redacted-views-drop.sql'], { onErrorStop: false })
    // Without ON_ERROR_STOP psql runs past the refused guard and exits 0; the DROP still must not happen.
    expect(result.status).toBe(0)
    expect(result.stderr).toContain('refusing to drop it')
    expect(await adminQuery(db.name, 'SELECT id FROM redacted.keep')).toEqual([{ id: 1 }])
  })

  it('D11: a schema created by hyde-db is replaced by apply and dropped by the drop script', async () => {
    expect(apply(db).status).toBe(0)
    expect(apply(db).status).toBe(0)
    expect(psql(db.name, db.files['redacted-views-drop.sql']).status).toBe(0)
    expect(
      await adminQuery(db.name, "SELECT 1 FROM pg_namespace WHERE nspname = 'redacted'"),
    ).toEqual([])
  })
})
